function ghCfg(){const d=data(),base={repoOwner:d.settings?.repoOwner||'pierceyalex5-star',repoName:d.settings?.repoName||'finance-department-performance',branch:d.settings?.branch||'main',autoSyncSeconds:d.settings?.autoSyncSeconds||60,autoSync:false};try{Object.assign(base,JSON.parse(localStorage.getItem(GHLS)||'{}'))}catch{};base.token=sessionStorage.getItem('d365-gh-token')||localStorage.getItem('d365-gh-token')||'';return base}
function saveGhCfg(c,remember){const clean={repoOwner:c.repoOwner,repoName:c.repoName,branch:c.branch,autoSyncSeconds:+c.autoSyncSeconds||60,autoSync:!!c.autoSync};localStorage.setItem(GHLS,JSON.stringify(clean));sessionStorage.setItem('d365-gh-token',c.token||'');if(remember)localStorage.setItem('d365-gh-token',c.token||'');else localStorage.removeItem('d365-gh-token');setupPolling()}
function ghHeaders(t){const h={'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};if(t)h.Authorization=`Bearer ${t}`;return h}
function b64d(s){const bin=atob(s.replace(/\n/g,'')),u=Uint8Array.from(bin,c=>c.charCodeAt(0));return new TextDecoder().decode(u)}
function b64e(s){const u=new TextEncoder().encode(s);let b='';for(const x of u)b+=String.fromCharCode(x);return btoa(b)}
async function ghRead(path,c=ghCfg()){const u=`https://api.github.com/repos/${encodeURIComponent(c.repoOwner)}/${encodeURIComponent(c.repoName)}/contents/${path.split('/').map(encodeURIComponent).join('/')}?ref=${encodeURIComponent(c.branch)}`;const r=await fetch(u,{headers:ghHeaders(c.token)});if(!r.ok)throw Error(`GitHub read failed (${r.status}) ${path}`);const j=await r.json();return {sha:j.sha,value:JSON.parse(b64d(j.content))}}
async function ghWrite(path,value,msg,c=ghCfg()){if(!c.token)throw Error('A fine-grained GitHub token with Contents read/write permission is required for shared edits.');let sha;try{sha=(await ghRead(path,c)).sha}catch(e){if(!String(e).includes('(404)'))throw e}const u=`https://api.github.com/repos/${encodeURIComponent(c.repoOwner)}/${encodeURIComponent(c.repoName)}/contents/${path.split('/').map(encodeURIComponent).join('/')}`;const body={message:msg,content:b64e(JSON.stringify(value,null,2)),branch:c.branch};if(sha)body.sha=sha;const r=await fetch(u,{method:'PUT',headers:{...ghHeaders(c.token),'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){const j=await r.json().catch(()=>({}));throw Error(j.message||`GitHub write failed (${r.status})`)}return r.json()}
function payloadFor(k){if(['framework','processes','registers','tasks','milestones'].includes(k))return {path:filePath(k),value:state[k]};if(flowChunks[k])return {path:`d365-control-tower/${k}`,value:flowChunks[k].map(({_file,...f})=>f)};return null}
async function pushGithub(silent=false){if(!dirtyFiles.size)return;const c=ghCfg();if(!c.token){if(!silent)setSync('local changes · GitHub token required');return}setSync('saving…');try{for(const k of [...dirtyFiles]){const p=payloadFor(k);if(!p)continue;await ghWrite(p.path,p.value,`D365 Control Tower update: ${k} ${new Date().toISOString()}`,c);dirtyFiles.delete(k)}saveLocal();setSync('synced')}catch(e){setSync('sync conflict/error');if(!silent)alert(e.message)}}
function schedulePush(){clearTimeout(syncTimer);const c=ghCfg();if(c.autoSync&&c.token)syncTimer=setTimeout(()=>pushGithub(true),1800)}
async function pullGithub(force=false){if(dirtyFiles.size&&!force&&!confirm('Local edits are pending. Replace them with GitHub?'))return;setSync('pulling…');try{const c=ghCfg();const keys=['framework','processes','registers','tasks','milestones'];const results=await Promise.all(keys.map(k=>ghRead(filePath(k),c)));keys.forEach((k,i)=>state[k]=results[i].value);const manifest=(await ghRead(filePath('flowManifest'),c)).value;flowManifest=manifest;const paths=[...new Set(Object.values(manifest).flat())];const vals=await Promise.all(paths.map(p=>ghRead(`d365-control-tower/${p}`,c)));flowChunks={};paths.forEach((p,i)=>flowChunks[p]=vals[i].value);dirtyFiles.clear();rebuildFlows();saveLocal();render();setSync('synced')}catch(e){setSync('sync error');alert(e.message)}}
function setupPolling(){clearInterval(pullTimer);const c=ghCfg();if(c.autoSync)pullTimer=setInterval(async()=>{if(dirtyFiles.size)return;try{await pullGithub(true)}catch{}},Math.max(30,+c.autoSyncSeconds||60)*1000)}
function renderSync(){const c=ghCfg();return `<div class="page-head"><div><h1>GitHub Sync</h1><p>Static site + GitHub JSON. No Vercel/Neon application backend, Teams integration or notifications.</p></div>${badge(dirtyFiles.size?`${dirtyFiles.size} pending`:'Synced')}</div><div class="grid two-col"><div class="card pad"><h3>Repository connection</h3><div class="form-grid"><label>Owner<input id="ghOwner" value="${esc(c.repoOwner)}"></label><label>Repository<input id="ghRepo" value="${esc(c.repoName)}"></label><label>Branch<input id="ghBranch" value="${esc(c.branch)}"></label><label>Auto-sync seconds<input id="ghSeconds" type="number" min="30" value="${c.autoSyncSeconds}"></label><label class="full">Fine-grained GitHub token<input id="ghToken" type="password" value="${esc(c.token)}" placeholder="Contents: Read and write"></label><label class="check"><input id="ghRemember" type="checkbox" ${localStorage.getItem('d365-gh-token')?'checked':''}> Remember token on this device</label><label class="check"><input id="ghAuto" type="checkbox" ${c.autoSync?'checked':''}> Auto-sync edits</label></div><div class="modal-actions"><button class="btn" id="saveGh">Save settings</button><button class="btn" id="pullGh">Pull latest</button><button class="btn primary" id="pushGh">Push now</button></div></div><div class="card pad"><h3>Team operating model</h3><ol class="activity-list"><li>Everyone reads the same public GitHub baseline.</li><li>Editors use their own GitHub token; the token stays in the browser only.</li><li>Changes are committed to GitHub JSON and Vercel redeploys automatically.</li><li>Each process-flow chunk is stored separately to reduce edit conflicts.</li><li>Git history provides the audit trail.</li></ol><div class="notice warning"><b>Concurrency:</b> GitHub is not a real-time database. During a workshop, use one designated editor for the same process map at a time.</div></div></div>`}
