// IFAST D365 Transformation Control Tower V2 overlay
// Extends the original Finance-Control-Tower-style static GitHub deployment without a new backend.
function vreg(name){state.registers=state.registers||{};return state.registers[name]||(state.registers[name]=[])}
function clampPct(v){return Math.max(0,Math.min(100,Math.round(Number(v)||0)))}
function fmtPct(v){return `${clampPct(v)}%`}
function dateAt(s){return s?new Date(`${s}T00:00:00`):null}
function daysFromToday(s){const d=dateAt(s);if(!d)return null;const t=dateAt(today());return Math.ceil((d-t)/86400000)}
function badge(s){const x=String(s||'').toLowerCase();let c='gray';if(x.includes('critical')||x.includes('overdue')||x.includes('red')||x.includes('blocked'))c='red';else if(x.includes('high')||x.includes('amber')||x.includes('medium')||x.includes('progress')||x.includes('review')||x.includes('waiting'))c='yellow';else if(x.includes('green')||x.includes('approved')||x.includes('closed')||x.includes('decided')||x.includes('imported')||x.includes('validated')||x.includes('complete')||x.includes('passed'))c='green';return `<span class="badge ${c}">${esc(s||'—')}</span>`}
const PROJECT_DECISION_SEEDS=[
 {id:'DEC-PRG-001',category:'Governance',stream:'Program',title:'Use enterprise value streams as the organizing backbone of the D365 Transformation Control Tower.',background:'The project structure defines seven end-to-end value streams and two cross-functional capabilities.',options:'Department-based dashboard; value-stream dashboard; hybrid.',recommendation:'Use the enterprise value streams as the primary navigation and governance structure.',decisionOutcome:'Approved: M2O, O2C, F2P, P2P, S2P, W2D and R2R are the primary workstreams, with Master Data and Quality cross-functional.',rationale:'This keeps process ownership and cross-functional handoffs visible throughout design and implementation.',owner:'Business Owner',status:'Decided',decisionDate:'2026-08-14',escalateToSteering:false},
 {id:'DEC-PRG-002',category:'Deployment',stream:'Program',title:'Use the Finance Control Tower deployment pattern for the D365 Control Tower.',background:'The organization does not accept Vercel for this project and the requested deployment should follow the Finance Control Tower pattern.',options:'Vercel/Neon; internal application server; GitHub Pages with GitHub JSON synchronization.',recommendation:'Use GitHub Pages and GitHub-hosted JSON data with browser-based GitHub synchronization.',decisionOutcome:'Approved: GitHub Pages + GitHub JSON synchronization. No Vercel or Neon application backend.',rationale:'This matches the existing Finance Control Tower deployment approach and the project deployment constraint.',owner:'Business Owner',status:'Decided',decisionDate:'2026-08-14',escalateToSteering:false},
 {id:'DEC-PRG-003',category:'Scope',stream:'Program',title:'Exclude Teams integration and notifications from the current D365 Control Tower scope.',background:'The current deployment is intentionally lightweight and does not require Teams connectivity or automated notifications.',options:'Include now; defer; exclude.',recommendation:'Exclude from current scope and revisit only if organizational requirements change.',decisionOutcome:'Approved: no Teams integration and no notification capability in the current scope.',rationale:'Keeps the solution aligned with the approved lightweight deployment model.',owner:'Business Owner',status:'Decided',decisionDate:'2026-08-14',escalateToSteering:false},
 {id:'DEC-PRG-004',category:'Deployment',stream:'Program',title:'Treat the current Control Tower project data as non-private for the current GitHub Pages deployment.',background:'The Business Owner confirmed that the data used in this dashboard is not private.',options:'Private-only hosting; public GitHub Pages; defer publication.',recommendation:'Continue with the current public GitHub Pages deployment while keeping the option to change hosting if data sensitivity changes.',decisionOutcome:'Approved for the current scope: the dashboard data may be published through the existing GitHub Pages deployment.',rationale:'This is consistent with the current data classification provided for the project.',owner:'Business Owner',status:'Decided',decisionDate:'2026-08-14',escalateToSteering:false},
 {id:'DEC-PRG-005',category:'Solution design',stream:'Program',title:'Maintain editable As-Is processes in both structured text and flow-chart views with legacy traceability.',background:'The current-state package includes Visio process maps that must remain usable as a working As-Is baseline.',options:'Static document repository; flow-only editor; synchronized text and flow working views.',recommendation:'Use editable process objects and preserve the legacy process IDs and source references.',decisionOutcome:'Approved: As-Is processes remain editable and can be viewed as structured process text or interactive flow diagrams.',rationale:'This makes current-state documentation usable during workshops without losing source traceability.',owner:'Business Owner',status:'Decided',decisionDate:'2026-08-14',escalateToSteering:false},
 {id:'DEC-PRG-006',category:'Governance',stream:'Program',title:'Use a stage-gated transformation lifecycle as the core governance model.',background:'The Control Tower needs to manage the implementation rather than only store process documents.',options:'Document/task repository; lifecycle-based transformation governance.',recommendation:'Govern work through As-Is, pain points, requirements, To-Be, fit/gap, build, testing and readiness.',decisionOutcome:'Approved: As-Is → Pain Points → Requirements → To-Be → Fit/Gap → Build → Test → Readiness is the core transformation lifecycle.',rationale:'Provides traceability from the current business problem to the implemented D365 solution and test evidence.',owner:'Business Owner',status:'Decided',decisionDate:'2026-08-14',escalateToSteering:false}
];
function ensureV2State(){for(const k of ['painPoints','opportunities','requirements','decisions','fitGap','raid','dataObjects','integrations','reports','controls','escalations'])vreg(k);const d=vreg('decisions');for(const seed of PROJECT_DECISION_SEEDS){if(!d.some(x=>x.id===seed.id))d.push(clone(seed))}}

const PROCESS_GATES=[
  ['processOwnerConfirmed','Process owner confirmed'],['smeConfirmed','SMEs confirmed'],['systemsReviewed','Systems reviewed'],['painPointsReviewed','Pain points reviewed'],['controlsReviewed','Controls reviewed'],['reportsReviewed','Reports reviewed'],['interfacesReviewed','Interfaces reviewed'],['bpoValidated','BPO validated']
];
function processGateScore(p){if(!p)return 0;if(p.status==='Approved As-Is')return 100;const g=p.gates||{};let n=PROCESS_GATES.filter(([k])=>!!g[k]).length;let score=15+85*n/PROCESS_GATES.length;if(p.status==='SME Validated')score=Math.max(score,80);if(p.status==='BPO Review')score=Math.max(score,60);return clampPct(score)}
function avg(xs){return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0}
function reqsFor(stream){return (data().requirements||[]).filter(x=>x.stream===stream)}
function dataScore(x){let s=0;if(x.owner)s+=15;if(x.sourceSystem)s+=10;if(['Mapped','Validated','Complete'].includes(x.mappingStatus))s+=25;if(['Complete','Validated'].includes(x.cleansingStatus))s+=20;if(['Tested','Validated','Complete'].includes(x.migrationStatus))s+=20;if(x.cutoverReady===true||x.cutoverReady==='Yes')s+=10;return s}
function streamMaturity(id){const d=data(),s=allStreams().find(x=>x.id===id),ps=d.subprocesses?.[id]||[],rs=reqsFor(id),people=(d.people||[]).filter(p=>p.stream===id),objs=(d.dataObjects||[]).filter(x=>x.stream===id||x.stream==='ALL');const asis=avg(ps.map(processGateScore)),ownership=Math.min(100,(s?.bpo&&!String(s.bpo).toUpperCase().includes('TBD')?50:0)+(people.some(p=>String(p.role).includes('SME'))?50:0)),requirements=rs.length?100*rs.filter(r=>['Approved','Ready for Design','Closed'].includes(r.status)).length/rs.length:0,tobe=rs.length?100*rs.filter(r=>r.toBeDesign||r.toBeProcess).length/rs.length:0,fitgap=rs.length?100*rs.filter(r=>r.fitGap&&r.fitGap!=='TBD').length/rs.length:0,dataM=objs.length?avg(objs.map(dataScore)):0,testing=rs.length?100*rs.filter(r=>r.testStatus==='Passed').length/rs.length:0;return {asis:clampPct(asis),ownership:clampPct(ownership),requirements:clampPct(requirements),tobe:clampPct(tobe),fitgap:clampPct(fitgap),data:clampPct(dataM),testing:clampPct(testing),readiness:clampPct(avg([asis,ownership,requirements,tobe,fitgap,dataM,testing]))}}
function maturityCell(v){const c=v>=80?'m-green':v>=50?'m-yellow':v>0?'m-red':'m-gray';return `<td class="maturity-cell ${c}"><b>${fmtPct(v)}</b></td>`}
function programHealth(){const d=data(),openTasks=(d.tasks||[]).filter(t=>!['Closed','Approved'].includes(t.status)),overdue=openTasks.filter(t=>(t.forecastDue||t.due)&&String(t.forecastDue||t.due)<today()),highOverdue=overdue.filter(t=>t.priority==='High'),raid=(d.raid||[]).filter(x=>!['Closed','Resolved'].includes(x.status)),critical=raid.filter(x=>x.severity==='Critical'),high=raid.filter(x=>['Critical','High'].includes(x.severity)),decisions=(d.decisions||[]).filter(x=>!['Closed','Decided'].includes(x.status)),overDec=decisions.filter(x=>x.due&&x.due<today()),esc=(d.escalations||[]).filter(x=>!['Closed','Resolved'].includes(x.status));let overall='Green';if(critical.length||highOverdue.length>=3)overall='Red';else if(high.length||highOverdue.length||overDec.length||esc.length)overall='Amber';const schedule=highOverdue.length?'Amber':overdue.length?'Amber':'Green';const scopeOpen=decisions.filter(x=>x.category==='Scope');const scope=scopeOpen.length?'Amber':'Stable';return {overall,schedule,scope,overdue:overdue.length,highOverdue:highOverdue.length,critical:critical.length,high:high.length,overDec:overDec.length,esc:esc.length}}
function attentionItems(){const d=data(),out=[];(d.tasks||[]).filter(t=>!['Closed','Approved'].includes(t.status)&&(t.forecastDue||t.due)&&String(t.forecastDue||t.due)<today()).sort((a,b)=>String(a.forecastDue||a.due).localeCompare(String(b.forecastDue||b.due))).slice(0,3).forEach(t=>out.push({type:'Overdue task',title:t.title,meta:`${t.stream} · ${t.owner} · due ${t.forecastDue||t.due}`,tone:'red'}));(d.raid||[]).filter(x=>!['Closed','Resolved'].includes(x.status)&&['Critical','High'].includes(x.severity)).slice(0,3).forEach(x=>out.push({type:`${x.type||'Risk'} · ${x.severity}`,title:x.title||x.description,meta:`${x.stream||'Program'} · ${x.owner||'Unassigned'}`,tone:x.severity==='Critical'?'red':'yellow'}));(d.decisions||[]).filter(x=>!['Closed','Decided'].includes(x.status)&&x.due&&x.due<=today()).slice(0,3).forEach(x=>out.push({type:'Decision due',title:x.title,meta:`${x.stream||'Program'} · ${x.owner}`,tone:'yellow'}));(d.escalations||[]).filter(x=>!['Closed','Resolved'].includes(x.status)).slice(0,3).forEach(x=>out.push({type:'Steering escalation',title:x.title,meta:`${x.owner||'Unassigned'} · ${x.committeeDate||'date TBD'}`,tone:'red'}));const s2p=(d.valueStreams||[]).find(x=>x.id==='S2P');if(s2p?.bpo&&String(s2p.bpo).toUpperCase().includes('TBD'))out.push({type:'Ownership gap',title:'Source to Pay BPO not yet assigned',meta:'S2P · mobilization risk',tone:'yellow'});return out.slice(0,7)}
function taskProgress(t){if(Number.isFinite(+t.progress))return clampPct(t.progress);return ({'Closed':100,'Approved':100,'BPO Review':80,'Ready for Review':70,'In Progress':50,'Waiting':35,'Not Started':0}[t.status]??0)}
function taskOutlook(min,max){return (data().tasks||[]).filter(t=>!['Closed','Approved'].includes(t.status)).filter(t=>{const n=daysFromToday(t.forecastDue||t.due);return n!==null&&n>=min&&n<=max}).sort((a,b)=>String(a.forecastDue||a.due).localeCompare(String(b.forecastDue||b.due)))}
