(()=>{
const D=window.FI_DATA;
const app=document.getElementById('app');
const sideNav=document.getElementById('sideNav');
const viewTitle=document.getElementById('viewTitle');
const viewSubtitle=document.getElementById('viewSubtitle');
const drawer=document.getElementById('drawer');
const backdrop=document.getElementById('backdrop');
const drawerTabs=document.getElementById('drawerTabs');
const drawerBody=document.getElementById('drawerBody');
const sourceModal=document.getElementById('sourceModal');
const state={view:'pulse',entity:null,tab:'summary',evidence:new Set(['fact','mgmt','est','derived','inference'])};
const titles={pulse:['Industry Pulse','Professional operating weather map: status, evidence, confidence and business implication'],demand:['Demand','End-market momentum with drillable evidence'],cost:['Price & Cost','Input-cost, pricing-power and margin-pressure signals'],customers:['Customers','Click any customer for a CFO-grade financial and strategic dossier'],peers:['Peers / Competitors','Financial benchmarking, strategy, profitability and competitive read-through'],suppliers:['Suppliers','Supplier financial health, pricing power, capacity and sourcing risk'],trade:['Imports & Trade','Country-of-origin, tariff, imports and localization intelligence'],capacity:['Capacity Map','Verified capacity and footprint intelligence; no invented plant coordinates'],trend:['Trend Lab','Persistent market, cost, FX and demand series with source metadata']};
const ev=t=>`<span class="evidence ${t}">${t==='mgmt'?'MGMT':t.toUpperCase()}</span>`;
const srcBtn=id=>id&&D.sources[id]?`<button class="source-link" data-source="${id}">${id}</button>`:'';
const evidenceWrap=(html,type,src)=>`<div class="evidence-line" data-evidence="${type}">${ev(type)}${html}${srcBtn(src)}</div>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderMarket(){document.getElementById('marketStrip').innerHTML=D.market.map(x=>`<div class="ticker"><label>${esc(x.label)}</label><strong>${esc(x.value)}</strong><small class="${x.dir||'flat'}">${esc(x.change)}</small></div>`).join('');}
function renderNav(){sideNav.innerHTML=D.nav.map(([id,icon,label])=>`<button class="nav-btn ${state.view===id?'active':''}" data-view="${id}"><span class="nav-icon">${icon}</span>${label}</button>`).join('');sideNav.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;renderNav();renderView();}));}
function spark(n,seed){let out='<div class="spark">';for(let i=0;i<n;i++){const h=20+((i*13+seed*17)%75);out+=`<i style="height:${h}%"></i>`;}return out+'</div>';}
function renderPulse(){
 const weather=D.weather.map((w,i)=>`<div class="weather-item" data-evidence="${w.type}"><div class="wi-top"><strong>${esc(w.name)}</strong><span class="status signal ${w.tone}">${esc(w.status)}</span></div><div class="coverage"><span>${w.score}/100</span><div class="coverage-track"><i style="width:${w.score}%"></i></div>${ev(w.type)} ${srcBtn(w.source)}</div><p>${esc(w.note)}</p>${spark(12,i+2)}</div>`).join('');
 const risks=[['Trade / tariff policy','High','Rules can change landed economics rapidly.','US_TARIFF'],['Steel producer pricing power','High','Lower imports and high utilization support supplier leverage.','NUCOR_Q2'],['Customer inventory quality','Medium','Separate consumption from pre-buying/dealer stock.','STLA_PRES'],['Private-company visibility','Medium','Do not invent financials where disclosure is limited.','INFERENCE']];
 const opp=[['Distributor fastener growth','High','Fastenal and Supply Technologies show positive relevant demand.','FAST_ER'],['AI / electrical infrastructure','High','Supply Technologies and industrial channels report strong growth.','PKOH_CALL'],['Aerospace','Medium-High','LISI and Supply Technologies commentary is constructive.','LISI_H1'],['Productivity / automation','Medium','Peers are expanding margins through productivity.','BULTEN_Q2']];
 app.innerHTML=`<div class="dashboard-grid"><section class="card span-8"><div class="weather-head"><div class="outlook"><span class="eyebrow">Overall industry outlook</span><div class="score">CAUTIOUSLY POSITIVE</div><div class="label">Demand improving · input costs firm · trade uncertainty high</div><p>This is a composite analytical view, not a reported industry statistic. Each component below exposes its evidence class and source.</p></div><div class="metric-row"><div class="metric"><label>Demand</label><strong>72</strong><small>Improving</small></div><div class="metric"><label>Cost pressure</label><strong>68</strong><small>Elevated</small></div><div class="metric"><label>Trade risk</label><strong>79</strong><small>High</small></div><div class="metric"><label>Coverage</label><strong>${Object.keys(D.entities).length}</strong><small>entity dossiers</small></div></div></div><div class="weather-grid">${weather}</div></section><section class="card span-4"><h2>Decision balance</h2><div class="list"><h3>Top risks</h3>${risks.map(r=>`<div class="signal-row" data-evidence="inference"><div><strong>${r[0]}</strong><p>${r[2]}</p></div><div><span class="chip negative">${r[1]}</span><br>${ev('inference')} ${srcBtn(r[3])}</div></div>`).join('')}<h3 style="margin-top:10px">Top opportunities</h3>${opp.map(r=>`<div class="signal-row" data-evidence="inference"><div><strong>${r[0]}</strong><p>${r[2]}</p></div><div><span class="chip positive">${r[1]}</span><br>${ev('inference')} ${srcBtn(r[3])}</div></div>`).join('')}</div></section><section class="card span-12"><h2>How to read this dashboard</h2><div class="metric-row"><div class="metric"><label>FACT</label><strong>Reported</strong><small>Direct filing, company release or official statistic.</small></div><div class="metric"><label>MGMT</label><strong>Commentary</strong><small>Management statement, guidance or prepared remarks.</small></div><div class="metric"><label>DERIVED</label><strong>Calculated</strong><small>Formula using source-backed reported inputs.</small></div><div class="metric"><label>INFERENCE</label><strong>Analysis</strong><small>Implication for Infasco; never substitutes for internal exposure data.</small></div></div></section></div>`;
}
function renderDemand(){app.innerHTML=`<div class="dashboard-grid"><section class="card span-7"><h2>End-market demand heatmap</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>End market</th><th>Current</th><th>3M trend</th><th>Outlook</th><th>Evidence</th><th>Source</th></tr></thead><tbody>${D.demand.map(r=>`<tr data-evidence="${r[5]}"><td>${r[0]}</td><td class="signal ${r[1]==='Strong'||r[1]==='Improving'?'good':'warn'}">${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${ev(r[5])}</td><td>${srcBtn(r[6])}</td></tr>`).join('')}</tbody></table></div></section><section class="card span-5"><h2>Demand interpretation</h2><div class="matrix"><div class="cell head">Signal</div><div class="cell head">Now</div><div class="cell head">Trend</div><div class="cell head">Confidence</div>${D.demand.slice(0,7).map(r=>`<div class="cell">${r[0]}</div><div class="cell ${r[1]==='Strong'?'green':r[1]==='Mixed'?'amber':'blue'}">${r[1]}</div><div class="cell">${r[2]}</div><div class="cell">${r[5]==='fact'?'High':'Med-High'}</div>`).join('')}</div><div class="privacy-note" style="margin-top:10px">External demand indicators are context. Forecast decisions should be reconciled to internal order intake, backlog, releases and customer inventory before translating to Infasco tons.</div></section><section class="card span-12"><h2>Entity demand drill-down</h2><div class="entity-grid">${['fastenal','supplytech','gm','stellantis','ford','applied'].map(id=>entityCard(id)).join('')}</div></section></div>`;bindEntityCards();}
function renderCost(){app.innerHTML=`<div class="dashboard-grid"><section class="card span-8"><h2>Input cost snapshot</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Input</th><th>Status</th><th>Exposure</th><th>Risk</th><th>Read-through</th><th>Evidence</th><th>Source</th></tr></thead><tbody>${D.costInputs.map(r=>`<tr data-evidence="${r[5]}"><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td>${ev(r[5])}</td><td>${srcBtn(r[6])}</td></tr>`).join('')}</tbody></table></div></section><section class="card span-4"><h2>Margin-pressure framework</h2><div class="outlook"><span class="eyebrow">Derived decision framework</span><div class="score" style="color:var(--amber)">ELEVATED</div><p>Selling-price recovery must be assessed against steel/wire rod, conversion labour, plating metals, freight, FX and financing. The dashboard separates reported benchmarks from the derived margin-pressure view.</p>${ev('derived')} ${srcBtn('DERIVED')}</div><div class="list" style="margin-top:10px"><div class="signal-row"><div><strong>Steel</strong><p>Producer leverage remains high.</p></div><span class="chip cautious">High</span></div><div class="signal-row"><div><strong>FX</strong><p>USD/CAD and USD/TWD are persistent Trend Lab series.</p></div><span class="chip neutral">Variable</span></div><div class="signal-row"><div><strong>Freight</strong><p>Benchmark improving versus peaks, geopolitical risk persists.</p></div><span class="chip cautious">Volatile</span></div></div></section><section class="card span-12"><h2>Supplier drill-down</h2><div class="entity-grid">${D.entityGroups.suppliers.map(id=>entityCard(id)).join('')}</div></section></div>`;bindEntityCards();}
function entityCard(id){const e=D.entities[id];const k=e.kpis.slice(0,3);return `<article class="entity-card" data-entity="${id}"><div class="entity-top"><div><h3>${esc(e.name)}</h3><div class="meta">${esc(e.role)} · ${esc(e.latest)}</div></div><span class="chip ${assessmentClass(e.assessment)}">${esc(e.assessment)}</span></div><div class="kpis">${k.map(x=>`<div class="mini"><label>${esc(x[0])}</label><strong>${esc(x[1])}</strong></div>`).join('')}</div><div class="takeaway">${esc(e.takeaway)}</div><div class="coverage" style="margin-top:9px"><span>Coverage ${e.coverage}%</span><div class="coverage-track"><i style="width:${e.coverage}%"></i></div><span>${esc(e.confidence)}</span></div></article>`;}
function assessmentClass(a){const s=(a||'').toLowerCase();return s.includes('positive')||s.includes('strong')?'positive':s.includes('negative')?'negative':s.includes('caut')||s.includes('limit')?'cautious':'neutral';}
function renderEntities(group){const ids=D.entityGroups[group];const label=group==='customers'?'Customer':group==='peers'?'Peer / competitor':'Supplier';app.innerHTML=`<div class="privacy-note"><strong>Public intelligence layer.</strong> Internal Infasco sales, tons, contribution margin, contract terms, part numbers and customer exposure are intentionally excluded from this public route. Each dossier provides public financial depth, sourcing evidence, management commentary and an Infasco relevance lens without inventing internal exposure.</div><div class="entity-grid">${ids.map(id=>entityCard(id)).join('')}</div><section class="card" style="margin-top:10px"><h2>${label} coverage standard</h2><div class="metric-row"><div class="metric"><label>Financial statements</label><strong>IS / BS / CF</strong><small>Where public disclosure allows.</small></div><div class="metric"><label>Operating analysis</label><strong>Ratios + segments</strong><small>Company-specific metrics, not generic scores.</small></div><div class="metric"><label>Executive lenses</label><strong>CFO / Sales / President</strong><small>Separate implications and questions.</small></div><div class="metric"><label>Auditability</label><strong>Source-level</strong><small>Every material item exposes provenance and evidence class.</small></div></div></section>`;bindEntityCards();}
function renderTrade(){app.innerHTML=`<div class="dashboard-grid"><section class="card span-7"><h2>Trade & localization risk register</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Lane / Region</th><th>Condition</th><th>Risk</th><th>Management use</th><th>Evidence</th><th>Source</th></tr></thead><tbody>${D.trade.map(r=>`<tr data-evidence="${r[4]}"><td>${r[0]}</td><td>${r[1]}</td><td><span class="chip ${r[2]==='High'?'negative':'cautious'}">${r[2]}</span></td><td>${r[3]}</td><td>${ev(r[4])}</td><td>${srcBtn(r[5])}</td></tr>`).join('')}</tbody></table></div></section><section class="card span-5"><h2>Landed-cost logic</h2><div class="list">${['Supplier base price','FX translation','Ocean / inland freight','MFN / Section 232 / AD-CVD','Origin qualification','Inventory carry','Customer recovery'].map((x,i)=>`<div class="signal-row"><div><strong>${i+1}. ${x}</strong><p>${i===4?'Must be verified by product/program; no blanket assumption.':'Separate driver in scenario model.'}</p></div><span class="chip neutral">${i<5?'Input':'Derived'}</span></div>`).join('')}</div><div class="privacy-note" style="margin-top:10px">No tariff exposure should be inferred from company nationality alone. HTS classification, actual origin, supplying plant, contractual importer-of-record terms and recovery clauses determine economics.</div></section><section class="card span-12"><h2>Trade-sensitive entities</h2><div class="entity-grid">${['supplytech','gm','stellantis','sanshing','nucor','arcelor'].map(id=>entityCard(id)).join('')}</div></section></div>`;bindEntityCards();}
function renderCapacity(){const rows=[['Nucor','North America steel capacity','High utilization / domestic leverage','NUCOR_Q2'],['Bulten','Global precision + C-parts footprint','Portfolio being refocused','BULTEN_Q2'],['LISI','Aerospace / automotive industrial sites','Capacity and productivity investments','LISI_H1'],['Supply Technologies','New North American distribution centre','Q3 opening / 2027 margin benefits','PKOH_CALL'],['Trifast','Global engineered fastener footprint','Revenue-quality / margin focus','TRIFAST_FY']];app.innerHTML=`<div class="dashboard-grid"><section class="card span-7"><h2>Verified footprint & capacity watch</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Entity</th><th>Footprint / Capacity topic</th><th>Current signal</th><th>Source</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${srcBtn(r[3])}</td></tr>`).join('')}</tbody></table></div></section><section class="card span-5"><h2>Map integrity control</h2><div class="outlook"><span class="eyebrow">No fabricated geography</span><div class="score" style="color:var(--blue)">SOURCE FIRST</div><p>Plant pins and capacity bubbles will only appear when a verified public location and capacity source is loaded. This build intentionally avoids approximating plant coordinates or capacity values.</p>${ev('fact')} ${srcBtn('INFERENCE')}</div></section><section class="card span-12"><h2>Capacity-linked dossiers</h2><div class="entity-grid">${['supplytech','bulten','lisi','trifast','nucor','arcelor'].map(id=>entityCard(id)).join('')}</div></section></div>`;bindEntityCards();}
function renderTrend(){app.innerHTML=`<div class="dashboard-grid"><section class="card span-8"><h2>Persistent Trend Lab series</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Series</th><th>Current status</th><th>Direction</th><th>Use</th><th>Evidence</th><th>Source</th></tr></thead><tbody>${D.trendSeries.map(r=>`<tr data-evidence="${r.type}"><td>${r.name}</td><td>${r.value}</td><td>${r.trend}</td><td>${r.note}</td><td>${ev(r.type)}</td><td>${srcBtn(r.source)}</td></tr>`).join('')}</tbody></table></div></section><section class="card span-4"><h2>Comparison controls</h2><div class="metric-row" style="grid-template-columns:repeat(2,1fr)"><div class="metric"><label>Periods</label><strong>1Y / 3Y / 5Y</strong><small>Plus user-defined dates</small></div><div class="metric"><label>Display</label><strong>Actual / % / 100</strong><small>Normalized-to-100 comparison</small></div><div class="metric"><label>FX</label><strong>USD/CAD + USD/TWD</strong><small>Persistent quote convention</small></div><div class="metric"><label>Provenance</label><strong>Date + source</strong><small>Every point retains metadata</small></div></div><div class="privacy-note" style="margin-top:10px">USD/TWD convention: Taiwan dollars per US$1. A rising USD/TWD means a weaker TWD. Semiconductor/component sourcing impact is only inferred when supplier contract currency and pass-through are known.</div></section><section class="card span-12"><h2>Normalized comparison mock view</h2><div class="chartbox">${[['Fastener demand',88],['Wire rod',74],['USD/CAD',55],['USD/TWD',52],['Copper',81],['Freight',63]].map((x,i)=>`<div class="chartbar" style="height:${x[1]}%;background:var(--${i===0?'blue':i===1?'amber':i===4?'green':'cyan'})"><span>${x[1]}</span><label>${x[0]}</label></div>`).join('')}</div><p style="color:var(--muted);font-size:10px;margin-top:20px">Illustrative normalized layout only. Live production Trend Lab should populate verified historical time series and never infer missing observations.</p></section></div>`;}
function renderView(){const [t,s]=titles[state.view];viewTitle.textContent=t;viewSubtitle.textContent=s;if(state.view==='pulse')renderPulse();else if(state.view==='demand')renderDemand();else if(state.view==='cost')renderCost();else if(['customers','peers','suppliers'].includes(state.view))renderEntities(state.view);else if(state.view==='trade')renderTrade();else if(state.view==='capacity')renderCapacity();else renderTrend();bindSourceButtons();applyEvidenceFilters();}
function bindEntityCards(){document.querySelectorAll('[data-entity]').forEach(el=>el.addEventListener('click',()=>openEntity(el.dataset.entity)));}
function openEntity(id){state.entity=id;state.tab='summary';const e=D.entities[id];document.getElementById('drawerType').textContent=e.role;document.getElementById('drawerTitle').textContent=e.name;document.getElementById('drawerSubtitle').textContent=`${e.latest} · Published ${e.published} · ${e.assessment} · Confidence ${e.confidence} · Coverage ${e.coverage}%`;renderDrawerTabs();renderDrawerTab();drawer.classList.add('open');backdrop.classList.add('open');drawer.setAttribute('aria-hidden','false');}
const tabs=[['summary','Executive Summary'],['financials','Financial Statements'],['ratios','Ratios & Trends'],['segments','Segments / End Markets'],['commentary','Management Commentary'],['cfo','CFO Lens'],['sales','Sales Director Lens'],['president','President Lens'],['sources','Sources / Audit Trail']];
function renderDrawerTabs(){drawerTabs.innerHTML=tabs.map(([id,label])=>`<button data-tab="${id}" class="${state.tab===id?'active':''}">${label}</button>`).join('');drawerTabs.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{state.tab=b.dataset.tab;renderDrawerTabs();renderDrawerTab();}));}
function kpiGrid(e){return `<div class="metric-row">${e.kpis.map(k=>`<div class="metric" data-evidence="${k[3]}"><label>${esc(k[0])}</label><strong>${esc(k[1])}</strong><small>${esc(k[2])}</small><div style="margin-top:5px">${ev(k[3])} ${srcBtn(k[4])}</div></div>`).join('')}</div>`;}
function renderDrawerTab(){const e=D.entities[state.entity];if(state.tab==='summary'){drawerBody.innerHTML=`<div class="dossier-hero"><div class="dossier-summary"><div class="entity-top"><div><span class="eyebrow">Executive conclusion</span><h3>${esc(e.name)}</h3></div><span class="chip ${assessmentClass(e.assessment)}">${esc(e.assessment)}</span></div><p>${esc(e.takeaway)}</p><div class="evidence-line">${ev('inference')} ${srcBtn('INFERENCE')}</div></div><div class="dossier-summary"><span class="eyebrow">Coverage control</span><div class="coverage"><strong>${e.coverage}%</strong><div class="coverage-track" style="width:160px"><i style="width:${e.coverage}%"></i></div></div><p><strong>Freshness:</strong> ${esc(e.freshness)}<br><strong>Direction:</strong> ${esc(e.direction)}<br><strong>Confidence:</strong> ${esc(e.confidence)}</p></div></div><div class="tab-section" style="margin-top:10px"><h3>Headline KPIs</h3>${kpiGrid(e)}</div><div class="tab-section"><h3>Three executive lenses</h3><div class="lens-grid"><div class="lens"><h3>CFO</h3><p>${esc(e.lenses.cfo)}</p></div><div class="lens"><h3>Sales Director</h3><p>${esc(e.lenses.sales)}</p></div><div class="lens"><h3>President</h3><p>${esc(e.lenses.president)}</p></div></div></div><div class="tab-section"><h3>High-value follow-up questions</h3><ol class="questions">${e.questions.map(q=>`<li>${esc(q)}</li>`).join('')}</ol></div>`;}
 else if(state.tab==='financials')drawerBody.innerHTML=renderFinancials(e);
 else if(state.tab==='ratios')drawerBody.innerHTML=renderSimpleTable('Ratios & analytical trends',['Metric','Current / Value','Interpretation / Comparator','Evidence','Source'],e.ratios);
 else if(state.tab==='segments')drawerBody.innerHTML=renderSimpleTable('Segments / end markets',['Segment / Market','Scale / Signal','Read-through','Evidence','Source'],e.segments);
 else if(state.tab==='commentary')drawerBody.innerHTML=renderCommentary(e);
 else if(['cfo','sales','president'].includes(state.tab))drawerBody.innerHTML=renderLens(e,state.tab);
 else drawerBody.innerHTML=renderEntitySources(e);
 bindSourceButtons();applyEvidenceFilters();}
function renderFinancials(e){const sections=[['Income Statement',e.financials.income],['Balance Sheet',e.financials.balance],['Cash Flow',e.financials.cash]];return `<div class="privacy-note">Financial statement values use the company's disclosed reporting basis and native currency. Cross-company comparability is not assumed. Blank sections mean the public-source model has not yet ingested reliable detail—not zero.</div>${sections.map(([name,rows])=>`<section class="tab-section"><h3>${name}</h3>${rows&&rows.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Metric</th><th>Current</th><th>Comparator / Context</th><th>Change</th><th>Evidence</th><th>Source</th></tr></thead><tbody>${rows.map(r=>`<tr data-evidence="${r[4]}"><td>${esc(r[0])}</td><td>${esc(r[1])}</td><td>${esc(r[2])}</td><td>${esc(r[3])}</td><td>${ev(r[4])}</td><td>${srcBtn(r[5])}</td></tr>`).join('')}</tbody></table></div>`:`<div class="empty">No reliable public-source ${name.toLowerCase()} detail has been ingested for this entity. The dashboard will not estimate missing financial statement lines.</div>`}</section>`).join('')}`;}
function renderSimpleTable(title,heads,rows){if(!rows||!rows.length)return `<div class="empty">No reliable public-source detail is available for this section. Nothing has been fabricated.</div>`;return `<section class="tab-section"><h3>${title}</h3><div class="table-wrap"><table class="data-table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr data-evidence="${r[3]}"><td>${esc(r[0])}</td><td>${esc(r[1])}</td><td>${esc(r[2])}</td><td>${ev(r[3])}</td><td>${srcBtn(r[4])}</td></tr>`).join('')}</tbody></table></div></section>`;}
function renderCommentary(e){if(!e.commentary.length)return `<div class="empty">No management commentary has been loaded. Private-company or limited-disclosure coverage remains explicit.</div>`;return `<div class="privacy-note">Management statements are shown separately from reported historical facts. Forward-looking statements are not treated as facts.</div>${e.commentary.map(c=>`<div class="quote" data-evidence="${c[2]}"><strong>${esc(c[0])}</strong><p>${esc(c[1])}</p>${ev(c[2])} ${srcBtn(c[3])}</div>`).join('')}`;}
function renderLens(e,lens){const label=lens==='cfo'?'CFO':lens==='sales'?'Sales Director':'President';return `<div class="dossier-summary"><span class="eyebrow">${label} lens</span><h3>${esc(e.name)}</h3><p>${esc(e.lenses[lens])}</p>${ev('inference')} ${srcBtn('INFERENCE')}</div><div class="tab-section" style="margin-top:10px"><h3>Questions to pressure-test the conclusion</h3><ol class="questions">${e.questions.map(q=>`<li>${esc(q)}</li>`).join('')}</ol></div><div class="privacy-note">Any quantified Infasco-specific exposure must come from authenticated internal sales, tons, margin, contract, payment-term and capacity data. This public layer will identify the exact missing input rather than guess.</div>`;}
function renderEntitySources(e){return `<div class="privacy-note">Source hierarchy: audited/regulatory filing → official earnings release/presentation → management call → official statistics → external estimate → dashboard-derived calculation → Infasco analytical inference.</div>${e.sources.map(id=>sourceCard(id)).join('')}`;}
function sourceCard(id){const s=D.sources[id];if(!s)return'';return `<article class="source-card"><div class="entity-top"><div><h3>${esc(id)} · ${esc(s.title)}</h3><p>${esc(s.publisher)} · ${esc(s.date)} · ${esc(s.period)} · ${esc(s.kind)}</p></div>${ev(s.class)}</div><p><strong>Used for:</strong> ${esc(s.usedFor)}</p><p><strong>Control note:</strong> ${esc(s.notes)}</p>${s.url?`<a href="${s.url}" target="_blank" rel="noopener">Open primary source ↗</a>`:'<span class="chip neutral">No external URL asserted</span>'}</article>`;}
function bindSourceButtons(){document.querySelectorAll('[data-source]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();openSourceModal(b.dataset.source);}));}
function openSourceModal(focus){sourceModal.classList.add('open');sourceModal.setAttribute('aria-hidden','false');document.getElementById('sourceSearch').value=focus||'';renderSourceRegister();}
function closeSourceModal(){sourceModal.classList.remove('open');sourceModal.setAttribute('aria-hidden','true');}
function renderSourceRegister(){const q=document.getElementById('sourceSearch').value.toLowerCase().trim();const type=document.getElementById('sourceTypeFilter').value;const entries=Object.entries(D.sources).filter(([id,s])=>{const hay=[id,s.title,s.publisher,s.period,s.kind,s.usedFor,s.notes].join(' ').toLowerCase();return (!q||hay.includes(q))&&(type==='all'||s.class===type);});document.getElementById('sourceModalBody').innerHTML=`<div class="source-register">${entries.length?entries.map(([id])=>sourceCard(id)).join(''):'<div class="empty">No matching sources.</div>'}</div>`;}
function applyEvidenceFilters(){document.querySelectorAll('[data-evidence]').forEach(el=>{el.style.display=state.evidence.has(el.dataset.evidence)?'':'none';});}
function exportSources(){const rows=[['ID','Title','Publisher','Date','Period','Evidence class','Kind','Used for','URL','Notes']];Object.entries(D.sources).forEach(([id,s])=>rows.push([id,s.title,s.publisher,s.date,s.period,s.class,s.kind,s.usedFor,s.url,s.notes]));const csv=rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`fastener-intelligence-source-register-${D.asOf}.csv`;a.click();URL.revokeObjectURL(a.href);}
document.getElementById('drawerClose').addEventListener('click',()=>{drawer.classList.remove('open');backdrop.classList.remove('open');});backdrop.addEventListener('click',()=>document.getElementById('drawerClose').click());document.getElementById('sourceRegisterBtn').addEventListener('click',()=>openSourceModal(''));document.getElementById('sourceModalClose').addEventListener('click',closeSourceModal);sourceModal.addEventListener('click',e=>{if(e.target===sourceModal)closeSourceModal();});document.getElementById('sourceSearch').addEventListener('input',renderSourceRegister);document.getElementById('sourceTypeFilter').addEventListener('change',renderSourceRegister);document.getElementById('exportSourcesBtn').addEventListener('click',exportSources);document.querySelectorAll('.evidenceFilter').forEach(c=>c.addEventListener('change',()=>{c.checked?state.evidence.add(c.value):state.evidence.delete(c.value);applyEvidenceFilters();}));
renderMarket();renderNav();renderView();
})();