(()=>{
const D=window.FI_DATA;
if(!D)return;
const app=document.getElementById('app');
const sideNav=document.getElementById('sideNav');
const viewTitle=document.getElementById('viewTitle');
const viewSubtitle=document.getElementById('viewSubtitle');
const drawer=document.getElementById('drawer');
const backdrop=document.getElementById('backdrop');
const drawerTabs=document.getElementById('drawerTabs');
const drawerBody=document.getElementById('drawerBody');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ev=t=>`<span class="evidence ${t}">${t==='mgmt'?'MGMT':String(t).toUpperCase()}</span>`;
const src=(id,label)=>D.sources[id]?`<button class="fi-source-button" data-enh-source="${id}">${label||id}</button>`:'';
const ent=(id,label)=>D.entities[id]?`<button class="fi-source-button" data-enh-entity="${id}">${label||D.entities[id].name}</button>`:'';
function tone(score){return score>=70?'#50c98b':score>=55?'#e7b451':'#ef6d74'}
function sourceOpen(id){const modal=document.getElementById('sourceModal');const input=document.getElementById('sourceSearch');if(!modal||!input)return;modal.classList.add('open');modal.setAttribute('aria-hidden','false');input.value=id;input.dispatchEvent(new Event('input',{bubbles:true}));}
function bindEnhanced(root=document){root.querySelectorAll('[data-enh-source]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',e=>{e.stopPropagation();sourceOpen(b.dataset.enhSource);});});root.querySelectorAll('[data-enh-entity]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',e=>{e.stopPropagation();openEntity(b.dataset.enhEntity);});});root.querySelectorAll('[data-enh-view]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',()=>openView(b.dataset.enhView));});}
function markEvidence(){document.querySelectorAll('.evidenceFilter').forEach(c=>{const t=c.value;document.querySelectorAll(`[data-evidence="${t}"]`).forEach(el=>el.style.display=c.checked?'':'none');});}
function miniSource(type,id){return `<div class="fi-mini-source">${ev(type)}${src(id)}</div>`}
function renderPulse(){
const weather=D.weather.slice(0,10).map(w=>`<div class="fi-weather-node fi-drill" data-evidence="${w.type}" data-enh-view="${w.name==='Demand'?'demand':w.name.includes('Pricing')||w.name.includes('Steel')||w.name.includes('Freight')||w.name.includes('Labour')?'cost':w.name.includes('Import')||w.name.includes('Trade')?'trade':'pulse'}"><div class="fi-ring" style="--score:${w.score};--ring:${tone(w.score)}"><b>${w.score}</b></div><div><h3>${esc(w.name)}</h3><div class="state" style="color:${tone(w.score)}">${esc(w.status)}</div><p>${esc(w.note)}</p>${miniSource(w.type,w.source)}</div></div>`).join('');
const ranked=[
['Tariff / origin uncertainty',92,'High','Now','Changes landed cost, sourcing and customer recovery economics.','US_TARIFF','trade'],
['Steel producer pricing power',86,'High','Now','High domestic utilization and lower import pressure support supplier leverage.','NUCOR_Q2','cost'],
['Distributor fastener growth',82,'High','Now','Fastenal and Supply Technologies show stronger relevant demand.','FAST_ER','customers'],
['Customer inventory quality',76,'Med-High','30–90d','Distinguish real consumption from pre-buying, dealer inventory and restocking.','STLA_PRES','customers'],
['AI / electrical infrastructure',74,'High','1–3y','Strong growth signal from Supply Technologies and industrial channels.','PKOH_CALL','demand']
];
const rankHtml=ranked.map((r,i)=>`<div class="fi-rank-row fi-drill" data-evidence="inference" data-enh-view="${r[6]}"><div class="fi-rank-num">${i+1}</div><div><strong>${r[0]}</strong><p>${r[4]}</p>${miniSource('inference',r[5])}</div><div class="fi-score-pill">${r[1]}/100</div><div class="fi-score-pill">${r[3]}</div></div>`).join('');
const demandRows=D.demand.slice(0,7).map(r=>{const cls=r[1]==='Strong'||r[1]==='Improving'?'good':r[1]==='Mixed'||r[1]==='Volatile'?'warn':'blue';return `<div class="fi-hcell name fi-drill" data-enh-view="demand">${r[0]}</div><div class="fi-hcell ${cls}" data-evidence="${r[5]}">${r[1]}</div><div class="fi-hcell ${r[2].includes('↑')?'good':'blue'}">${r[2]}</div><div class="fi-hcell ${r[3]==='Positive'?'good':r[3]==='Cautious'?'warn':'blue'}">${r[3]}</div><div class="fi-hcell">${src(r[6],'source')}</div>`}).join('');
const costBars=[['Fastener price',64,'price'],['Wire rod',81,'cost'],['Scrap',70,'cost'],['Zinc',74,'cost'],['Tungsten',86,'risk'],['Freight',58,'price'],['FX',55,'price']].map(x=>`<div class="fi-bar-col ${x[2]}" style="--h:${x[1]}%"><span>${x[1]}</span><label>${x[0]}</label></div>`).join('');
const bubbles=[
['Fastenal',68,72,44,'good','fastenal'],['Supply Tech',64,66,42,'good','supplytech'],['GM',53,63,36,'good','gm'],['Stellantis',40,58,38,'warn','stellantis'],['Ford',46,55,34,'warn','ford'],['Grainger',61,68,32,'good','grainger']
].map(b=>`<div class="fi-bubble ${b[4]}" style="--x:${b[1]}%;--y:${b[2]}%;--size:${b[3]}px" data-enh-entity="${b[5]}" title="Click for dossier">${b[0]}</div>`).join('');
const comp=[
['Fastenal','Customer','Strong','High','Low','fastenal'],['Supply Tech','Customer / mfr','Improving','High','Med','supplytech'],['San Shing','Peer / supplier','Cautious','High','High','sanshing'],['Bulten','Peer','Margin up','Med','High','bulten'],['LISI','Peer','Strong','High','High','lisi'],['Trifast','Peer','Margin up','High','Med','trifast']
];
const compRows=comp.map(r=>`<div class="company" data-enh-entity="${r[5]}">${r[0]}</div><div>${r[1]}</div><div class="score-blue">${r[2]}</div><div class="score-good">${r[3]}</div><div class="score-warn">${r[4]}</div><div>${D.entities[r[5]]?.coverage||'—'}%</div>`).join('');
const actions=[
['Complete trade exposure matrix','Map customer × HTS × origin × supplying plant × recovery terms.','Critical','US_TARIFF','trade'],
['Challenge supplier price increases','Separate steel spread, scrap, freight, FX and tariff components.','High','NUCOR_Q2','cost'],
['Exploit distributor growth pockets','Match Fastenal / Supply Tech growth to programs and externally sourced content.','High','FAST_ER','customers'],
['Monitor inventory cycle','Watch dealer/distributor inventory versus sales to detect destocking risk.','High','STLA_PRES','customers']
].map(a=>`<div class="fi-action-card" data-enh-view="${a[4]}"><div class="top"><strong>${a[0]}</strong><span class="chip ${a[2]==='Critical'?'negative':'cautious'}">${a[2]}</span></div><p>${a[1]}</p>${miniSource('inference',a[3])}</div>`).join('');
const news=[
['2026-08','Supply Technologies','North American distribution centre / automation investment','PKOH_CALL','supplytech'],
['2026-07','Bulten','Portfolio refocus toward precision manufacturing and C-parts','BULTEN_Q2','bulten'],
['2026-07','LISI','Aerospace growth and productivity investment','LISI_H1','lisi'],
['2026-07','Nucor','High mill utilization and higher realized pricing','NUCOR_Q2','nucor'],
['2026-07','Trifast','Revenue-quality strategy and margin improvement','TRIFAST_FY','trifast']
].map(n=>`<div class="fi-event"><time>${n[0]}</time><strong>${ent(n[4],n[1])}</strong><p>${n[2]}</p>${miniSource('fact',n[3])}</div>`).join('');
const sourceCount=Object.keys(D.sources).length, entityCount=Object.keys(D.entities).length;
app.innerHTML=`<div class="fi-command-center">
<section class="card fi-hero"><div class="fi-hero-main"><div class="fi-hero-title"><span class="fi-pulse-badge">Industry command center</span><h2>North American Fastener Intelligence</h2></div><p class="fi-hero-summary">Demand, margin pressure, customer cycle, trade, competitive capacity and strategic actions in one source-traceable operating view. Click any visual, company or source to drill from L1 → L2 → entity dossier → primary evidence.</p><div class="fi-score-strip"><div class="fi-score-tile"><label>Industry outlook</label><strong style="color:var(--green)">Cautiously positive</strong><small>Derived composite</small></div><div class="fi-score-tile"><label>Demand</label><strong>72/100</strong><small>Improving</small></div><div class="fi-score-tile"><label>Cost pressure</label><strong>68/100</strong><small>Elevated</small></div><div class="fi-score-tile"><label>Trade risk</label><strong>79/100</strong><small>High</small></div><div class="fi-score-tile"><label>Coverage</label><strong>${entityCount}</strong><small>entity dossiers</small></div></div>${miniSource('inference','INFERENCE')}</div><div class="fi-hero-side"><div><span class="eyebrow">Management read-through</span><div class="fi-decision"><div><strong>Volume</strong><p>Selective growth across distribution, aerospace, industrial and infrastructure.</p></div><span class="chip positive">Positive</span></div><div class="fi-decision"><div><strong>Margin</strong><p>Steel and tariff economics remain the largest structural pressure points.</p></div><span class="chip cautious">Caution</span></div><div class="fi-decision"><div><strong>Working capital</strong><p>Inventory quality matters more than headline shipment growth.</p></div><span class="chip cautious">Watch</span></div><div class="fi-decision"><div><strong>Strategy</strong><p>Localization and supply reliability remain differentiators.</p></div><span class="chip positive">Opportunity</span></div></div></div></section>
<section class="card fi-weather"><div class="fi-visual-title"><h2>Fastener Industry Weather Map</h2><span class="fi-tag">Professional composite · source drill-down</span></div><div class="fi-weather-grid">${weather}</div><div class="fi-legend" style="margin-top:8px"><span><i class="fi-legend-dot good"></i> favourable / improving</span><span><i class="fi-legend-dot warn"></i> elevated / mixed</span><span><i class="fi-legend-dot bad"></i> adverse</span><span>${ev('inference')} composite scoring; component sources remain visible</span></div></section>
<section class="card fi-rank"><div class="fi-visual-title"><h2>Ranked Risks & Opportunities</h2><span class="fi-tag">Magnitude × probability × exposure × urgency</span></div>${rankHtml}</section>
<section class="card fi-demand"><div class="fi-visual-title"><h2>End-Market Demand Heatmap</h2><button class="fi-source-button" data-enh-view="demand">Open Demand L2 →</button></div><div class="fi-heatmap"><div class="fi-hcell head">End market</div><div class="fi-hcell head">Current</div><div class="fi-hcell head">Trend</div><div class="fi-hcell head">Outlook</div><div class="fi-hcell head">Evidence</div>${demandRows}</div><div class="fi-matrix-note">External demand signals must be reconciled to internal backlog, releases and customer inventory before translating into Infasco tons.</div></section>
<section class="card fi-cost"><div class="fi-visual-title"><h2>Price–Cost Pressure</h2><button class="fi-source-button" data-enh-view="cost">Open Price & Cost L2 →</button></div><div class="fi-bar-chart">${costBars}</div><div class="fi-spread-note"><div><label>Selling-price recovery</label><strong>Improving selectively</strong>${miniSource('mgmt','FAST_CALL')}</div><div><label>Raw-material pressure</label><strong>Elevated</strong>${miniSource('inference','NUCOR_Q2')}</div><div><label>Margin regime</label><strong>Recovery discipline required</strong>${miniSource('inference','INFERENCE')}</div></div><div class="fi-matrix-note">Bars are a normalized current-pressure view, not fabricated historical price indices. Trend Lab remains the place for verified time series.</div></section>
<section class="card fi-cycle"><div class="fi-visual-title"><h2>Customer / Distributor Cycle</h2><span class="fi-tag">Derived positioning</span></div><div class="fi-quadrant"><span class="fi-q-label tl">lean inventory / growth</span><span class="fi-q-label tr">growth + inventory build</span><span class="fi-q-label bl">weak demand / destocking</span><span class="fi-q-label br">inventory risk</span>${bubbles}<div class="fi-axis-x">Demand / revenue momentum →</div><div class="fi-axis-y">Inventory quality / cycle →</div></div><p class="fi-matrix-note">Positions combine non-uniform public indicators and are therefore ${ev('derived')} analytical, not directly comparable accounting ratios. Click a bubble for the full dossier.</p></section>
<section class="card fi-import"><div class="fi-visual-title"><h2>Imports, Localization & Landed Cost</h2><button class="fi-source-button" data-enh-view="trade">Open Trade L2 →</button></div><div class="fi-stack"><span style="width:30%;background:#2e6b97">Taiwan</span><span style="width:22%;background:#356f55">China</span><span style="width:15%;background:#806328">Mexico</span><span style="width:12%;background:#594b8c">Korea</span><span style="width:21%;background:#3d4d5b">Other</span></div><div class="fi-waterfall"><div class="fi-water total" style="--h:52%"><small>Supplier</small><label>Base</label></div><div class="fi-water add" style="--h:25%"><small>FX</small><label>FX</label></div><div class="fi-water add" style="--h:32%"><small>Ocean</small><label>Freight</label></div><div class="fi-water risk" style="--h:72%"><small>Policy</small><label>Duty / AD-CVD</label></div><div class="fi-water add" style="--h:22%"><small>Carry</small><label>Inventory</label></div><div class="fi-water total" style="--h:88%"><small>Delivered</small><label>Landed</label></div></div><div class="fi-matrix-note">Import-share bar is a visual category framework, not asserted current market-share data. Actual trade shares must come from the U.S./Canadian customs series. The landed-cost waterfall is schematic because HTS, origin and importer-of-record terms vary by program. ${src('US_TRADE','Trade data')} · ${src('US_TARIFF','Tariff rules')} · ${src('TWD','USD/TWD')}</div></section>
<section class="card fi-competition"><div class="fi-visual-title"><h2>Competitive Position & Capacity</h2><button class="fi-source-button" data-enh-view="capacity">Open Capacity L2 →</button></div><div class="fi-comp-grid"><div class="head">Entity</div><div class="head">Role</div><div class="head">Direction</div><div class="head">Financial strength</div><div class="head">Direct fastener relevance</div><div class="head">Coverage</div>${compRows}</div><div class="fi-region-map"><div class="fi-region"><h3>Canada</h3><span class="fi-pin" data-enh-entity="arcelor">ArcelorMittal</span><span class="fi-pin" data-enh-entity="gm">GM programs</span></div><div class="fi-region"><h3>United States</h3><span class="fi-pin" data-enh-entity="nucor">Nucor</span><span class="fi-pin" data-enh-entity="supplytech">Supply Technologies</span><span class="fi-pin" data-enh-entity="fastenal">Fastenal</span><span class="fi-pin" data-enh-entity="ford">Ford</span><span class="fi-pin" data-enh-entity="stellantis">Stellantis</span></div><div class="fi-region"><h3>Global / import sources</h3><span class="fi-pin" data-enh-entity="sanshing">San Shing / Taiwan</span><span class="fi-pin" data-enh-entity="bulten">Bulten</span><span class="fi-pin" data-enh-entity="lisi">LISI</span><span class="fi-pin" data-enh-entity="trifast">Trifast</span></div></div><div class="fi-map-note">Schematic strategic footprint only; not a geospatial plant map. Exact plant pins will only be added where verified location/capacity data is loaded.</div></section>
<section class="card fi-actions"><div class="fi-visual-title"><h2>Management Action Queue</h2><span class="fi-tag">Decision-oriented</span></div>${actions}</section>
<section class="card fi-news"><div class="fi-visual-title"><h2>M&A, Capacity & Strategic Actions Timeline</h2><button class="fi-source-button" data-enh-view="news">Open M&A & News →</button></div><div class="fi-timeline">${news}</div></section>
<section class="card fi-sources"><div class="fi-visual-title"><h2>Data Integrity & Coverage</h2><button class="fi-source-button" data-enh-source="INFERENCE">Open source register →</button></div><div class="fi-source-summary"><div><label>Source records</label><strong>${sourceCount}</strong><small>filings, company releases, government, market benchmarks</small></div><div><label>Entity dossiers</label><strong>${entityCount}</strong><small>customers, peers, suppliers</small></div><div><label>Evidence classes</label><strong>5</strong><small>fact · management · estimate · derived · inference</small></div><div><label>Private-company rule</label><strong>0 invented</strong><small>financials remain blank when disclosure is unavailable</small></div></div><div class="privacy-note" style="margin-top:8px">Public site keeps confidential Infasco tons, sales, margins, part codes, payment terms and contracts out of the route. Those belong in an authenticated internal layer.</div></section>
</div>`;
bindEnhanced(app);markEvidence();
}
function prependL2(kind){if(app.querySelector('.fi-augmentation'))return;let html='';
if(kind==='Demand')html=`<section class="card fi-augmentation"><div class="fi-section-head"><div><h2>Demand cockpit</h2><p>Macro signal → end market → company evidence → entity dossier</p></div><span class="fi-tag">L2 drill-down</span></div><div class="fi-l2-banner"><div class="fi-l2-stat"><label>Strongest</label><strong>Aerospace</strong><small>Management + peer evidence</small></div><div class="fi-l2-stat"><label>Accelerating</label><strong>AI / electrical</strong><small>Supply Technologies</small></div><div class="fi-l2-stat"><label>Mixed</label><strong>Automotive</strong><small>OEM-specific</small></div><div class="fi-l2-stat"><label>Watch</label><strong>Inventory cycle</strong><small>Dealer / distributor</small></div></div></section>`;
if(kind==='Price & Cost')html=`<section class="card fi-augmentation"><div class="fi-section-head"><div><h2>Margin pressure bridge</h2><p>External selling-price recovery versus raw material, conversion, freight and FX</p></div><span class="fi-tag">L2 drill-down</span></div><div class="fi-l2-banner"><div class="fi-l2-stat"><label>Steel</label><strong>Elevated</strong><small>${src('NUCOR_Q2')}</small></div><div class="fi-l2-stat"><label>Plating metals</label><strong>Firm</strong><small>${src('LME')}</small></div><div class="fi-l2-stat"><label>Freight</label><strong>Volatile</strong><small>${src('DREWRY')}</small></div><div class="fi-l2-stat"><label>FX</label><strong>USD/CAD + USD/TWD</strong><small>${src('BOC')} ${src('TWD')}</small></div></div></section>`;
if(kind==='Imports & Trade')html=`<section class="card fi-augmentation"><div class="fi-section-head"><div><h2>Trade decision framework</h2><p>Never infer exposure from company nationality: classify HTS × origin × supplying plant × importer-of-record × recovery clause</p></div><span class="fi-tag">L2 drill-down</span></div><div class="fi-l2-banner"><div class="fi-l2-stat"><label>Canada → U.S.</label><strong>High sensitivity</strong><small>Tariff / origin</small></div><div class="fi-l2-stat"><label>Taiwan</label><strong>FX + duty</strong><small>USD/TWD persistent</small></div><div class="fi-l2-stat"><label>China</label><strong>Trade-case risk</strong><small>AD/CVD + tariff</small></div><div class="fi-l2-stat"><label>USMCA</label><strong>Qualification</strong><small>Program-specific</small></div></div></section>`;
if(kind==='Capacity Map')html=`<section class="card fi-augmentation"><div class="fi-section-head"><div><h2>Capacity intelligence hierarchy</h2><p>Verified announcement → location → capacity / investment → timing → competitive implication</p></div><span class="fi-tag">L2 drill-down</span></div><div class="fi-region-map"><div class="fi-region"><h3>Distribution</h3><span class="fi-pin" data-enh-entity="supplytech">Supply Technologies centre</span></div><div class="fi-region"><h3>Fastener peers</h3><span class="fi-pin" data-enh-entity="bulten">Bulten</span><span class="fi-pin" data-enh-entity="lisi">LISI</span><span class="fi-pin" data-enh-entity="trifast">Trifast</span></div><div class="fi-region"><h3>Steel upstream</h3><span class="fi-pin" data-enh-entity="nucor">Nucor</span><span class="fi-pin" data-enh-entity="arcelor">ArcelorMittal</span></div></div></section>`;
if(kind==='Trend Lab')html=`<section class="card fi-augmentation"><div class="fi-section-head"><div><h2>Trend Lab control model</h2><p>Actual · YoY · % change · rebased 100 · 1Y / 3Y / 5Y · custom period · source/date metadata</p></div><span class="fi-tag">Persistent time series</span></div><div class="fi-l2-banner"><div class="fi-l2-stat"><label>FX</label><strong>USD/CAD</strong><small>Bank of Canada</small></div><div class="fi-l2-stat"><label>Taiwan FX</label><strong>USD/TWD</strong><small>Taiwan central bank</small></div><div class="fi-l2-stat"><label>Metals</label><strong>Cu / Zn / steel</strong><small>official benchmarks</small></div><div class="fi-l2-stat"><label>Demand</label><strong>PMI / DSR / end markets</strong><small>source-specific</small></div></div></section>`;
if(html){app.insertAdjacentHTML('afterbegin',html);bindEnhanced(app);}
}
function ensureNewsNav(){if(sideNav.querySelector('[data-enh-custom="news"]'))return;const b=document.createElement('button');b.className='nav-btn';b.dataset.enhCustom='news';b.innerHTML='<span class="nav-icon">◈</span>M&A & News';b.addEventListener('click',()=>openView('news'));const trend=sideNav.querySelector('[data-view="trend"]');trend?sideNav.insertBefore(b,trend):sideNav.appendChild(b);}
function openView(v){if(v==='news'){sideNav.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));const n=sideNav.querySelector('[data-enh-custom="news"]');if(n)n.classList.add('active');viewTitle.textContent='M&A & News';viewSubtitle.textContent='Strategic actions, acquisitions, restructurings, capacity changes and verified industry developments';renderNews();return;}const btn=sideNav.querySelector(`[data-view="${v}"]`);if(btn)btn.click();}
function renderNews(){const items=[
['Supply Technologies','New North American distribution centre, automation and information-systems investment.','Strategic capacity / service','PKOH_CALL','supplytech'],
['Bulten','Portfolio refocus toward precision manufacturing and full-service C-parts.','Restructuring','BULTEN_Q2','bulten'],
['LISI','Aerospace capacity and productivity investments with automotive share gains.','Capacity / share','LISI_H1','lisi'],
['Trifast','Revenue-quality and structural-efficiency program driving margin improvement.','Turnaround','TRIFAST_FY','trifast'],
['Nucor','High mill utilization and stronger pricing support domestic producer leverage.','Capacity / pricing','NUCOR_Q2','nucor']
];
app.innerHTML=`<div class="fi-news-view"><section class="card span-8"><div class="fi-section-head"><div><h2>Strategic action feed</h2><p>Only developments with sales, cost, sourcing, capacity, working-capital or competitive implications</p></div><span class="fi-tag">Source-backed</span></div>${items.map(i=>`<div class="fi-news-card"><div class="entity-top"><div><h3>${ent(i[4],i[0])}</h3><p>${i[1]}</p></div><span class="chip neutral">${i[2]}</span></div>${miniSource('fact',i[3])}</div>`).join('')}</section><section class="card span-4"><h2>Event scoring</h2>${[['Magnitude','Business impact'],['Probability','Likelihood of outcome'],['Infasco exposure','Customer / cost / sourcing relevance'],['Time sensitivity','When management must act']].map((x,i)=>`<div class="fi-action-card"><strong>${x[0]}</strong><p>${x[1]}</p><div class="fi-kpi-mini"><span>${[85,72,78,81][i]}/100 example framework</span></div></div>`).join('')}<div class="privacy-note">Scores are ${ev('derived')} prioritization tools. They do not replace source facts or quantified internal exposure.</div></section><section class="card span-12"><h2>Entity drill-down</h2><div class="entity-grid">${['supplytech','bulten','lisi','trifast','nucor','sanshing'].map(id=>entityCard(id)).join('')}</div></section></div>`;bindEnhanced(app);}
function entityCard(id){const e=D.entities[id];if(!e)return'';const k=e.kpis.slice(0,3);return `<article class="entity-card" data-enh-entity="${id}"><div class="entity-top"><div><h3>${esc(e.name)}</h3><div class="meta">${esc(e.role)} · ${esc(e.latest)}</div></div><span class="chip ${String(e.assessment).toLowerCase().includes('positive')||String(e.assessment).toLowerCase().includes('strong')?'positive':'cautious'}">${esc(e.assessment)}</span></div><div class="kpis">${k.map(x=>`<div class="mini"><label>${esc(x[0])}</label><strong>${esc(x[1])}</strong></div>`).join('')}</div><div class="takeaway">${esc(e.takeaway)}</div><div class="coverage" style="margin-top:8px"><span>Coverage ${e.coverage}%</span><div class="coverage-track"><i style="width:${e.coverage}%"></i></div><span>${esc(e.confidence)}</span></div></article>`}
function openEntity(id){const e=D.entities[id];if(!e)return;document.getElementById('drawerType').textContent=e.role;document.getElementById('drawerTitle').textContent=e.name;document.getElementById('drawerSubtitle').textContent=`${e.latest} · Published ${e.published} · ${e.assessment} · Confidence ${e.confidence} · Coverage ${e.coverage}%`;const tabs=[['summary','Executive Summary'],['financials','Financial Statements'],['ratios','Ratios & Trends'],['segments','Segments / End Markets'],['commentary','Management Commentary'],['cfo','CFO Lens'],['sales','Sales Director Lens'],['president','President Lens'],['sources','Sources / Audit Trail']];drawerTabs.innerHTML=tabs.map((t,i)=>`<button data-enh-tab="${t[0]}" class="${i===0?'active':''}">${t[1]}</button>`).join('');const render=t=>{drawerTabs.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.enhTab===t));drawerBody.innerHTML=renderEntityTab(e,t);bindEnhanced(drawerBody)};drawerTabs.querySelectorAll('[data-enh-tab]').forEach(b=>b.addEventListener('click',()=>render(b.dataset.enhTab)));render('summary');drawer.classList.add('open');backdrop.classList.add('open');drawer.setAttribute('aria-hidden','false');}
function renderEntityTab(e,t){if(t==='summary')return `<div class="fi-entity-summary"><span class="eyebrow">Executive conclusion</span><h3>${esc(e.name)}</h3><p>${esc(e.takeaway)}</p>${miniSource('inference','INFERENCE')}</div><div class="fi-dossier-grid">${e.kpis.map(k=>`<div class="fi-dossier-box" data-evidence="${k[3]}"><label>${esc(k[0])}</label><strong>${esc(k[1])}</strong><small>${esc(k[2])}</small><div class="fi-e-row">${ev(k[3])}${src(k[4])}</div></div>`).join('')}</div><section class="tab-section" style="margin-top:10px"><h3>Executive lenses</h3><div class="lens-grid"><div class="lens"><h3>CFO</h3><p>${esc(e.lenses.cfo)}</p></div><div class="lens"><h3>Sales Director</h3><p>${esc(e.lenses.sales)}</p></div><div class="lens"><h3>President</h3><p>${esc(e.lenses.president)}</p></div></div></section><section class="tab-section"><h3>High-value questions</h3><ol class="questions">${e.questions.map(q=>`<li>${esc(q)}</li>`).join('')}</ol></section>`;
if(t==='financials')return `<p class="fi-tabs-note">Company native currency and reporting basis. Blank sections mean reliable public detail has not been ingested—not zero.</p>${finTable('Income Statement',e.financials.income)}${finTable('Balance Sheet',e.financials.balance)}${finTable('Cash Flow',e.financials.cash)}`;
if(t==='ratios')return simpleTable('Ratios & Trends',e.ratios);
if(t==='segments')return simpleTable('Segments / End Markets',e.segments);
if(t==='commentary')return `<p class="fi-tabs-note">Management claims and forward-looking statements remain separate from reported historical facts.</p>${(e.commentary||[]).length?e.commentary.map(c=>`<div class="quote" data-evidence="${c[2]}"><strong>${esc(c[0])}</strong><p>${esc(c[1])}</p>${ev(c[2])} ${src(c[3])}</div>`).join(''):'<div class="empty">No management commentary loaded.</div>'}`;
if(['cfo','sales','president'].includes(t)){const label=t==='cfo'?'CFO':t==='sales'?'Sales Director':'President';return `<div class="fi-entity-summary"><span class="eyebrow">${label} lens</span><h3>${esc(e.name)}</h3><p>${esc(e.lenses[t])}</p>${miniSource('inference','INFERENCE')}</div><ol class="questions">${e.questions.map(q=>`<li>${esc(q)}</li>`).join('')}</ol><div class="privacy-note">Any quantified Infasco-specific exposure requires authenticated internal sales, tons, margin, contract, payment-term and capacity data. Public dossiers do not guess.</div>`}
return `<div class="privacy-note">Source hierarchy: audited/regulatory filing → official earnings release/presentation → management call → official statistics → external estimate → derived calculation → analytical inference.</div>${(e.sources||[]).map(id=>sourceCard(id)).join('')}`}
function finTable(title,rows){if(!rows||!rows.length)return `<section class="tab-section"><h3>${title}</h3><div class="empty">No reliable public-source detail ingested.</div></section>`;return `<section class="tab-section"><h3>${title}</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Metric</th><th>Current</th><th>Comparator</th><th>Change</th><th>Evidence</th><th>Source</th></tr></thead><tbody>${rows.map(r=>`<tr data-evidence="${r[4]}"><td>${esc(r[0])}</td><td>${esc(r[1])}</td><td>${esc(r[2])}</td><td>${esc(r[3])}</td><td>${ev(r[4])}</td><td>${src(r[5])}</td></tr>`).join('')}</tbody></table></div></section>`}
function simpleTable(title,rows){if(!rows||!rows.length)return '<div class="empty">No reliable public-source detail ingested.</div>';return `<section class="tab-section"><h3>${title}</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Metric / Segment</th><th>Value / Signal</th><th>Interpretation</th><th>Evidence</th><th>Source</th></tr></thead><tbody>${rows.map(r=>`<tr data-evidence="${r[3]}"><td>${esc(r[0])}</td><td>${esc(r[1])}</td><td>${esc(r[2])}</td><td>${ev(r[3])}</td><td>${src(r[4])}</td></tr>`).join('')}</tbody></table></div></section>`}
function sourceCard(id){const s=D.sources[id];if(!s)return'';return `<article class="source-card"><div class="entity-top"><div><h3>${esc(id)} · ${esc(s.title)}</h3><p>${esc(s.publisher)} · ${esc(s.date)} · ${esc(s.period)} · ${esc(s.kind)}</p></div>${ev(s.class)}</div><p><strong>Used for:</strong> ${esc(s.usedFor)}</p><p><strong>Control note:</strong> ${esc(s.notes)}</p>${s.url?`<a href="${s.url}" target="_blank" rel="noopener">Open primary source ↗</a>`:'<span class="chip neutral">No external URL asserted</span>'}</article>`}
function enhanceCurrent(){ensureNewsNav();const t=viewTitle.textContent.trim();if(t==='Industry Pulse'&&!app.querySelector('.fi-command-center'))renderPulse();else if(['Demand','Price & Cost','Imports & Trade','Capacity Map','Trend Lab'].includes(t))prependL2(t);bindEnhanced(document);markEvidence();}
const obs=new MutationObserver(()=>queueMicrotask(enhanceCurrent));obs.observe(app,{childList:true,subtree:false});obs.observe(sideNav,{childList:true});obs.observe(viewTitle,{childList:true,characterData:true,subtree:true});document.querySelectorAll('.evidenceFilter').forEach(c=>c.addEventListener('change',()=>queueMicrotask(markEvidence)));
setTimeout(enhanceCurrent,0);
})();