(()=>{
const app=document.getElementById('app');if(!app)return;
const NS='http://www.w3.org/2000/svg';
const peerSites=[
  {company:'MNP Corporation',site:'Headquarters / fastener manufacturing',place:'Utica, MI',lat:42.63,lon:-83.03,kind:'Direct fastener peer',detail:'Heading, thread rolling, heat treat, steel processing and distribution',src:'https://www.mnp.com/facilities/'},
  {company:'MNP Corporation',site:'Plant II',place:'Madison Heights, MI',lat:42.49,lon:-83.11,kind:'Direct fastener peer',detail:'Heading and threading',src:'https://www.mnp.com/facilities/'},
  {company:'MNP Precision Parts',site:'Precision Parts',place:'Rockford, IL',lat:42.27,lon:-89.09,kind:'Direct fastener peer',detail:'Heading, threading and secondary machining',src:'https://www.mnp.com/facilities/'},
  {company:'MNP Heat Treat',site:'Heat Treat',place:'Redford, MI',lat:42.37,lon:-83.30,kind:'Direct fastener peer',detail:'Fastener and metal-part heat treatment',src:'https://www.mnp.com/facilities/'},
  {company:'Nucor Fastener',site:'Fastener division',place:'St. Joe, IN',lat:41.31,lon:-84.90,kind:'Direct fastener peer',detail:'Steel fastener manufacturing',src:'https://nucor.com/news/?article=nucor-fastener-to-expand-with-acquisition-of-coil-processing-facility-122560'},
  {company:'Nucor Fastener',site:'Shelbyville operation',place:'Shelbyville, IN',lat:39.52,lon:-85.78,kind:'Direct fastener peer',detail:'Coil processing, wire drawing and bolt-making capability',src:'https://nucor.com/news/?article=nucor-fastener-to-expand-with-acquisition-of-coil-processing-facility-122560'},
  {company:'Nucor Steel Nebraska',site:'Engineered Bar Mill',place:'Norfolk, NE',lat:42.03,lon:-97.42,kind:'Upstream CHQ / SBQ capacity',detail:'Engineered bar and coil serving automotive, heavy truck and heavy equipment',src:'https://nucor.com/news/?article=nucor-to-upgrade-engineered-bar-mill-in-nebraska-122730'},
  {company:'Nucor Steel South Carolina',site:'Bar mill',place:'Darlington, SC',lat:34.30,lon:-79.87,kind:'Upstream CHQ / wire rod capacity',detail:'Merchant bar, wire rod, SBQ and cold-headed-quality bar',src:'https://investors.nucor.com/news/news-details/2019/Nucor-Announces-Capital-Investment-at-South-Carolina-Bar-Mill-05-20-2019/default.aspx'},
  {company:'ArcelorMittal Long Products Canada',site:'Contrecoeur integrated long-products complex',place:'Contrecoeur, QC',lat:45.86,lon:-73.24,kind:'Upstream wire rod / bar capacity',detail:'DRI, steelmaking, bar mill and wire-rod mill; cold-heading rod supplied to fastener applications',src:'https://northamerica.arcelormittal.com/our-operations/arcelormittal-long-products-canada'},
  {company:'ArcelorMittal Long Products Canada',site:'Longueuil Bar Mill',place:'Longueuil, QC',lat:45.54,lon:-73.47,kind:'Upstream bar capacity',detail:'Bar mill in the Québec long-products network',src:'https://long-canada.arcelormittal.com/en/our-locations/'},
  {company:'ArcelorMittal Mexico',site:'Lázaro Cárdenas long-products complex',place:'Lázaro Cárdenas, Michoacán',lat:17.96,lon:-102.20,kind:'Upstream wire rod / billet capacity',detail:'Rod, wire rod, billet and slab production',src:'https://northamerica.arcelormittal.com/our-operations/arcelormittal-mexico'}
];
function mode(){const b=[...app.querySelectorAll('.v13-cap-controls button')].find(x=>x.classList.contains('active'));const t=(b?.textContent||'').toLowerCase();return t.includes('customer')?'CUSTOMER':t.includes('peer manufacturing')?'MFG':t.includes('peer distribution')?'DIST':'ALL'}
function tooltip(){return document.getElementById('fiGeoTooltip')}
function move(e){const t=tooltip();if(!t)return;t.style.left=Math.min(window.innerWidth-300,e.clientX+14)+'px';t.style.top=Math.min(window.innerHeight-160,e.clientY+14)+'px'}
function show(e,s){const t=tooltip();if(!t)return;t.innerHTML=`<strong>${s.company}</strong><span>${s.site}</span><span>${s.place}</span><span>${s.kind}</span><span>${s.detail}</span><small>Click marker to open public source</small>`;t.classList.add('show');move(e)}
function hide(){tooltip()?.classList.remove('show')}
function markerClass(s){return s.kind.startsWith('Direct')?'v17-direct-peer':'v17-upstream-peer'}
function addPeers(svg){const geo=window.FI_GEO_MAP;if(!geo||!svg.querySelector('.v14-country-layer'))return;svg.querySelectorAll('.v17-peer-layer').forEach(x=>x.remove());if(!['ALL','MFG'].includes(mode()))return;const layer=document.createElementNS(NS,'g');layer.setAttribute('class','v17-peer-layer');for(const s of peerSites){const [x,y]=geo.naXY(s.lat,s.lon);if(x<0||x>1000||y<0||y>560)continue;const g=document.createElementNS(NS,'g');g.setAttribute('class','v17-peer-point');const c=document.createElementNS(NS,'circle');c.setAttribute('cx',x.toFixed(1));c.setAttribute('cy',y.toFixed(1));c.setAttribute('r',s.kind.startsWith('Direct')?'8':'7');c.setAttribute('class',markerClass(s));const title=document.createElementNS(NS,'title');title.textContent=`${s.company} — ${s.site} | ${s.place} | ${s.kind} | ${s.detail}`;c.appendChild(title);c.addEventListener('mouseenter',e=>show(e,s));c.addEventListener('mousemove',move);c.addEventListener('mouseleave',hide);c.addEventListener('click',()=>window.open(s.src,'_blank','noopener'));g.appendChild(c);layer.appendChild(g)}svg.appendChild(layer)}
function addLegend(){const cap=app.querySelector('.v13-capacity');if(!cap)return;let l=cap.querySelector('.v17-peer-legend');if(!l){l=document.createElement('div');l.className='v17-peer-legend';l.innerHTML='<span><i class="direct"></i> Direct fastener manufacturing peer</span><span><i class="upstream"></i> Upstream CHQ / SBQ / wire-rod manufacturing capacity</span>';const anchor=cap.querySelector('.v16-map-legend')||cap.querySelector('.v15-customer-note');anchor?.insertAdjacentElement('afterend',l)}l.style.display=['ALL','MFG'].includes(mode())?'flex':'none'}
function addCoverageNote(){const cap=app.querySelector('.v13-capacity');if(!cap||cap.querySelector('.v17-peer-note'))return;const n=document.createElement('div');n.className='v17-peer-note';n.innerHTML='<strong>Manufacturing interpretation:</strong> MNP and Nucor Fastener are direct fastener-manufacturing peers. Nucor Engineered Bar and ArcelorMittal Long Products are shown because CHQ/SBQ/wire-rod capacity directly affects North American fastener localization, input availability and competitive landed-cost economics.';const l=cap.querySelector('.v17-peer-legend')||cap.querySelector('.v16-map-legend');l?.insertAdjacentElement('afterend',n)}
function enhance(){window.FI_GEO_MAP?.schedule();setTimeout(()=>{app.querySelectorAll('svg.v13-na').forEach(addPeers);addLegend();addCoverageNote()},100)}
let timer;function schedule(){clearTimeout(timer);timer=setTimeout(enhance,55)}
new MutationObserver(schedule).observe(app,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});
app.addEventListener('click',e=>{if(e.target.closest('.v13-cap-controls button'))setTimeout(schedule,120)},true);
schedule();
})();