(()=>{
const app=document.getElementById('app'),title=document.getElementById('viewTitle');
const TD=window.FI_TREND_DATA||{series:{}};
if(!app||!title)return;
const toDate=s=>new Date(s+'T00:00:00Z');
const monthEnd=m=>{const [y,mo]=m.split('-').map(Number);return new Date(Date.UTC(y,mo,0));};
function series(id){return TD.series?.[id]||null}
function obsAt(id,end){const s=series(id);if(!s?.data?.length)return null;let best=null;for(const p of s.data){const d=toDate(p[0]);if(d<=end)best=p;else break}return best}
function janObs(id,y){const s=series(id);if(!s?.data?.length)return null;const js=new Date(Date.UTC(+y,0,1)),je=new Date(Date.UTC(+y,0,31));let prior=null,first=null;for(const p of s.data){const d=toDate(p[0]);if(d<js)prior=p;else if(d<=je&&!first)first=p;else if(d>je)break}return first||prior}
function janIndex(id,month){const y=month.slice(0,4),b=janObs(id,y),c=obsAt(id,monthEnd(month));if(!b||!c||!b[1])return null;return {index:c[1]/b[1]*100,base:b,cur:c}}
function drewryTie(month){const y=month.slice(0,4),w=series('DREWRY_WCI'),p=series('PCU4831114831115');if(!w?.data?.length||!p?.data?.length)return null;const yr=w.data.filter(x=>x[0].startsWith(y));if(!yr.length)return null;const first=yr[0],cur=obsAt('DREWRY_WCI',monthEnd(month));if(!cur||toDate(cur[0])<toDate(first[0]))return null;const pBase=janObs('PCU4831114831115',y),pBridge=obsAt('PCU4831114831115',toDate(first[0]));if(!pBase||!pBridge)return null;const ppiToBridge=pBridge[1]/pBase[1]*100;const wciOwn=cur[1]/first[1]*100;const chained=ppiToBridge*wciOwn/100;return {first,cur,pBase,pBridge,ppiToBridge,wciOwn,chained}}
function fmt(v,d=1){return Number.isFinite(v)?v.toFixed(d):'—'}
function current(){return {month:document.getElementById('v6Month')?.value||'2026-08',route:document.getElementById('v6Route')?.value||'IMPORT_TWD',freight:document.getElementById('v6Freight')?.value||'COMPOSITE'}}
function freightSubtotal(month,route,mode){const truck=janIndex('WPU3012',month),oceanPpi=janIndex('PCU4831114831115',month),dw=drewryTie(month);const ocean=dw?.chained??oceanPpi?.index??100;const truckIdx=truck?.index??100;let idx=100;if(mode==='COMPOSITE'){const ow=route==='MFG_CA'?0:8,tw=route==='MFG_CA'?5:4;idx=(ow+tw)?(ow*ocean+tw*truckIdx)/(ow+tw):100}else if(mode==='TRUCK')idx=truckIdx;else if(mode==='OCEAN')idx=ocean;return {truck,oceanPpi,dw,ocean,truckIdx,index:idx}}
function openTrend(){const c=current(),y=c.month.slice(0,4),end=monthEnd(c.month).toISOString().slice(0,10);let s={};try{s=JSON.parse(localStorage.getItem('fiTrendState')||'{}')}catch(e){}s.selected=['WPU3012','PCU4831114831115','DREWRY_WCI'];s.range='CUSTOM';s.customStart=y+'-01-01';s.customEnd=end;s.transform='Rebased 100';s.frequency='Auto';localStorage.setItem('fiTrendState',JSON.stringify(s));document.querySelector('[data-view="trend"]')?.click()}
function panel(){const c=current(),r=freightSubtotal(c.month,c.route,c.freight),dw=r.dw;const janYear=c.month.slice(0,4);const wciNote=dw?`Drewry starts ${dw.first[0]} at $${Number(dw.first[1]).toLocaleString()}/40ft, so it cannot independently have a January ${janYear} observation.`:'No Drewry observation is available by the selected month; ocean uses deep-sea freight PPI only.';return `<section class="v7-tie-panel"><div class="v7-head"><div><h2>Freight Index Tie-Out</h2><p>Reconciles the source indices to the landed-cost freight bridge. This is the missing link between Trend Lab and the waterfall.</p></div><button id="v7OpenTrend">Open same Jan window in Trend Lab</button></div><div class="v7-tie-grid"><div><span>Truck PPI</span><strong>${fmt(r.truckIdx)}</strong><small>Jan ${janYear}=100 · ${r.truck?.base?.[0]||'—'} → ${r.truck?.cur?.[0]||'—'}</small></div><div><span>Deep-sea freight PPI</span><strong>${fmt(r.oceanPpi?.index)}</strong><small>Jan ${janYear}=100 · direct source index</small></div><div><span>Drewry WCI</span><strong>${fmt(dw?.wciOwn)}</strong><small>${dw?`${dw.first[0]}=100 → ${dw.cur[0]}`:'Not yet available'}</small></div><div class="derived"><span>Chain-linked ocean index</span><strong>${fmt(r.ocean)}</strong><small>${dw?`${fmt(dw.ppiToBridge)} at hand-off × ${fmt(dw.wciOwn)} WCI / 100`:'Deep-sea PPI proxy'}</small></div><div class="total"><span>Freight subtotal index</span><strong>${fmt(r.index)}</strong><small>${c.freight==='COMPOSITE'?'8/4 ocean-truck Jan cost weights':c.freight==='TRUCK'?'Trucking only':c.freight==='OCEAN'?'Ocean only':'Held at Jan'} · Jan ${janYear}=100</small></div></div><div class="v7-formula">${dw?`Ocean chain: ${fmt(dw.ppiToBridge)} × ${fmt(dw.wciOwn)} ÷ 100 = <strong>${fmt(dw.chained)}</strong>. `:''}${c.freight==='COMPOSITE'?`Imported freight subtotal: (8 × ${fmt(r.ocean)} + 4 × ${fmt(r.truckIdx)}) ÷ 12 = <strong>${fmt(r.index)}</strong>.`:''}</div><div class="v7-warning"><strong>Why the screenshot does not visually tie:</strong> Trend Lab's “Rebased 100” uses the <em>first observation visible in the selected period</em> as 100 for each series. The landed-cost model uses January of the selected year as 100. ${wciNote} The chain-linked ocean index is therefore a <strong>DERIVED</strong> continuation series; it is not the same thing as the standalone Drewry line.</div></section>`}
function render(){if(!title.textContent.includes('Imports & Trade'))return;const layer=app.querySelector('.v6-trade-layer');if(!layer)return;let p=app.querySelector('.v7-tie-panel');if(p)p.remove();layer.insertAdjacentHTML('afterend',panel());document.getElementById('v7OpenTrend')?.addEventListener('click',openTrend)}
let timer=null;function schedule(){clearTimeout(timer);timer=setTimeout(render,30)}
new MutationObserver(schedule).observe(title,{childList:true,subtree:true,characterData:true});
new MutationObserver(schedule).observe(app,{childList:true,subtree:true});
app.addEventListener('change',e=>{if(['v6Month','v6Route','v6Freight'].includes(e.target?.id))schedule()});
schedule();
})();