(()=>{
const app=document.getElementById('app'),title=document.getElementById('viewTitle');if(!app||!title)return;
const today=()=>new Date().toISOString().slice(0,10);
const monthEnd=m=>{const [y,mo]=String(m||'').split('-').map(Number);return y&&mo?new Date(Date.UTC(y,mo,0)).toISOString().slice(0,10):today()};
function cloneControl(id){const el=document.getElementById(id);if(!el||el.dataset.v20clean)return el;const c=el.cloneNode(true);c.dataset.v20clean='1';el.replaceWith(c);return c}
function patch(){if(!title.textContent.includes('Imports & Trade'))return;const layer=app.querySelector('.v6-trade-layer'),controls=layer?.querySelector('.v6-controls');if(!layer||!controls)return;
 const head=layer.querySelector('.v6-head p');if(head)head.textContent='Choose any start and end date, route, freight basis and exactly which cost movements you want included.';
 const oldMonth=document.getElementById('v6Month'),oldM=oldMonth?.value||'2026-08';oldMonth?.closest('label')?.remove();
 if(!document.getElementById('v20Start')){const end=localStorage.getItem('fiCostCompareEndDate')||monthEnd(oldM),start=localStorage.getItem('fiCostCompareStartDate')||`${end.slice(0,4)}-01-01`,rule=localStorage.getItem('fiCostObsRule')||'NEAREST';localStorage.setItem('fiCostCompareStartDate',start);localStorage.setItem('fiCostCompareEndDate',end);localStorage.setItem('fiCostObsRule',rule);const first=controls.firstElementChild,frag=document.createDocumentFragment();const s=document.createElement('label');s.className='v20-date';s.innerHTML=`Start date<input id="v20Start" type="date" min="2019-01-01" max="${end}" value="${start}">`;const arrow=document.createElement('span');arrow.className='v20-arrow';arrow.textContent='→';const e=document.createElement('label');e.className='v20-date';e.innerHTML=`End date<input id="v20End" type="date" min="${start}" max="${today()}" value="${end}">`;const r=document.createElement('label');r.className='v20-rule';r.innerHTML=`Observation rule<select id="v20Rule"><option value="NEAREST" ${rule==='NEAREST'?'selected':''}>Closest available</option><option value="PRIOR" ${rule==='PRIOR'?'selected':''}>On or before date</option></select>`;frag.append(s,arrow,e,r);controls.insertBefore(frag,first)}
 ['v6Route','v6Fx','v6Material','v6Freight'].forEach(cloneControl);
 const fh=layer.querySelector('.v6-factor-head'),fs=layer.querySelector('.v6-factors');if(fh&&!fh.dataset.v20clean){const c=fh.cloneNode(true);c.dataset.v20clean='1';fh.replaceWith(c)}if(fs&&!fs.dataset.v20clean){const c=fs.cloneNode(true);c.dataset.v20clean='1';fs.replaceWith(c)}
 const factorHead=layer.querySelector('.v6-factor-head span');if(factorHead)factorHead.textContent='Unchecked = hold that driver at the selected starting-date level.';
 const start=document.getElementById('v20Start'),end=document.getElementById('v20End'),rule=document.getElementById('v20Rule'),route=document.getElementById('v6Route'),fx=document.getElementById('v6Fx'),freight=document.getElementById('v6Freight');
 if(start&&!start.dataset.bound){start.dataset.bound='1';start.addEventListener('change',ev=>{localStorage.setItem('fiCostCompareStartDate',ev.target.value);if(end){end.min=ev.target.value;if(end.value<ev.target.value){end.value=ev.target.value;localStorage.setItem('fiCostCompareEndDate',end.value)}}ev.target.dispatchEvent(new CustomEvent('fiCostRefresh',{bubbles:true}))})}
 if(end&&!end.dataset.bound){end.dataset.bound='1';end.addEventListener('change',ev=>{localStorage.setItem('fiCostCompareEndDate',ev.target.value);if(start)start.max=ev.target.value;ev.target.dispatchEvent(new CustomEvent('fiCostRefresh',{bubbles:true}))})}
 if(rule&&!rule.dataset.bound){rule.dataset.bound='1';rule.addEventListener('change',ev=>{localStorage.setItem('fiCostObsRule',ev.target.value);ev.target.dispatchEvent(new CustomEvent('fiCostRefresh',{bubbles:true}))})}
 if(route&&!route.dataset.v20bound){route.dataset.v20bound='1';route.addEventListener('change',()=>{if(route.value==='MFG_CA'){if(fx)fx.value='NONE';if(freight)freight.value='TRUCK'}else if(route.value==='IMPORT_TWD'){if(fx)fx.value='TWD';if(freight&&freight.value==='TRUCK')freight.value='COMPOSITE'}else if(route.value==='IMPORT_USD'){if(fx)fx.value='USD';if(freight&&freight.value==='TRUCK')freight.value='COMPOSITE'}})}
 layer.querySelectorAll('[data-solo]').forEach(b=>{if(b.dataset.v20bound)return;b.dataset.v20bound='1';b.addEventListener('click',()=>{layer.querySelectorAll('[data-factor]').forEach(x=>x.checked=x.dataset.factor===b.dataset.solo)})});
 const all=layer.querySelector('#v6All'),none=layer.querySelector('#v6None');if(all&&!all.dataset.v20bound){all.dataset.v20bound='1';all.addEventListener('click',()=>layer.querySelectorAll('[data-factor]').forEach(x=>x.checked=true))}if(none&&!none.dataset.v20bound){none.dataset.v20bound='1';none.addEventListener('click',()=>layer.querySelectorAll('[data-factor]').forEach(x=>x.checked=false))}
 if(!layer.dataset.v20kick){layer.dataset.v20kick='1';const model=document.getElementById('v6Model');if(model)model.innerHTML='<div class="v20-loading">Loading start/end comparison…</div>';setTimeout(()=>{(document.getElementById('v6Route')||start)?.dispatchEvent(new Event('change',{bubbles:true}))},0)}
}
let t;function schedule(){clearTimeout(t);t=setTimeout(patch,40)}new MutationObserver(schedule).observe(app,{childList:true,subtree:true});new MutationObserver(schedule).observe(title,{childList:true,subtree:true,characterData:true});app.addEventListener('fiCostRefresh',()=>{const x=document.getElementById('v6Route');x?.dispatchEvent(new Event('change',{bubbles:true}))});schedule();
})();