(()=>{
const app=document.getElementById('app');
const title=document.getElementById('viewTitle');
const D=window.FI_DATA||{};
const TD=window.FI_TREND_DATA||{series:{}};
if(!app||!title)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const monthEnd=m=>{const [y,mo]=m.split('-').map(Number);return new Date(Date.UTC(y,mo,0));};
const janStart=y=>new Date(Date.UTC(Number(y),0,1));
const toDate=s=>new Date(s+'T00:00:00Z');
function openSource(id){const modal=document.getElementById('sourceModal'),input=document.getElementById('sourceSearch');if(!modal||!input)return;modal.classList.add('open');modal.setAttribute('aria-hidden','false');input.value=id;input.dispatchEvent(new Event('input',{bubbles:true}));}
function src(id,label){return `<button class="v5-src" data-v5-source="${esc(id)}">${esc(label||id)}</button>`}
function bindSources(root){root.querySelectorAll('[data-v5-source]').forEach(b=>{if(b.dataset.v5bound)return;b.dataset.v5bound='1';b.addEventListener('click',e=>{e.stopPropagation();openSource(b.dataset.v5Source)})})}
function series(id){return TD.series?.[id]||null}
function obsAt(id,endDate){const s=series(id);if(!s?.data?.length)return null;let best=null;for(const p of s.data){const d=toDate(p[0]);if(d<=endDate)best=p;else break}return best}
function janObs(id,year){const s=series(id);if(!s?.data?.length)return null;const js=janStart(year),je=new Date(Date.UTC(Number(year),0,31));let first=null,lastBefore=null;for(const p of s.data){const d=toDate(p[0]);if(d<js)lastBefore=p;else if(d<=je&&!first)first=p;else if(d>je)break}return first||lastBefore}
function indexAt(id,month){const y=month.slice(0,4),base=janObs(id,y),cur=obsAt(id,monthEnd(month));if(!base||!cur||!base[1])return null;return {index:cur[1]/base[1]*100,base,cur,source:id}}
function fmtValue(id,v){const s=series(id),u=s?.units||'';if(v==null)return '—';if(u.includes('USD per 40ft'))return '$'+Math.round(v).toLocaleString()+'/40ft';if(u.includes('USD per metric ton'))return '$'+Math.round(v).toLocaleString()+'/t';if(u.includes('cents per cubic'))return Number(v).toFixed(2)+'¢/m³';if(u.includes('CAD per GJ'))return '$'+Number(v).toFixed(2)+'/GJ';if(u.includes('CAD per USD'))return Number(v).toFixed(4);if(u.includes('TWD per USD'))return Number(v).toFixed(2);return Number(v).toLocaleString(undefined,{maximumFractionDigits:2})}
function fxIndex(currency,month){const y=month.slice(0,4);if(currency==='NONE')return {index:100,label:'No FX',base:null,cur:null,source:null};const cadBase=janObs('DEXCAUS',y),cadCur=obsAt('DEXCAUS',monthEnd(month));if(!cadBase||!cadCur)return null;if(currency==='USD')return {index:cadCur[1]/cadBase[1]*100,label:'USD/CAD',base:cadBase,cur:cadCur,source:'DEXCAUS'};const twdBase=janObs('DEXTAUS',y),twdCur=obsAt('DEXTAUS',monthEnd(month));if(!twdBase||!twdCur)return null;const baseCross=cadBase[1]/twdBase[1],curCross=cadCur[1]/twdCur[1];return {index:curCross/baseCross*100,label:'CAD/TWD cross',base:[cadBase[0],baseCross],cur:[cadCur[0],curCross],source:'DEXCAUS+DEXTAUS'} }
function oceanIndex(mode,month){if(mode==='PPI')return {...indexAt('PCU4831114831115',month),label:'Deep-sea freight PPI'};const y=month.slice(0,4),ppi=indexAt('PCU4831114831115',month),w=series('DREWRY_WCI');if(!ppi)return null;if(!w?.data?.length)return {...ppi,label:'Deep-sea freight PPI fallback'};const yr=w.data.filter(p=>p[0].startsWith(y));if(!yr.length)return {...ppi,label:'Deep-sea freight PPI fallback'};const first=yr[0],end=monthEnd(month),cur=obsAt('DREWRY_WCI',end);if(!cur||toDate(cur[0])<toDate(first[0]))return {...ppi,label:'Deep-sea freight PPI fallback'};const ppiBase=janObs('PCU4831114831115',y),ppiBridge=obsAt('PCU4831114831115',toDate(first[0]));if(!ppiBase||!ppiBridge)return {...ppi,label:'Deep-sea freight PPI fallback'};const bridgeIndex=ppiBridge[1]/ppiBase[1]*100;return {index:bridgeIndex*(cur[1]/first[1]),base:ppiBase,cur,source:'DREWRY_WCI',label:'Drewry WCI chain-linked to deep-sea PPI',bridge:first}}
function tariff(profile,date){if(profile==='NONE')return {rate:0,label:'No modeled tariff',source:null,basis:'n/a'};const d=date.getTime(),d25=Date.parse('2025-03-12T00:00:00Z'),d50=Date.parse('2025-06-04T00:00:00Z'),full=Date.parse('2026-04-06T00:00:00Z');let rate=d<d25?0:d<d50?25:50;return {rate,label:'U.S. Section 232 covered steel / derivative proxy',source:'US_TARIFF',basis:d>=full?'Full customs value for covered profile under 2026 rule':'Steel content / product classification dependent'} }
const defaults={
 'IMPORT_USD':{route:'Imported finished goods',currency:'USD',material:100,conversion:0,ocean:8,inland:4,tariff:'SECTION232',steelContent:100},
 'IMPORT_TWD':{route:'Imported finished goods — Taiwan currency',currency:'TWD',material:100,conversion:0,ocean:8,inland:4,tariff:'SECTION232',steelContent:100},
 'MFG_CA':{route:'Manufactured in Canada',currency:'NONE',material:75,conversion:20,ocean:0,inland:5,tariff:'NONE',steelContent:100}
};
let lc={month:'2026-08',route:'IMPORT_TWD',currency:'TWD',materialSeries:'WPU101',oceanMode:'HYBRID',tariffProfile:'SECTION232',materialBase:100,conversionBase:0,oceanBase:8,inlandBase:4,steelContent:100};
function setRoute(r){const d=defaults[r];lc.route=r;lc.currency=d.currency;lc.tariffProfile=d.tariff;lc.materialBase=d.material;lc.conversionBase=d.conversion;lc.oceanBase=d.ocean;lc.inlandBase=d.inland;lc.steelContent=d.steelContent}
function driverState(month,override={}){const mat=indexAt(lc.materialSeries,month)||{index:100,base:null,cur:null,source:lc.materialSeries};const fx=fxIndex(lc.currency,month)||{index:100};const oc=oceanIndex(lc.oceanMode==='PPI'?'PPI':'HYBRID',month)||{index:100};const inland=indexAt('WPU3012',month)||{index:100};const energy=indexAt('QC_NATGAS',month)||indexAt('DHHNGSP',month)||{index:100};const t=tariff(lc.tariffProfile,monthEnd(month));return {material:override.material??mat.index,fx:override.fx??fx.index,tariff:override.tariff??t.rate,ocean:override.ocean??oc.index,inland:override.inland??inland.index,energy:override.energy??energy.index,mat,fxObj:fx,oceanObj:oc,inlandObj:inland,energyObj:energy,tariffObj:t}}
function totalCost(st,month){const d=monthEnd(month);const fullBase=d>=new Date('2026-04-06T00:00:00Z')?1:lc.steelContent/100;const goods=lc.materialBase*(st.material/100)*(st.fx/100);const conversion=lc.conversionBase*(st.energy/100);const ocean=lc.oceanBase*(st.ocean/100);const inland=lc.inlandBase*(st.inland/100);const duty=goods*(st.tariff/100)*fullBase;return {goods,conversion,ocean,inland,duty,total:goods+conversion+ocean+inland+duty,tariffBasePct:fullBase*100}}
function decomposition(){const y=lc.month.slice(0,4),baseMonth=y+'-01';const b=driverState(baseMonth),s=driverState(lc.month);const baseCost=totalCost(b,baseMonth);let cur={...b};let prev=baseCost.total;const out=[];for(const key of ['material','fx','tariff','ocean','inland','energy']){cur[key]=s[key];const next=totalCost(cur,lc.month).total;out.push({key,points:(next-prev)/baseCost.total*100,from:prev/baseCost.total*100,to:next/baseCost.total*100});prev=next}const final=prev/baseCost.total*100;return {baseMonth,b,s,baseCost,selectedCost:totalCost(s,lc.month),steps:out,final}}
const labels={material:'Material / supplier price',fx:'FX',tariff:'Tariff',ocean:'Ocean freight',inland:'Mainland freight',energy:'Conversion energy'};
function waterfallSvg(dec){const vals=[100,...dec.steps.map(s=>s.to),dec.final],min=Math.min(90,...vals)-3,max=Math.max(110,...vals)+3,W=820,H=285,left=42,right=18,top=18,bottom=54,plotH=H-top-bottom;const y=v=>top+(max-v)/(max-min)*plotH;const bw=72,gap=31;let x=left+12;let bars=`<line x1="${left}" x2="${W-right}" y1="${y(100)}" y2="${y(100)}" class="v5-base-line"/><text x="${left}" y="${y(100)-5}" class="v5-axis-label">Jan 1 = 100</text>`;bars+=`<rect x="${x}" y="${y(100)}" width="${bw}" height="${Math.max(2,y(min)-y(100))}" class="v5-wf-start"/><text x="${x+bw/2}" y="${y(100)-7}" text-anchor="middle" class="v5-wf-val">100.0</text><text x="${x+bw/2}" y="${H-22}" text-anchor="middle" class="v5-wf-label">JAN BASE</text>`;let prev=100;x+=bw+gap;dec.steps.forEach(st=>{const a=prev,b=st.to,yy=Math.min(y(a),y(b)),hh=Math.max(3,Math.abs(y(a)-y(b))),cls=st.points>=0?'up':'down';bars+=`<line x1="${x-gap}" x2="${x}" y1="${y(a)}" y2="${y(a)}" class="v5-connector"/><rect x="${x}" y="${yy}" width="${bw}" height="${hh}" class="v5-wf-change ${cls}"/><text x="${x+bw/2}" y="${yy-6}" text-anchor="middle" class="v5-wf-val">${st.points>=0?'+':''}${st.points.toFixed(1)}</text><text x="${x+bw/2}" y="${H-22}" text-anchor="middle" class="v5-wf-label">${labels[st.key].replace(' / ','/')}</text>`;prev=b;x+=bw+gap});bars+=`<line x1="${x-gap}" x2="${x}" y1="${y(prev)}" y2="${y(prev)}" class="v5-connector"/><rect x="${x}" y="${y(dec.final)}" width="${bw}" height="${Math.max(3,y(min)-y(dec.final))}" class="v5-wf-total"/><text x="${x+bw/2}" y="${y(dec.final)-7}" text-anchor="middle" class="v5-wf-val">${dec.final.toFixed(1)}</text><text x="${x+bw/2}" y="${H-22}" text-anchor="middle" class="v5-wf-label">LANDED INDEX</text>`;return `<svg class="v5-waterfall" viewBox="0 0 ${W} ${H}" role="img" aria-label="Landed cost index waterfall from January base 100 to selected month">${bars}</svg>`}
function observationRow(name,obj,index,points,sourceLabel){if(!obj)return `<tr><td>${name}</td><td colspan="6">No source observation</td></tr>`;const b=obj.base||null,c=obj.cur||null;return `<tr><td>${name}</td><td>${b?esc(b[0]):'—'}</td><td>${b?esc(fmtValue(obj.source||'',b[1])):'—'}</td><td>${c?esc(c[0]):'—'}</td><td>${c?esc(fmtValue(obj.source||'',c[1])):'—'}</td><td>${index?.toFixed?index.toFixed(1):'—'}</td><td>${points>=0?'+':''}${points.toFixed(1)}</td><td>${sourceLabel||''}</td></tr>`}
function tradeControls(){return `<div class="v5-controls"><label>Month<select id="v5Month">${['2025-01','2025-02','2025-03','2025-04','2025-05','2025-06','2025-07','2025-08','2025-09','2025-10','2025-11','2025-12','2026-01','2026-02','2026-03','2026-04','2026-05','2026-06','2026-07','2026-08'].map(m=>`<option ${m===lc.month?'selected':''}>${m}</option>`).join('')}</select></label><label>Supply mode<select id="v5Route"><option value="IMPORT_USD" ${lc.route==='IMPORT_USD'?'selected':''}>Imported — USD supplier</option><option value="IMPORT_TWD" ${lc.route==='IMPORT_TWD'?'selected':''}>Imported — Taiwan / TWD supplier</option><option value="MFG_CA" ${lc.route==='MFG_CA'?'selected':''}>Manufactured — Canada</option></select></label><label>Supplier FX<select id="v5Fx"><option value="NONE" ${lc.currency==='NONE'?'selected':''}>None</option><option value="USD" ${lc.currency==='USD'?'selected':''}>USD → CAD</option><option value="TWD" ${lc.currency==='TWD'?'selected':''}>TWD → CAD cross</option></select></label><label>Material benchmark<select id="v5Material"><option value="WPU101" ${lc.materialSeries==='WPU101'?'selected':''}>Iron & Steel PPI</option><option value="WPU10" ${lc.materialSeries==='WPU10'?'selected':''}>Metals & Metal Products PPI</option><option value="PZINCUSDM" ${lc.materialSeries==='PZINCUSDM'?'selected':''}>Zinc</option><option value="PNICKUSDM" ${lc.materialSeries==='PNICKUSDM'?'selected':''}>Nickel</option></select></label><label>Ocean benchmark<select id="v5Ocean"><option value="HYBRID" ${lc.oceanMode==='HYBRID'?'selected':''}>Drewry WCI + historical freight PPI</option><option value="PPI" ${lc.oceanMode==='PPI'?'selected':''}>Deep-sea freight PPI only</option></select></label><label>Tariff profile<select id="v5Tariff"><option value="NONE" ${lc.tariffProfile==='NONE'?'selected':''}>None</option><option value="SECTION232" ${lc.tariffProfile==='SECTION232'?'selected':''}>U.S. Section 232 covered steel proxy</option></select></label></div><details class="v5-weights"><summary>Jan cost structure / product assumptions</summary><div class="v5-controls"><label>Material / goods<input id="v5MaterialBase" type="number" value="${lc.materialBase}"></label><label>Conversion / energy<input id="v5ConversionBase" type="number" value="${lc.conversionBase}"></label><label>Ocean freight<input id="v5OceanBase" type="number" value="${lc.oceanBase}"></label><label>Mainland freight<input id="v5InlandBase" type="number" value="${lc.inlandBase}"></label><label>Steel content %<input id="v5SteelContent" type="number" min="0" max="100" value="${lc.steelContent}"></label></div><p>These are scenario weights, not reported Infasco costs. All <em>changes through time</em> are linked to dated indicators.</p></details>`}
function tradeDataPanel(dec){const step=Object.fromEntries(dec.steps.map(x=>[x.key,x]));const s=dec.s;return `<div class="v5-index-cards"><div><span>Landed cost index</span><strong>${dec.final.toFixed(1)}</strong><small>Jan 1 ${lc.month.slice(0,4)} = 100</small></div><div><span>Material</span><strong>${s.material.toFixed(1)}</strong><small>${series(lc.materialSeries)?.name||lc.materialSeries}</small></div><div><span>FX</span><strong>${s.fx.toFixed(1)}</strong><small>${s.fxObj.label||'No FX'}</small></div><div><span>Ocean</span><strong>${s.ocean.toFixed(1)}</strong><small>${s.oceanObj.label||''}</small></div><div><span>Trucking</span><strong>${s.inland.toFixed(1)}</strong><small>Truck freight PPI</small></div><div><span>Tariff</span><strong>${s.tariff.toFixed(0)}%</strong><small>${s.tariffObj.basis}</small></div></div>${waterfallSvg(dec)}<div class="v5-table-wrap"><table class="v5-table"><thead><tr><th>Driver</th><th>Jan obs.</th><th>Jan value</th><th>Selected obs.</th><th>Selected value</th><th>Index</th><th>Index-pt impact</th><th>Source</th></tr></thead><tbody>${observationRow('Material',s.mat,s.material,step.material.points,src(lc.materialSeries,'source'))}${observationRow('FX',s.fxObj,s.fx,step.fx.points,s.fxObj.source?src(s.fxObj.source.split('+')[0],'FX source'):'—')}${observationRow('Ocean freight',s.oceanObj,s.ocean,step.ocean.points,s.oceanObj.source==='DREWRY_WCI'?src('DREWRY_WCI','Drewry WCI'):src('PCU4831114831115','Deep-sea PPI'))}${observationRow('Mainland freight',s.inlandObj,s.inland,step.inland.points,src('WPU3012','Truck freight PPI'))}${observationRow('Conversion energy',s.energyObj,s.energy,step.energy.points,src(s.energyObj.source||'QC_NATGAS','Energy'))}<tr><td>Tariff</td><td>effective-date rule</td><td>${tariff(lc.tariffProfile,monthEnd(dec.baseMonth)).rate}%</td><td>${lc.month}</td><td>${s.tariff}%</td><td>step function</td><td>${step.tariff.points>=0?'+':''}${step.tariff.points.toFixed(1)}</td><td>${src('US_TARIFF','trade policy')}</td></tr></tbody></table></div><div class="v5-note"><strong>Method:</strong> total landed cost is recalculated at each selected date, then rebased so January 1 of the selected year = 100. Imported mode uses ocean + mainland freight; manufactured mode removes ocean/tariff and uses mainland freight plus Québec natural-gas conversion. TWD sourcing uses the CAD/TWD cross derived from USD/CAD ÷ USD/TWD. Drewry public WCI observations begin in the dashboard in June 2026; earlier months chain to the BLS deep-sea freight PPI and are explicitly identified as a proxy.</div>`}
function worldMap(){return `<div class="v5-map-shell world"><div class="v5-map-fallback">Loading geographic basemap…</div><img class="v5-map-img" src="world.svg" data-external="https://simplemaps.com/static/demos/resources/svg-library/svgs/world.svg" alt="World geographic basemap"><svg class="v5-route-overlay" viewBox="0 0 1000 500" preserveAspectRatio="none" aria-label="Indicative trade lanes"><defs><marker id="v5arr" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z"/></marker></defs><path d="M790 210 C690 185 555 170 335 205"/><path d="M815 250 C700 250 575 220 335 210"/><path d="M545 145 C480 155 405 175 335 205"/><path d="M295 250 C310 235 320 225 335 210"/></svg><span class="v5-origin tw">Taiwan</span><span class="v5-origin cn">China</span><span class="v5-origin eu">Europe</span><span class="v5-origin mx">Mexico</span><span class="v5-dest">North America</span></div>`}
function capacityMap(){return `<div class="v5-map-shell capacity"><div class="v5-map-fallback">Loading North America basemap…</div><img class="v5-map-img" src="north-america.svg" data-external="https://simplemaps.com/static/demos/resources/svg-library/svgs/north-america.svg" alt="North America geographic basemap"><button class="v5-cap-pin upstream" style="left:52%;top:56%" data-v5-source="NUCOR_Q2"><b>Nucor</b><span>Upstream steel capacity</span></button><button class="v5-cap-pin expand" style="left:61%;top:50%" data-v5-source="PKOH_CALL"><b>Supply Technologies</b><span>Distribution / automation</span></button><button class="v5-cap-pin expand" style="left:69%;top:57%" data-v5-source="LISI_H1"><b>LISI</b><span>NA industrial investment</span></button><button class="v5-cap-pin upstream" style="left:45%;top:47%" data-v5-source="AM_Q2"><b>ArcelorMittal</b><span>Upstream footprint</span></button><div class="v5-cap-legend"><span><i class="expand"></i> Expansion / investment</span><span><i class="upstream"></i> Upstream leverage</span><span>Markers are regional unless a facility-level source is loaded.</span></div></div>`}
function bindMaps(root){root.querySelectorAll('.v5-map-img').forEach(img=>{const fb=img.parentElement.querySelector('.v5-map-fallback');const loaded=()=>{img.classList.add('loaded');if(fb)fb.style.display='none'};img.addEventListener('load',loaded,{once:true});img.addEventListener('error',()=>{if(!img.dataset.tried){img.dataset.tried='1';img.src=img.dataset.external}else{img.style.display='none';if(fb){fb.textContent='Basemap asset unavailable — overlays and source controls remain active.';fb.classList.add('failed')}}});if(img.complete&&img.naturalWidth)loaded()})}
function renderTrade(){if(app.querySelector('.v5-trade-visuals'))return;const old=app.querySelector('.v4-trade-visuals');if(old)old.style.display='none';const wrap=document.createElement('div');wrap.className='v5-stack v5-trade-visuals';wrap.innerHTML=`<section class="v5-panel span-7"><div class="v5-head"><div><h2>Trade Flow & Origin Map</h2><p>Real geographic basemap with indicative sourcing lanes; lane paths are directional, not shipment-volume scaled.</p></div><span class="v5-badge">MAP</span></div>${worldMap()}<div class="v5-sources">${src('US_TARIFF','Tariff rules')} ${src('DEXTAUS','USD/TWD')} ${src('DREWRY_WCI','Drewry WCI')}</div></section><section class="v5-panel span-5"><div class="v5-head"><div><h2>Indexed Landed Cost</h2><p>Date-aware model. January 1 of the selected year is always 100.</p></div><span class="v5-badge">DERIVED</span></div>${tradeControls()}<div id="v5LandedBody"></div></section>`;const grid=app.querySelector('.dashboard-grid');app.insertBefore(wrap,grid||app.firstChild);bindSources(wrap);bindMaps(wrap);bindTradeControls(wrap);updateTradeModel(wrap)}
function bindTradeControls(root){const ids=['v5Month','v5Route','v5Fx','v5Material','v5Ocean','v5Tariff','v5MaterialBase','v5ConversionBase','v5OceanBase','v5InlandBase','v5SteelContent'];ids.forEach(id=>{const el=root.querySelector('#'+id);if(!el)return;el.addEventListener('change',()=>{if(id==='v5Route'){setRoute(el.value);rerenderTradePanel(root);return}lc.month=root.querySelector('#v5Month').value;lc.currency=root.querySelector('#v5Fx').value;lc.materialSeries=root.querySelector('#v5Material').value;lc.oceanMode=root.querySelector('#v5Ocean').value;lc.tariffProfile=root.querySelector('#v5Tariff').value;lc.materialBase=Number(root.querySelector('#v5MaterialBase').value)||0;lc.conversionBase=Number(root.querySelector('#v5ConversionBase').value)||0;lc.oceanBase=Number(root.querySelector('#v5OceanBase').value)||0;lc.inlandBase=Number(root.querySelector('#v5InlandBase').value)||0;lc.steelContent=Math.min(100,Math.max(0,Number(root.querySelector('#v5SteelContent').value)||0));updateTradeModel(root)})})}
function rerenderTradePanel(root){lc.month=root.querySelector('#v5Month')?.value||lc.month;lc.materialSeries=root.querySelector('#v5Material')?.value||lc.materialSeries;lc.oceanMode=root.querySelector('#v5Ocean')?.value||lc.oceanMode;const panel=root.querySelector('.span-5');panel.innerHTML=`<div class="v5-head"><div><h2>Indexed Landed Cost</h2><p>Date-aware model. January 1 of the selected year is always 100.</p></div><span class="v5-badge">DERIVED</span></div>${tradeControls()}<div id="v5LandedBody"></div>`;bindTradeControls(root);updateTradeModel(root)}
function updateTradeModel(root){const body=root.querySelector('#v5LandedBody');if(!body)return;const dec=decomposition();body.innerHTML=tradeDataPanel(dec);bindSources(body)}
function renderCapacity(){if(app.querySelector('.v5-capacity-visuals'))return;const old=app.querySelector('.v4-capacity-visuals');if(old)old.style.display='none';const wrap=document.createElement('div');wrap.className='v5-stack v5-capacity-visuals';wrap.innerHTML=`<section class="v5-panel span-8"><div class="v5-head"><div><h2>North America Capacity Map</h2><p>Geographic basemap with source-controlled capacity signals. Regional markers are used where public disclosure is not facility-specific.</p></div><span class="v5-badge">CAPACITY</span></div>${capacityMap()}<div class="v5-sources">Map geometry: SimpleMaps free SVG · ${src('NUCOR_Q2','Nucor')} ${src('PKOH_CALL','Supply Tech')} ${src('LISI_H1','LISI')} ${src('AM_Q2','ArcelorMittal')}</div></section><section class="v5-panel span-4"><div class="v5-head"><div><h2>Capacity Layers</h2><p>Use the map as a capacity intelligence surface rather than a decorative footprint.</p></div></div><div class="v5-layer-list"><div><strong>Upstream steel</strong><span>Nucor, ArcelorMittal and domestic steel pricing/capacity signals.</span></div><div><strong>Fastener manufacturing</strong><span>Publicly disclosed plants, expansions, closures and productivity investments.</span></div><div><strong>Distribution capacity</strong><span>DC openings, automation, consolidation and network changes.</span></div><div><strong>Customer localization</strong><span>OEM / distributor sourcing actions that change domestic capacity requirements.</span></div></div><div class="v5-note">Next-level map pins should only be facility-specific when a company release, filing or official location page supports the site. The map intentionally avoids invented tonnage or fabricated coordinates.</div></section>`;const grid=app.querySelector('.dashboard-grid');app.insertBefore(wrap,grid||app.firstChild);bindSources(wrap);bindMaps(wrap)}
function apply(){const t=title.textContent||'';if(t.includes('Imports & Trade'))renderTrade();else if(t.includes('Capacity Map'))renderCapacity()}
let scheduled=false;const obs=new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;apply()})});obs.observe(app,{childList:true,subtree:true});obs.observe(title,{childList:true,subtree:true,characterData:true});setTimeout(apply,120);
})();
