(()=>{
const app=document.getElementById('app'),title=document.getElementById('viewTitle'),subtitle=document.getElementById('viewSubtitle'),IO=window.FI_IMPORT_ORIGINS||{};
if(!app||!title)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const SOURCES={
 fontana:'https://fontanagruppoagtna.com/locations/',
 lisi:'https://www.lisi-group.com/en/lisi-around-the-world.html',
 bulten:'https://www.bulten.com/en/news/press-releases/?slug=following-strategic-review-bulten-consolidates-manufacturing-and-makes-changes-to-u-s-operations',
 trifast:'https://www.trfastenings.com/tr-usa',
 supplytech:'https://www.supplytechnologies.com/resources/blog/building-the-standard-what-our-new-north-american-distribution-center-means-for-customers',
 census:IO.sourceUrl||'https://www.census.gov/foreign-trade/reference/guides/tradestatsinfo.html'
};
const capSites=[
 {company:'Fontana / Acument',site:'Sterling Heights',place:'Sterling Heights, MI',lat:42.58,lon:-83.03,role:'Peer manufacturing',status:'Active',source:'fontana'},
 {company:'Fontana / Acument',site:'Baldwin / Holly',place:'Holly, MI',lat:42.79,lon:-83.63,role:'Peer manufacturing',status:'Active',source:'fontana'},
 {company:'Fontana / Acument',site:'Fenton',place:'Fenton, MI',lat:42.80,lon:-83.71,role:'Peer manufacturing',status:'Active',source:'fontana'},
 {company:'Fontana / Acument',site:'Belvidere',place:'Belvidere, IL',lat:42.26,lon:-88.84,role:'Peer manufacturing',status:'Active',source:'fontana'},
 {company:'Fontana / Acument',site:'Frankfort',place:'Frankfort, IN',lat:40.28,lon:-86.51,role:'Peer manufacturing',status:'Active',source:'fontana'},
 {company:'Fontana / Acument',site:'Spencer',place:'Spencer, TN',lat:35.75,lon:-85.46,role:'Peer manufacturing',status:'Active',source:'fontana'},
 {company:'Fontana / Acument',site:'Burbank',place:'Burbank, CA',lat:34.18,lon:-118.31,role:'Peer manufacturing',status:'Active',source:'fontana'},
 {company:'Fontana / Acument',site:'Santa Catarina',place:'Nuevo León, Mexico',lat:25.67,lon:-100.46,role:'Peer manufacturing',status:'Active',source:'fontana'},
 {company:'LISI Automotive',site:'Lake Zurich',place:'Lake Zurich, IL',lat:42.20,lon:-88.09,role:'Peer manufacturing',status:'Active',source:'lisi'},
 {company:'LISI Automotive',site:'Livonia',place:'Livonia, MI',lat:42.37,lon:-83.35,role:'Peer manufacturing',status:'Active',source:'lisi'},
 {company:'LISI Automotive',site:'Monterrey',place:'Monterrey, Mexico',lat:25.69,lon:-100.32,role:'Peer manufacturing',status:'Active',source:'lisi'},
 {company:'LISI Automotive',site:'Querétaro',place:'Querétaro, Mexico',lat:20.59,lon:-100.39,role:'Peer manufacturing',status:'Active',source:'lisi'},
 {company:'LISI Aerospace',site:'Dorval',place:'Dorval, QC',lat:45.45,lon:-73.75,role:'Peer manufacturing',status:'Active',source:'lisi'},
 {company:'LISI Aerospace',site:'City of Industry',place:'City of Industry, CA',lat:34.02,lon:-117.96,role:'Peer manufacturing',status:'Active',source:'lisi'},
 {company:'LISI Aerospace',site:'Garden Grove',place:'Garden Grove, CA',lat:33.77,lon:-117.94,role:'Peer manufacturing',status:'Active',source:'lisi'},
 {company:'LISI Aerospace',site:'Torrance',place:'Torrance, CA',lat:33.84,lon:-118.34,role:'Peer manufacturing',status:'Active',source:'lisi'},
 {company:'Bulten',site:'Streetsboro',place:'Streetsboro, OH',lat:41.24,lon:-81.35,role:'Peer distribution',status:'Production discontinued / distribution model',source:'bulten'},
 {company:'Trifast / TR',site:'Houston',place:'Houston, TX',lat:29.76,lon:-95.37,role:'Peer distribution',status:'Active',source:'trifast'},
 {company:'Trifast / TR',site:'Charlotte',place:'Charlotte, NC',lat:35.23,lon:-80.84,role:'Peer distribution',status:'Active',source:'trifast'},
 {company:'Trifast / TR',site:'Louisville',place:'Louisville, KY',lat:38.25,lon:-85.76,role:'Peer distribution',status:'Active',source:'trifast'},
 {company:'Supply Technologies',site:'North American Distribution Center',place:'Union, OH',lat:39.90,lon:-84.31,role:'Customer / distributor capacity',status:'375,000 sq ft hub',source:'supplytech'}
];
const countryCoords={
 'taiwan':[23.70,121.00],'china':[35.86,104.20],'japan':[36.20,138.25],'germany':[51.17,10.45],'canada':[56.13,-106.35],'italy':[41.87,12.57],'india':[20.59,78.96],'south korea':[35.91,127.77],'republic of korea':[35.91,127.77],'mexico':[23.63,-102.55],'vietnam':[14.06,108.28],'thailand':[15.87,100.99],'turkey':[38.96,35.24],'malaysia':[4.21,101.98],'france':[46.23,2.21],'united kingdom':[55.38,-3.44],'spain':[40.46,-3.75],'sweden':[60.13,18.64],'poland':[51.92,19.15],'czech republic':[49.82,15.47],'czechia':[49.82,15.47],'brazil':[-14.24,-51.93],'indonesia':[-0.79,113.92],'philippines':[12.88,121.77],'singapore':[1.35,103.82],'austria':[47.52,14.55],'switzerland':[46.82,8.23],'belgium':[50.50,4.47],'netherlands':[52.13,5.29],'portugal':[39.40,-8.22],'united states':[39.83,-98.58],'united states of america':[39.83,-98.58]
};
function normCountry(n){return String(n||'').toLowerCase().replace(/\([^)]*\)/g,'').replace(/^federal republic of /,'').replace(/\s+/g,' ').trim()}
function coordCountry(n){let k=normCountry(n);if(countryCoords[k])return countryCoords[k];if(k.includes('germany'))return countryCoords.germany;if(k.includes('korea'))return countryCoords['south korea'];if(k.includes('taiwan'))return countryCoords.taiwan;if(k.includes('united kingdom'))return countryCoords['united kingdom'];return null}
function link(k,label='Source'){return `<a class="v13-source" href="${esc(SOURCES[k]||k)}" target="_blank" rel="noopener">${esc(label)} ↗</a>`}
function worldXY(lat,lon){return [(lon+180)/360*1000,(90-lat)/180*500]}
function naXY(lat,lon){const minLon=-130,maxLon=-60,minLat=15,maxLat=60;return [(lon-minLon)/(maxLon-minLon)*1000,(maxLat-lat)/(maxLat-minLat)*560]}
function graticuleWorld(){let s='';for(let lon=-150;lon<=150;lon+=30){const [x]=worldXY(0,lon);s+=`<line class="v13-grid" x1="${x}" x2="${x}" y1="25" y2="475"/>`}for(let lat=-60;lat<=60;lat+=30){const [,y]=worldXY(lat,0);s+=`<line class="v13-grid" x1="20" x2="980" y1="${y}" y2="${y}"/>`}return s}
function landWorld(){const polys=[
 [[72,-168],[70,-140],[55,-125],[48,-105],[30,-95],[20,-82],[45,-60],[62,-65],[72,-100]],
 [[12,-82],[8,-62],[-10,-48],[-35,-55],[-55,-70],[-20,-80]],
 [[70,-10],[70,40],[48,45],[35,20],[40,-10]],
 [[35,-18],[35,45],[-30,48],[-35,15],[0,-15]],
 [[72,40],[70,175],[15,170],[5,120],[10,70],[35,45]],
 [[-10,110],[-10,155],[-45,155],[-45,115]]
 ];return polys.map(p=>`<polygon class="v13-land" points="${p.map(([lat,lon])=>worldXY(lat,lon).join(',')).join(' ')}"/>`).join('')}
function landNA(){const p=[[58,-128],[55,-115],[50,-105],[49,-95],[48,-85],[46,-75],[40,-70],[30,-82],[25,-98],[18,-104],[25,-115],[34,-120],[45,-125]];return `<polygon class="v13-land" points="${p.map(([lat,lon])=>naXY(lat,lon).join(',')).join(' ')}"/>`}
function importMapSvg(){const rows=(IO.countries||[]).slice(0,10),dest=worldXY(39.83,-98.58);let routes='',pts='';rows.forEach((r,i)=>{const c=coordCountry(r.name);if(!c)return;const [x,y]=worldXY(c[0],c[1]),share=+r.share||0,rad=Math.max(5,Math.min(18,4+Math.sqrt(share)*2.1)),label=i<6?`<text class="v13-map-label" x="${x+rad+4}" y="${y-3}">${esc(r.name)} ${share.toFixed(1)}%</text>`:'';const midx=(x+dest[0])/2,midy=Math.min(y,dest[1])-35-Math.abs(x-dest[0])*.035;routes+=`<path class="v13-route" d="M${x},${y} Q${midx},${midy} ${dest[0]},${dest[1]}"/>`;pts+=`<g><circle class="v13-origin" cx="${x}" cy="${y}" r="${rad}"><title>${esc(r.name)} — ${share.toFixed(1)}% of U.S. HS 7318 import value</title></circle>${label}</g>`});return `<svg class="v13-world" viewBox="0 0 1000 500" role="img" aria-label="Geographic map of top U.S. fastener import origins">${graticuleWorld()}${landWorld()}<text class="v13-region" x="170" y="145">NORTH AMERICA</text><text class="v13-region" x="465" y="150">EUROPE</text><text class="v13-region" x="700" y="170">ASIA</text>${routes}<circle class="v13-dest" cx="${dest[0]}" cy="${dest[1]}" r="10"/><text class="v13-dest-label" x="${dest[0]+14}" y="${dest[1]+4}">U.S. destination</text>${pts}</svg>`}
function importLegend(){const rows=(IO.countries||[]).slice(0,10);return `<div class="v13-import-list">${rows.map((r,i)=>`<div><b>${i+1}</b><span>${esc(r.name)}</span><i style="width:${Math.min(100,+r.share||0)}%"></i><strong>${(+r.share||0).toFixed(1)}%</strong></div>`).join('')}</div>`}
function renderTrade(){if(!title.textContent.includes('Imports & Trade'))return;app.querySelectorAll('.v4-trade-visuals,.v5-trade-visuals,.v12-import-geo').forEach(x=>x.style.display='none');if(app.querySelector('.v13-import-map'))return;const sec=document.createElement('section');sec.className='v13-panel v13-import-map';sec.innerHTML=`<div class="v13-head"><div><h2>U.S. Fastener Import Geography</h2><p>Top origins are plotted from country latitude/longitude centroids. Marker size equals share of U.S. HS 7318 import value; routes point to the U.S. and are not shipment lanes or port routings.</p></div><span>FACT · CENSUS</span></div><div class="v13-import-grid"><div>${importMapSvg()}<div class="v13-map-note">Geography is coordinate-driven, not hand-positioned. Latest Census period: <strong>${esc(IO.asOf||'latest available')}</strong>. ${link('census','Census data')}</div></div><div><h3>Origin concentration</h3>${importLegend()}<p class="v13-muted">This visual answers <strong>where imported fasteners originate</strong>. It does not imply where individual suppliers manufacture or which ports the goods use.</p></div></div>`;const anchor=app.querySelector('.v6-trade-layer')||app.firstChild;app.insertBefore(sec,anchor)}
function capColor(role,status){if(status.toLowerCase().includes('discontinued'))return 'exit';if(role.includes('manufacturing'))return 'mfg';if(role.includes('distribution'))return 'dist';return 'customer'}
function capMapSvg(filter='ALL'){const rows=capSites.filter(s=>filter==='ALL'||(filter==='MFG'&&s.role==='Peer manufacturing')||(filter==='DIST'&&s.role==='Peer distribution')||(filter==='CUSTOMER'&&s.role.startsWith('Customer')));let pts='';rows.forEach(s=>{const [x,y]=naXY(s.lat,s.lon),cls=capColor(s.role,s.status),r=cls==='customer'?8:cls==='exit'?9:6;pts+=`<g class="v13-cap-point"><circle class="${cls}" cx="${x}" cy="${y}" r="${r}"><title>${esc(s.company)} — ${esc(s.site)} | ${esc(s.place)} | ${esc(s.role)} | ${esc(s.status)}</title></circle></g>`});return `<svg class="v13-na" viewBox="0 0 1000 560" role="img" aria-label="North America peer capacity and footprint map">${landNA()}<text class="v13-country-label" x="390" y="95">CANADA</text><text class="v13-country-label" x="440" y="280">UNITED STATES</text><text class="v13-country-label" x="410" y="475">MEXICO</text>${pts}</svg>`}
function capTable(filter='ALL'){const rows=capSites.filter(s=>filter==='ALL'||(filter==='MFG'&&s.role==='Peer manufacturing')||(filter==='DIST'&&s.role==='Peer distribution')||(filter==='CUSTOMER'&&s.role.startsWith('Customer')));return `<div class="v13-cap-table"><table><thead><tr><th>Company</th><th>Site</th><th>Geography</th><th>Role</th><th>Status / read-through</th><th>Source</th></tr></thead><tbody>${rows.map(s=>`<tr><td>${esc(s.company)}</td><td>${esc(s.site)}</td><td>${esc(s.place)}</td><td><span class="v13-role ${capColor(s.role,s.status)}">${esc(s.role)}</span></td><td>${esc(s.status)}</td><td>${link(s.source)}</td></tr>`).join('')}</tbody></table></div>`}
function capacitySummary(){return `<div class="v13-purpose"><div><b>Competitive localization</b><span>Shows which peers have actual North American manufacturing rather than imported-only exposure.</span></div><div><b>Lead-time & freight</b><span>Local plants and VMI/distribution footprints can change response time and landed-cost economics.</span></div><div><b>Capacity actions</b><span>Separates expansion, active footprint and manufacturing exits such as Bulten Streetsboro.</span></div><div><b>Customer corridor overlap</b><span>Highlights where peer capacity sits near Midwest automotive, Southern industrial and Mexico manufacturing clusters.</span></div></div>`}
function strategicRead(){return `<div class="v13-read"><div><strong>Fontana / Acument</strong><span>Dense U.S. manufacturing footprint plus Mexico plant gives strong localization in automotive corridors.</span>${link('fontana','Locations')}</div><div><strong>LISI</strong><span>North American production spans aerospace and automotive across Canada, the U.S. and Mexico.</span>${link('lisi','Footprint')}</div><div><strong>Bulten</strong><span>Streetsboro is a manufacturing exit: the U.S. model shifts to distribution/sourcing, so it should not be read as active production capacity.</span>${link('bulten','2026 action')}</div><div><strong>Trifast / TR</strong><span>Houston, Charlotte and Louisville are distribution/VMI sites, not manufacturing plants.</span>${link('trifast','U.S. locations')}</div><div><strong>Supply Technologies</strong><span>Union, Ohio is customer/distributor capacity: a 375,000 sq ft North American distribution hub, not peer manufacturing.</span>${link('supplytech','NADC')}</div></div>`}
function renderCapacity(){if(!/Capacity Map|Capacity & Footprint/.test(title.textContent))return;if(subtitle)subtitle.textContent='Competitive manufacturing footprint, distribution reach, localization and capacity actions';app.querySelectorAll('.v4-capacity-visuals,.v5-capacity-visuals,.v12-capacity').forEach(x=>x.style.display='none');if(app.querySelector('.v13-capacity'))return;const sec=document.createElement('section');sec.className='v13-panel v13-capacity';sec.innerHTML=`<div class="v13-head"><div><h2>What this tab is for: Capacity & Footprint Intelligence</h2><p>The management question is not “where are dots on a map?” It is <strong>which competitors can produce locally, which only distribute locally, how that footprint is changing, and what it means for localization, freight, lead time and customer awards.</strong></p></div><span>SOURCE-CONTROLLED</span></div>${capacitySummary()}<div class="v13-cap-controls"><button class="active" data-v13-cap="ALL">All verified footprint</button><button data-v13-cap="MFG">Peer manufacturing</button><button data-v13-cap="DIST">Peer distribution / VMI</button><button data-v13-cap="CUSTOMER">Customer / distributor capacity</button></div><div class="v13-cap-grid"><div><div id="v13CapMap">${capMapSvg('ALL')}</div><div class="v13-cap-legend"><span><i class="mfg"></i>Peer manufacturing</span><span><i class="dist"></i>Peer distribution/VMI</span><span><i class="exit"></i>Manufacturing exit</span><span><i class="customer"></i>Customer/distributor capacity</span></div></div>${strategicRead()}</div><div id="v13CapTable">${capTable('ALL')}</div><div class="v13-map-note"><strong>Geography control:</strong> every plotted point uses a city latitude/longitude tied to a company location source. The map does not infer tonnage. Capacity tonnage will only be added when explicitly disclosed.</div>`;app.insertBefore(sec,app.firstChild);sec.querySelectorAll('[data-v13-cap]').forEach(b=>b.addEventListener('click',()=>{sec.querySelectorAll('[data-v13-cap]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.v13Cap;sec.querySelector('#v13CapMap').innerHTML=capMapSvg(f);sec.querySelector('#v13CapTable').innerHTML=capTable(f)}))}
function clean(){const t=title.textContent||'';if(!t.includes('Imports & Trade'))app.querySelector('.v13-import-map')?.remove();if(!/Capacity Map|Capacity & Footprint/.test(t))app.querySelector('.v13-capacity')?.remove()}
function apply(){clean();renderTrade();renderCapacity()}
let q=false;function schedule(){if(q)return;q=true;requestAnimationFrame(()=>{q=false;apply()})}
new MutationObserver(schedule).observe(title,{childList:true,subtree:true,characterData:true});
new MutationObserver(schedule).observe(app,{childList:true});
setTimeout(apply,120);
})();