(()=>{
const app=document.getElementById('app'),title=document.getElementById('viewTitle'),TD=window.FI_TREND_DATA||{series:{}};
if(!app||!title)return;
const toDate=s=>new Date(s+'T00:00:00Z');
const monthEnd=m=>{const [y,mo]=m.split('-').map(Number);return new Date(Date.UTC(y,mo,0));};
const janStart=y=>new Date(Date.UTC(+y,0,1));
function meta(id){return TD.series?.[id]||null}
function obsAt(id,end){const s=meta(id);if(!s?.data?.length)return null;let best=null;for(const p of s.data){const d=toDate(p[0]);if(d<=end)best=p;else break}return best}
function janObs(id,y){const s=meta(id);if(!s?.data?.length)return null;const js=janStart(y),je=new Date(Date.UTC(+y,0,31));let prior=null,first=null;for(const p of s.data){const d=toDate(p[0]);if(d<js)prior=p;else if(d<=je&&!first)first=p;else if(d>je)break}return first||prior}
function idx(id,month){const y=month.slice(0,4),b=janObs(id,y),c=obsAt(id,monthEnd(month));if(!b||!c||!b[1])return null;return {id,index:c[1]/b[1]*100,base:b,cur:c,meta:meta(id)}}
function fx(currency,month){const y=month.slice(0,4);if(currency==='NONE')return {index:100,label:'No FX',base:null,cur:null};const cadB=janObs('DEXCAUS',y),cadC=obsAt('DEXCAUS',monthEnd(month));if(!cadB||!cadC)return null;if(currency==='USD')return {index:cadC[1]/cadB[1]*100,label:'USD/CAD',base:cadB,cur:cadC,ids:['DEXCAUS']};const twdB=janObs('DEXTAUS',y),twdC=obsAt('DEXTAUS',monthEnd(month));if(!twdB||!twdC)return null;const b=cadB[1]/twdB[1],c=cadC[1]/twdC[1];return {index:c/b*100,label:'CAD/TWD cross',base:[cadB[0],b],cur:[cadC[0],c],ids:['DEXCAUS','DEXTAUS']}}
function ocean(month){const p=idx('PCU4831114831115',month);if(!p)return null;const w=meta('DREWRY_WCI'),y=month.slice(0,4);if(!w?.data?.length)return {...p,label:'BLS deep-sea freight PPI',mode:'PPI'};const yr=w.data.filter(x=>x[0].startsWith(y));if(!yr.length)return {...p,label:'BLS deep-sea freight PPI',mode:'PPI'};const first=yr[0],cur=obsAt('DREWRY_WCI',monthEnd(month));if(!cur||toDate(cur[0])<toDate(first[0]))return {...p,label:'BLS deep-sea freight PPI',mode:'PPI'};const pb=janObs('PCU4831114831115',y),bridge=obsAt('PCU4831114831115',toDate(first[0]));if(!pb||!bridge)return {...p,label:'BLS deep-sea freight PPI',mode:'PPI'};const ppiBridge=bridge[1]/pb[1]*100,wciOwn=cur[1]/first[1]*100;return {index:ppiBridge*wciOwn/100,base:pb,cur,label:'BLS PPI → Drewry chain-link',mode:'CHAIN',ppiBridge,wciOwn,first,bridge}}
function tariffRate(month){const d=monthEnd(month).getTime(),d25=Date.parse('2025-03-12T00:00:00Z'),d50=Date.parse('2025-06-04T00:00:00Z');return d<d25?0:d<d50?25:50}
function current(){const route=document.getElementById('v6Route')?.value||'IMPORT_TWD',currency=document.getElementById('v6Fx')?.value||(route==='IMPORT_TWD'?'TWD':route==='IMPORT_USD'?'USD':'NONE');const enabled={};document.querySelectorAll('[data-factor]').forEach(x=>enabled[x.dataset.factor]=x.checked);return {month:document.getElementById('v6Month')?.value||'2026-08',route,currency,material:document.getElementById('v6Material')?.value||'WPU101',freight:document.getElementById('v6Freight')?.value||(route==='MFG_CA'?'TRUCK':'COMPOSITE'),enabled}}
function weights(route){if(route==='MFG_CA')return {material:75,energy:20,ocean:0,truck:5,tariff:false};return {material:100,energy:0,ocean:8,truck:4,tariff:true}}
function selected(c){const m=idx(c.material,c.month),f=fx(c.currency,c.month),o=ocean(c.month),t=idx('WPU3012',c.month),e=idx('QC_NATGAS',c.month)||idx('DHHNGSP',c.month);return {material:m?.index??100,fx:f?.index??100,ocean:o?.index??100,truck:t?.index??100,energy:e?.index??100,tariff:tariffRate(c.month),meta:{material:m,fx:f,ocean:o,truck:t,energy:e}}}
function effective(c,s,janTar){return {material:c.enabled.material===false?100:s.material,fx:c.enabled.fx===false?100:s.fx,ocean:c.enabled.ocean===false?100:s.ocean,truck:c.enabled.truck===false?100:s.truck,energy:c.enabled.energy===false?100:s.energy,tariff:c.enabled.tariff===false?janTar:s.tariff}}
function parts(v,c,w){const goods=w.material*(v.material/100)*(v.fx/100),energy=w.energy*(v.energy/100);let ocean=0,truck=0;if(c.freight==='COMPOSITE'){ocean=w.ocean*(v.ocean/100);truck=w.truck*(v.truck/100)}else if(c.freight==='TRUCK'){truck=(w.ocean+w.truck)*(v.truck/100)}else if(c.freight==='OCEAN'){ocean=(w.ocean+w.truck)*(v.ocean/100)}else{ocean=w.ocean;truck=w.truck}const duty=w.tariff?goods*(v.tariff/100):0;return {goods,energy,ocean,truck,freight:ocean+truck,duty,total:goods+energy+ocean+truck+duty}}
const order=['material','fx','tariff','ocean','truck','energy'],names={material:'Material',fx:'FX',tariff:'Tariff',ocean:'Ocean freight',truck:'Trucking',energy:'Energy / conversion'};
function calc(c){const w=weights(c.route),janTar=tariffRate(c.month.slice(0,4)+'-01'),s=selected(c),target=effective(c,s,janTar),base={material:100,fx:100,ocean:100,truck:100,energy:100,tariff:janTar},bp=parts(base,c,w),steps=[];let cur={...base},prev=bp.total;for(const k of order){cur[k]=target[k];const np=parts(cur,c,w),pts=(np.total-prev)/bp.total*100;steps.push({key:k,points:pts,to:np.total/bp.total*100,index:target[k]});prev=np.total}const final=prev/bp.total*100;const freightBase=bp.freight;const fp=parts({...base,ocean:target.ocean,truck:target.truck},c,w),freightIndex=freightBase?fp.freight/freightBase*100:100,freightShare=bp.total?freightBase/bp.total*100:0,freightContribution=bp.total?(fp.freight-freightBase)/bp.total*100:0;return {c,w,s,target,base,bp,steps,final,freightIndex,freightShare,freightContribution,fp}}
function cls(v){return v>.005?'v9-pos':v<-.005?'v9-neg':'v9-zero'}
function waterfall(d){const vals=[100,...d.steps.map(x=>x.to),d.final],min=Math.min(94,...vals)-1,max=Math.max(106,...vals)+1,W=900,H=270,L=45,R=18,T=26,B=62,pw=W-L-R,ph=H-T-B,y=v=>T+(max-v)/(max-min)*ph,bw=82,gap=26;let x=L,out=`<line class="grid" x1="${L}" x2="${W-R}" y1="${y(100)}" y2="${y(100)}"/><text x="${L}" y="${y(100)-7}">Jan 1 = 100</text><rect class="start" x="${x}" y="${y(100)}" width="${bw}" height="${Math.max(3,y(min)-y(100))}"/><text class="val" x="${x+bw/2}" y="${y(100)-8}" text-anchor="middle">100.0</text><text x="${x+bw/2}" y="${H-25}" text-anchor="middle">JAN BASE</text>`;let prev=100;x+=bw+gap;for(const s of d.steps){const yy=Math.min(y(prev),y(s.to)),hh=Math.max(3,Math.abs(y(prev)-y(s.to))),bar=Math.abs(s.points)<.005?'flat':s.points>0?'up':'down';out+=`<line class="conn" x1="${x-gap}" x2="${x}" y1="${y(prev)}" y2="${y(prev)}"/><rect class="${bar}" x="${x}" y="${Math.abs(s.points)<.005?y(prev)-2:yy}" width="${bw}" height="${Math.abs(s.points)<.005?4:hh}"/><text class="val" x="${x+bw/2}" y="${(Math.abs(s.points)<.005?y(prev)-2:yy)-7}" text-anchor="middle">${s.points>=0?'+':''}${s.points.toFixed(1)}</text><text x="${x+bw/2}" y="${H-29}" text-anchor="middle">${names[s.key]}</text><text class="idx" x="${x+bw/2}" y="${H-17}" text-anchor="middle">idx ${Number.isFinite(s.index)?s.index.toFixed(1):'—'}</text>`;prev=s.to;x+=bw+gap}out+=`<line class="conn" x1="${x-gap}" x2="${x}" y1="${y(prev)}" y2="${y(prev)}"/><rect class="total" x="${x}" y="${y(d.final)}" width="${bw}" height="${Math.max(3,y(min)-y(d.final))}"/><text class="val" x="${x+bw/2}" y="${y(d.final)-8}" text-anchor="middle">${d.final.toFixed(1)}</text><text x="${x+bw/2}" y="${H-25}" text-anchor="middle">TOTAL INDEX</text>`;return `<svg class="v9-waterfall" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">${out}</svg>`}
function coverage(d){const o=d.s.meta.ocean,first=meta('DREWRY_WCI')?.data?.[0]?.[0];if(!o)return `<div class="v9-coverage warn">Ocean freight source unavailable for this period. The model holds that component at 100 and the audit trail identifies the missing source.</div>`;if(o.mode==='PPI')return `<div class="v9-coverage">Selected period uses <strong>BLS Deep Sea Freight Services PPI</strong>. Drewry WCI observations in this dashboard begin ${first||'later'}, so earlier periods deliberately use BLS rather than showing blanks.</div>`;return `<div class="v9-coverage">Ocean freight is chain-linked: BLS deep-sea PPI covers January through ${o.first[0]}, then Drewry WCI carries the series to ${o.cur[0]}.</div>`}
function rows(d){return d.steps.map(s=>{let treatment='Sequential bridge contribution';if(s.key==='ocean'&&d.c.freight==='TRUCK')treatment='Not used — trucking-only freight mode';if(s.key==='truck'&&d.c.freight==='OCEAN')treatment='Not used — ocean-only freight mode';if((s.key==='ocean'||s.key==='truck')&&d.c.freight==='NONE')treatment='Held at January';return `<tr><td><strong>${names[s.key]}</strong></td><td>${Number.isFinite(s.index)?s.index.toFixed(1):'—'}</td><td class="${cls(s.points)}">${s.points>=0?'+':''}${s.points.toFixed(2)} pts</td><td>${treatment}<small>Contribution = change in modeled cost ÷ January total cost.</small></td></tr>`}).join('')}
function extendMonths(){const sel=document.getElementById('v6Month');if(!sel||sel.dataset.v9extended)return;sel.dataset.v9extended='1';const starts=['WPU101','WPU3012','PCU4831114831115','DEXCAUS'].map(id=>meta(id)?.data?.[0]?.[0]).filter(Boolean).sort();const start=(TD.start&&TD.start<'2021-01-01'?TD.start:starts[0]||'2021-01-01').slice(0,7),end=new Date().toISOString().slice(0,7);const existing=new Set([...sel.options].map(o=>o.value)),add=[];let [y,m]=start.split('-').map(Number),[ey,em]=end.split('-').map(Number);while(y<ey||(y===ey&&m<=em)){const v=`${y}-${String(m).padStart(2,'0')}`;if(!existing.has(v))add.push(v);m++;if(m===13){m=1;y++}}for(const v of add.reverse()){const o=document.createElement('option');o.value=v;o.textContent=v;sel.insertBefore(o,sel.firstChild)} }
function render(){if(!title.textContent.includes('Imports & Trade'))return;extendMonths();const box=document.getElementById('v6Model');if(!box)return;const c=current(),sig=JSON.stringify(c);if(box.dataset.v9sig===sig&&box.querySelector('.v9-model'))return;const d=calc(c),freightMath=d.freightShare?`(${d.freightIndex.toFixed(1)} − 100) × ${d.freightShare.toFixed(1)}% = ${d.freightContribution>=0?'+':''}${d.freightContribution.toFixed(1)} total-cost index points`:'No freight cost in January baseline';box.dataset.v9sig=sig;box.innerHTML=`<div class="v9-model"><div class="v9-bridge-head"><div><h2>Total Landed-Cost Bridge</h2><p>Bars are <strong>contributions to the total landed-cost index</strong>. Component indices such as freight 128.9 are shown separately and are converted by their January cost share.</p></div><span class="v9-badge">JAN 1 ${c.month.slice(0,4)} = 100</span></div><div class="v9-explain-grid"><div><span>Freight component index</span><strong>${d.freightIndex.toFixed(1)}</strong><small>Freight-only movement versus January.</small></div><div><span>January freight share</span><strong>${d.freightShare.toFixed(1)}%</strong><small>${d.bp.freight.toFixed(1)} freight units ÷ ${d.bp.total.toFixed(1)} total January cost units.</small></div><div><span>Freight contribution</span><strong>${d.freightContribution>=0?'+':''}${d.freightContribution.toFixed(1)} pts</strong><small>What freight adds to the total cost index.</small></div><div class="accent"><span>Total landed-cost index</span><strong>${d.final.toFixed(1)}</strong><small>January total landed cost = 100.</small></div></div><div class="v9-equation"><strong>Why freight ${d.freightIndex.toFixed(1)} does not mean total cost ${d.freightIndex.toFixed(1)}:</strong> ${freightMath}. The bridge therefore shows about ${d.freightContribution>=0?'+':''}${d.freightContribution.toFixed(1)} points from freight, not +${(d.freightIndex-100).toFixed(1)} points.</div>${waterfall(d)}<div class="v9-table-wrap"><table class="v9-table"><thead><tr><th>Driver</th><th>Source / derived index</th><th>Contribution to total</th><th>Bridge treatment</th></tr></thead><tbody>${rows(d)}</tbody></table></div>${coverage(d)}<div class="v9-audit-callout"><span><strong>Baseline correction applied:</strong> every non-tariff driver is exactly 100 at the January source observation. Daily FX no longer uses January month-end as a hidden bridge baseline.</span><button id="v9AuditJump">View source-data audit trail</button></div></div>`;document.getElementById('v9AuditJump')?.addEventListener('click',()=>document.querySelector('.v8-audit-panel')?.scrollIntoView({behavior:'smooth',block:'start'}))}
let timer;function schedule(){clearTimeout(timer);timer=setTimeout(render,35)}
new MutationObserver(schedule).observe(title,{childList:true,subtree:true,characterData:true});
new MutationObserver(schedule).observe(app,{childList:true,subtree:true});
app.addEventListener('change',e=>{if(e.target?.id?.startsWith('v6')||e.target?.matches?.('[data-factor]'))schedule()});
app.addEventListener('click',e=>{if(e.target?.matches?.('[data-solo],#v6All,#v6None'))setTimeout(schedule,20)});
schedule();
})();