(()=>{
const app=document.getElementById('app'),title=document.getElementById('viewTitle');
const TD=window.FI_TREND_DATA||{series:{}},D=window.FI_DATA||{},IO=window.FI_IMPORT_ORIGINS||{};
if(!app||!title)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toDate=s=>new Date(s+'T00:00:00Z');
const monthEnd=m=>{const [y,mo]=m.split('-').map(Number);return new Date(Date.UTC(y,mo,0));};
const janStart=y=>new Date(Date.UTC(+y,0,1));
function series(id){return TD.series?.[id]||null}
function obsAt(id,end){const s=series(id);if(!s?.data?.length)return null;let best=null;for(const p of s.data){const d=toDate(p[0]);if(d<=end)best=p;else break}return best}
function janObs(id,y){const s=series(id);if(!s?.data?.length)return null;const js=janStart(y),je=new Date(Date.UTC(+y,0,31));let prior=null,first=null;for(const p of s.data){const d=toDate(p[0]);if(d<js)prior=p;else if(d<=je&&!first)first=p;else if(d>je)break}return first||prior}
function idx(id,month){const y=month.slice(0,4),b=janObs(id,y),c=obsAt(id,monthEnd(month));if(!b||!c||!b[1])return null;return {index:c[1]/b[1]*100,base:b,cur:c,source:id,label:series(id)?.name||id}}
function fx(currency,month){const y=month.slice(0,4);if(currency==='NONE')return {index:100,base:null,cur:null,source:null,label:'No FX'};const cb=janObs('DEXCAUS',y),cc=obsAt('DEXCAUS',monthEnd(month));if(!cb||!cc)return null;if(currency==='USD')return {index:cc[1]/cb[1]*100,base:cb,cur:cc,source:'DEXCAUS',label:'USD/CAD'};const tb=janObs('DEXTAUS',y),tc=obsAt('DEXTAUS',monthEnd(month));if(!tb||!tc)return null;const bv=cb[1]/tb[1],cv=cc[1]/tc[1];return {index:cv/bv*100,base:[cb[0],bv],cur:[cc[0],cv],source:'DEXCAUS+DEXTAUS',label:'CAD/TWD cross'} }
function ocean(month){const p=idx('PCU4831114831115',month),w=series('DREWRY_WCI'),y=month.slice(0,4);if(!p)return null;if(!w?.data?.length)return {...p,label:'Deep-sea freight PPI'};const yr=w.data.filter(x=>x[0].startsWith(y));if(!yr.length)return {...p,label:'Deep-sea freight PPI'};const first=yr[0],cur=obsAt('DREWRY_WCI',monthEnd(month));if(!cur||toDate(cur[0])<toDate(first[0]))return {...p,label:'Deep-sea freight PPI'};const pb=janObs('PCU4831114831115',y),bridge=obsAt('PCU4831114831115',toDate(first[0]));if(!pb||!bridge)return {...p,label:'Deep-sea freight PPI'};const bridgeIdx=bridge[1]/pb[1]*100;return {index:bridgeIdx*(cur[1]/first[1]),base:pb,cur,source:'DREWRY_WCI',label:'Drewry WCI chain-linked to deep-sea freight PPI'} }
function tariffRate(month){const d=monthEnd(month).getTime(),d25=Date.parse('2025-03-12T00:00:00Z'),d50=Date.parse('2025-06-04T00:00:00Z');return d<d25?0:d<d50?25:50}
function fmt(id,v){if(v==null)return '—';const u=series(id)?.units||'';if(u.includes('USD per 40ft'))return '$'+Math.round(v).toLocaleString()+'/40ft';if(u.includes('USD per metric ton'))return '$'+Math.round(v).toLocaleString()+'/t';if(u.includes('cents per cubic'))return Number(v).toFixed(2)+'¢/m³';if(u.includes('CAD per USD'))return Number(v).toFixed(4);if(u.includes('TWD per USD'))return Number(v).toFixed(2);return Number(v).toLocaleString(undefined,{maximumFractionDigits:2})}
function openSource(id){const modal=document.getElementById('sourceModal'),input=document.getElementById('sourceSearch');if(!modal||!input)return;modal.classList.add('open');modal.setAttribute('aria-hidden','false');input.value=id;input.dispatchEvent(new Event('input',{bubbles:true}))}
function sourceBtn(id,label){return `<button class="v6-src" data-v6-source="${esc(id)}">${esc(label||id)}</button>`}
function bindSources(root){root.querySelectorAll('[data-v6-source]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',e=>{e.stopPropagation();openSource(b.dataset.v6Source)})})}
if(D.sources&&IO?.sourceUrl){D.sources.US_FASTENER_IMPORTS={title:'U.S. Fastener Import Origins — HS 7318',publisher:'U.S. Census Bureau',date:IO.asOf||'Latest available',period:IO.asOf?`YTD through ${IO.asOf}`:'Current',class:'fact',kind:'Government trade data',url:IO.sourceUrl,usedFor:'U.S. import composition by country of origin for HS 7318',notes:'General Imports, value basis, aggregated from Census Port HS6 country-by-port records. This is import composition, not total U.S. market penetration.'}}
const routes={IMPORT_USD:{label:'Imported — USD supplier',currency:'USD',material:100,energy:0,ocean:8,truck:4,tariff:true},IMPORT_TWD:{label:'Imported — Taiwan / TWD',currency:'TWD',material:100,energy:0,ocean:8,truck:4,tariff:true},MFG_CA:{label:'Manufactured — Canada',currency:'NONE',material:75,energy:20,ocean:0,truck:5,tariff:false}};
let st={month:'2026-08',route:'IMPORT_TWD',currency:'TWD',materialSeries:'WPU101',freightMode:'COMPOSITE',enabled:{material:true,fx:true,tariff:true,ocean:true,truck:true,energy:true},weights:{...routes.IMPORT_TWD}};
function setRoute(r){const d=routes[r];st.route=r;st.currency=d.currency;st.weights={...d};st.freightMode=r==='MFG_CA'?'TRUCK':'COMPOSITE'}
function raw(month){return {material:idx(st.materialSeries,month)||{index:100},fx:fx(st.currency,month)||{index:100},ocean:ocean(month)||{index:100},truck:idx('WPU3012',month)||{index:100},energy:idx('QC_NATGAS',month)||idx('DHHNGSP',month)||{index:100},tariff:tariffRate(month)}}
function effective(base,selected){return {material:st.enabled.material?selected.material.index:base.material.index,fx:st.enabled.fx?selected.fx.index:base.fx.index,ocean:st.enabled.ocean?selected.ocean.index:base.ocean.index,truck:st.enabled.truck?selected.truck.index:base.truck.index,energy:st.enabled.energy?selected.energy.index:base.energy.index,tariff:st.enabled.tariff?selected.tariff:base.tariff}}
function cost(v,month){const w=st.weights,goods=w.material*(v.material/100)*(v.fx/100),energy=w.energy*(v.energy/100);let freight=0;if(st.freightMode==='COMPOSITE')freight=w.ocean*(v.ocean/100)+w.truck*(v.truck/100);else if(st.freightMode==='TRUCK')freight=(w.ocean+w.truck)*(v.truck/100);else if(st.freightMode==='OCEAN')freight=(w.ocean+w.truck)*(v.ocean/100);else freight=w.ocean+w.truck;const duty=w.tariff?goods*(v.tariff/100):0;return {goods,energy,freight,duty,total:goods+energy+freight+duty}}
const order=['material','fx','tariff','ocean','truck','energy'];
const names={material:'Material',fx:'FX',tariff:'Tariff',ocean:'Ocean freight',truck:'Trucking',energy:'Energy / conversion'};
function calc(){const y=st.month.slice(0,4),baseMonth=y+'-01',braw=raw(baseMonth),sraw=raw(st.month);const b={material:braw.material.index,fx:braw.fx.index,ocean:braw.ocean.index,truck:braw.truck.index,energy:braw.energy.index,tariff:braw.tariff};const target=effective(braw,sraw);const bc=cost(b,baseMonth),steps=[];let cur={...b},prev=bc.total;for(const k of order){cur[k]=target[k];const next=cost(cur,st.month).total;steps.push({key:k,points:(next-prev)/bc.total*100,to:next/bc.total*100,included:st.enabled[k],applicable:!(k==='ocean'&&st.freightMode==='TRUCK')&&!(k==='truck'&&st.freightMode==='OCEAN')&&!(k==='ocean'||k==='truck')||true});prev=next}return {baseMonth,braw,sraw,baseCost:bc,steps,final:prev/bc.total*100,target}}
function wf(dec){const vals=[100,...dec.steps.map(x=>x.to),dec.final],min=Math.min(92,...vals)-2,max=Math.max(108,...vals)+2,W=820,H=270,left=44,top=20,bottom=52,ph=H-top-bottom,y=v=>top+(max-v)/(max-min)*ph,bw=68,gap=28;let x=left,b=`<line x1="${left}" x2="${W-12}" y1="${y(100)}" y2="${y(100)}" class="v6-base"/><text x="${left}" y="${y(100)-6}" class="v6-axis">Jan 1 = 100</text><rect x="${x}" y="${y(100)}" width="${bw}" height="${Math.max(2,y(min)-y(100))}" class="v6-start"/><text x="${x+bw/2}" y="${y(100)-7}" text-anchor="middle" class="v6-val">100.0</text><text x="${x+bw/2}" y="${H-20}" text-anchor="middle" class="v6-label">JAN BASE</text>`;let prev=100;x+=bw+gap;for(const s of dec.steps){const yy=Math.min(y(prev),y(s.to)),hh=Math.max(3,Math.abs(y(prev)-y(s.to))),zero=Math.abs(s.points)<.005;b+=`<line x1="${x-gap}" x2="${x}" y1="${y(prev)}" y2="${y(prev)}" class="v6-conn"/><rect x="${x}" y="${zero?y(prev)-2:yy}" width="${bw}" height="${zero?4:hh}" class="v6-change ${s.points>=0?'up':'down'} ${s.included?'':'excluded'}"/><text x="${x+bw/2}" y="${(zero?y(prev)-2:yy)-6}" text-anchor="middle" class="v6-val">${s.points>=0?'+':''}${s.points.toFixed(1)}</text><text x="${x+bw/2}" y="${H-20}" text-anchor="middle" class="v6-label">${names[s.key]}</text>`;prev=s.to;x+=bw+gap}b+=`<line x1="${x-gap}" x2="${x}" y1="${y(prev)}" y2="${y(prev)}" class="v6-conn"/><rect x="${x}" y="${y(dec.final)}" width="${bw}" height="${Math.max(3,y(min)-y(dec.final))}" class="v6-total"/><text x="${x+bw/2}" y="${y(dec.final)-7}" text-anchor="middle" class="v6-val">${dec.final.toFixed(1)}</text><text x="${x+bw/2}" y="${H-20}" text-anchor="middle" class="v6-label">COST INDEX</text>`;return `<svg class="v6-waterfall" viewBox="0 0 ${W} ${H}">${b}</svg>`}
function monthOptions(){let out=[],d=new Date(Date.UTC(2021,0,1)),end=new Date(Date.UTC(2026,7,1));while(d<=end){const m=d.toISOString().slice(0,7);out.push(`<option value="${m}" ${m===st.month?'selected':''}>${m}</option>`);d.setUTCMonth(d.getUTCMonth()+1)}return out.join('')}
function factorControls(){return `<div class="v6-factor-head"><strong>Cost-driver isolation</strong><span>Unchecked = hold that driver at its January baseline.</span><button id="v6All">All</button><button id="v6None">None</button></div><div class="v6-factors">${order.map(k=>`<label class="v6-factor"><input type="checkbox" data-factor="${k}" ${st.enabled[k]?'checked':''}><span>${names[k]}</span><button type="button" data-solo="${k}">Solo</button></label>`).join('')}</div>`}
function controls(){return `<div class="v6-controls"><label>Month<select id="v6Month">${monthOptions()}</select></label><label>Supply mode<select id="v6Route"><option value="IMPORT_USD" ${st.route==='IMPORT_USD'?'selected':''}>Imported — USD supplier</option><option value="IMPORT_TWD" ${st.route==='IMPORT_TWD'?'selected':''}>Imported — Taiwan / TWD</option><option value="MFG_CA" ${st.route==='MFG_CA'?'selected':''}>Manufactured — Canada</option></select></label><label>FX<select id="v6Fx"><option value="NONE" ${st.currency==='NONE'?'selected':''}>None</option><option value="USD" ${st.currency==='USD'?'selected':''}>USD → CAD</option><option value="TWD" ${st.currency==='TWD'?'selected':''}>TWD → CAD cross</option></select></label><label>Material benchmark<select id="v6Material"><option value="WPU101" ${st.materialSeries==='WPU101'?'selected':''}>Iron & Steel PPI</option><option value="WPU10" ${st.materialSeries==='WPU10'?'selected':''}>Metals & Metal Products PPI</option><option value="PZINCUSDM" ${st.materialSeries==='PZINCUSDM'?'selected':''}>Zinc</option><option value="PNICKUSDM" ${st.materialSeries==='PNICKUSDM'?'selected':''}>Nickel</option></select></label><label>Freight driver<select id="v6Freight"><option value="COMPOSITE" ${st.freightMode==='COMPOSITE'?'selected':''}>Ocean + trucking</option><option value="TRUCK" ${st.freightMode==='TRUCK'?'selected':''}>Trucking index only</option><option value="OCEAN" ${st.freightMode==='OCEAN'?'selected':''}>Ocean index only</option><option value="NONE" ${st.freightMode==='NONE'?'selected':''}>Hold freight at Jan</option></select></label></div>${factorControls()}`}
function row(name,obj,index,step,srcId){const b=obj?.base,c=obj?.cur;return `<tr><td>${name}</td><td>${step?.included?'Included':'Held at Jan'}</td><td>${b?esc(b[0]):'—'}</td><td>${b?esc(fmt(srcId,b[1])):'—'}</td><td>${c?esc(c[0]):'—'}</td><td>${c?esc(fmt(srcId,c[1])):'—'}</td><td>${index?.toFixed?index.toFixed(1):'—'}</td><td>${step?(step.points>=0?'+':'')+step.points.toFixed(1):'—'}</td></tr>`}
function modelBody(){const dec=calc(),sm=Object.fromEntries(dec.steps.map(x=>[x.key,x])),s=dec.sraw;return `<div class="v6-kpis"><div><span>Selected cost index</span><strong>${dec.final.toFixed(1)}</strong><small>Jan 1 ${st.month.slice(0,4)} = 100</small></div><div><span>Active drivers</span><strong>${Object.values(st.enabled).filter(Boolean).length}/6</strong><small>Use Solo to isolate one factor</small></div><div><span>Freight basis</span><strong>${st.freightMode==='COMPOSITE'?'Ocean + truck':st.freightMode==='TRUCK'?'Truck only':st.freightMode==='OCEAN'?'Ocean only':'Held'}</strong><small>Index selection</small></div></div>${wf(dec)}<div class="v6-table-wrap"><table class="v6-table"><thead><tr><th>Driver</th><th>Status</th><th>Jan obs.</th><th>Jan value</th><th>Selected obs.</th><th>Selected value</th><th>Index</th><th>Impact</th></tr></thead><tbody>${row('Material',s.material,s.material.index,sm.material,st.materialSeries)}${row('FX',s.fx,s.fx.index,sm.fx,s.fx.source?.split('+')[0]||'DEXCAUS')}<tr><td>Tariff</td><td>${sm.tariff.included?'Included':'Held at Jan'}</td><td>${dec.baseMonth}</td><td>${dec.braw.tariff}%</td><td>${st.month}</td><td>${s.tariff}%</td><td>Step</td><td>${sm.tariff.points>=0?'+':''}${sm.tariff.points.toFixed(1)}</td></tr>${row('Ocean freight',s.ocean,s.ocean.index,sm.ocean,s.ocean.source||'PCU4831114831115')}${row('Trucking',s.truck,s.truck.index,sm.truck,'WPU3012')}${row('Energy / conversion',s.energy,s.energy.index,sm.energy,s.energy.source||'QC_NATGAS')}</tbody></table></div><div class="v6-method"><strong>Isolation rule:</strong> removing a driver does not remove the January cost component from the denominator; it holds that driver at its January level. This preserves a consistent Jan=100 base while showing only the movements you choose.</div>`}
function importMix(){const rows=IO.countries||[];if(!rows.length)return `<div class="v6-empty">Official Census import-origin data is being refreshed. The dashboard will populate this panel from the latest available Port HS6 file.</div>`;const top=rows.slice(0,8),top5=rows.slice(0,5),other=100-top5.reduce((a,r)=>a+r.share,0),segments=[...top5.map(r=>({name:r.name,share:r.share})),{name:'Other',share:other}],top3=rows.slice(0,3).reduce((a,r)=>a+r.share,0),total=IO.totalValue||0;return `<div class="v6-import-kpis"><div><span>YTD import value</span><strong>$${(total/1e9).toFixed(2)}B</strong><small>HS 7318 general imports</small></div><div><span>Top 3 concentration</span><strong>${top3.toFixed(1)}%</strong><small>of import value</small></div><div><span>Countries</span><strong>${rows.length}</strong><small>reported origins</small></div></div><div class="v6-stackbar">${segments.map((r,i)=>`<span style="width:${Math.max(.4,r.share)}%" title="${esc(r.name)} ${r.share.toFixed(1)}%"><i>${r.share>=7?esc(r.name):''}</i></span>`).join('')}</div><div class="v6-origin-list">${top.map((r,i)=>`<div class="v6-origin-row"><b>${i+1}</b><span class="name">${esc(r.name)}</span><div class="bar"><i style="width:${r.share}%"></i></div><strong>${r.share.toFixed(1)}%</strong><small>$${(r.value/1e6).toFixed(0)}M</small></div>`).join('')}</div><div class="v6-region-row">${(IO.regions||[]).slice(0,4).map(r=>`<span><b>${esc(r.name)}</b>${r.share.toFixed(1)}%</span>`).join('')}</div><div class="v6-method">Latest available Census period: <strong>${esc(IO.asOf)}</strong>. Value basis, HS 7318 only. This shows <strong>where U.S. imports come from</strong>; it is not the share of imports in total U.S. fastener consumption. ${sourceBtn('US_FASTENER_IMPORTS','Census source')}</div>`}
function render(){if(!title.textContent.includes('Imports & Trade')){app.classList.remove('v6-trade-active');return}app.classList.add('v6-trade-active');if(app.querySelector('.v6-trade-layer'))return;const wrap=document.createElement('div');wrap.className='v6-trade-layer';wrap.innerHTML=`<section class="v6-panel v6-span-8"><div class="v6-head"><div><h2>Indexed Landed Cost — Factor Isolation Lab</h2><p>Select the month, route, freight basis and exactly which cost movements you want included.</p></div><span>DERIVED</span></div>${controls()}<div id="v6Model">${modelBody()}</div></section><section class="v6-panel v6-span-4"><div class="v6-head"><div><h2>U.S. Fastener Import Origin Mix</h2><p>Official U.S. Census HS 7318 import composition by country of origin.</p></div><span>FACT</span></div>${importMix()}</section>`;const anchor=app.querySelector('.dashboard-grid');app.insertBefore(wrap,anchor||app.firstChild);bind(wrap);bindSources(wrap)}
function bind(root){const upd=()=>{const body=root.querySelector('#v6Model');if(body)body.innerHTML=modelBody();bindSources(root)};root.querySelector('#v6Month')?.addEventListener('change',e=>{st.month=e.target.value;upd()});root.querySelector('#v6Route')?.addEventListener('change',e=>{setRoute(e.target.value);root.querySelector('#v6Fx').value=st.currency;root.querySelector('#v6Freight').value=st.freightMode;upd()});root.querySelector('#v6Fx')?.addEventListener('change',e=>{st.currency=e.target.value;upd()});root.querySelector('#v6Material')?.addEventListener('change',e=>{st.materialSeries=e.target.value;upd()});root.querySelector('#v6Freight')?.addEventListener('change',e=>{st.freightMode=e.target.value;upd()});root.querySelectorAll('[data-factor]').forEach(x=>x.addEventListener('change',e=>{st.enabled[e.target.dataset.factor]=e.target.checked;upd()}));root.querySelectorAll('[data-solo]').forEach(b=>b.addEventListener('click',()=>{Object.keys(st.enabled).forEach(k=>st.enabled[k]=k===b.dataset.solo);root.querySelectorAll('[data-factor]').forEach(x=>x.checked=st.enabled[x.dataset.factor]);upd()}));root.querySelector('#v6All')?.addEventListener('click',()=>{Object.keys(st.enabled).forEach(k=>st.enabled[k]=true);root.querySelectorAll('[data-factor]').forEach(x=>x.checked=true);upd()});root.querySelector('#v6None')?.addEventListener('click',()=>{Object.keys(st.enabled).forEach(k=>st.enabled[k]=false);root.querySelectorAll('[data-factor]').forEach(x=>x.checked=false);upd()})}
let queued=false;function schedule(){if(queued)return;queued=true;setTimeout(()=>{queued=false;render()},0)}
new MutationObserver(schedule).observe(title,{childList:true,subtree:true,characterData:true});
new MutationObserver(schedule).observe(app,{childList:true});
schedule();
})();
