(()=>{
const app=document.getElementById('app'),title=document.getElementById('viewTitle');if(!app||!title)return;const NS='http://www.w3.org/2000/svg';
const customers=[
 {company:'Caterpillar',site:'Decatur facility',place:'Decatur, IL',lat:39.84,lon:-88.95,detail:'Major construction/resource equipment manufacturing',src:'https://www.caterpillar.com/en/company/about-caterpillar/global-footprint/united-states.html'},
 {company:'Caterpillar',site:'East Peoria facility',place:'East Peoria, IL',lat:40.67,lon:-89.58,detail:'Construction/resource equipment and component manufacturing',src:'https://www.caterpillar.com/en/company/about-caterpillar/global-footprint/united-states.html'},
 {company:'Caterpillar',site:'Mapleton facility',place:'Mapleton, IL',lat:40.57,lon:-89.73,detail:'Component and manufacturing footprint',src:'https://www.caterpillar.com/en/company/about-caterpillar/global-footprint/united-states.html'},
 {company:'Caterpillar',site:'Lafayette facility',place:'Lafayette, IN',lat:40.42,lon:-86.88,detail:'Energy & Transportation manufacturing',src:'https://www.caterpillar.com/en/investors/financial-information/proxy-materials/annual-report-to-shareholders.html'},
 {company:'Caterpillar',site:'South Milwaukee facility',place:'South Milwaukee, WI',lat:42.91,lon:-87.86,detail:'Resource Industries manufacturing',src:'https://www.caterpillar.com/en/investors/financial-information/proxy-materials/annual-report-to-shareholders.html'},
 {company:'John Deere',site:'Waterloo Tractor Operations',place:'Waterloo, IA',lat:42.49,lon:-92.34,detail:'Tractor, engine, drivetrain and foundry operations',src:'https://www.deere.com/en/stories/featured/waterloo-employee-callbacks/'},
 {company:'John Deere',site:'Davenport Works',place:'Davenport, IA',lat:41.52,lon:-90.58,detail:'Construction equipment manufacturing',src:'https://johndeeretours.deere.com/Info.aspx?EventID=14'},
 {company:'John Deere',site:'Dubuque Works',place:'Dubuque, IA',lat:42.50,lon:-90.66,detail:'Construction and forestry equipment manufacturing',src:'https://johndeeretours.deere.com/Info.aspx?EventID=15'},
 {company:'John Deere',site:'Des Moines Works',place:'Ankeny, IA',lat:41.73,lon:-93.60,detail:'Agricultural equipment manufacturing',src:'https://johndeeretours.deere.com/Info.aspx?EventID=24'},
 {company:'John Deere',site:'Horicon Works',place:'Horicon, WI',lat:43.45,lon:-88.63,detail:'Utility vehicle, lawn tractor and component manufacturing',src:'https://www.deere.com/en-us/our-company/locations/factories/horicon-works'},
 {company:'John Deere',site:'Kernersville campus',place:'Kernersville, NC',lat:36.12,lon:-80.07,detail:'Excavator manufacturing / reshoring investment',src:'https://www.deere.com/en-us/john-deere-news/two-new-us-facilities'}
];
function mode(){const b=[...app.querySelectorAll('.v13-cap-controls button')].find(x=>x.classList.contains('active')),t=(b?.textContent||'').toLowerCase();return t.includes('customer')?'CUSTOMER':t.includes('peer manufacturing')?'MFG':t.includes('peer distribution')?'DIST':'ALL'}
function tooltip(){return document.getElementById('fiGeoTooltip')}
function move(e){const t=tooltip();if(!t)return;t.style.left=Math.min(window.innerWidth-300,e.clientX+14)+'px';t.style.top=Math.min(window.innerHeight-160,e.clientY+14)+'px'}
function show(e,s){const t=tooltip();if(!t)return;t.innerHTML=`<strong>${s.company}</strong><span>${s.site}</span><span>${s.place}</span><span>Customer / OEM manufacturing</span><span>${s.detail}</span><small>Click marker to open public source</small>`;t.classList.add('show');move(e)}
function hide(){tooltip()?.classList.remove('show')}
function addCustomerPoints(svg){const geo=window.FI_GEO_MAP;if(!geo)return;svg.querySelectorAll('.v19-heavy-customer-layer').forEach(x=>x.remove());if(!['ALL','CUSTOMER'].includes(mode()))return;const layer=document.createElementNS(NS,'g');layer.setAttribute('class','v19-heavy-customer-layer');for(const s of customers){const [x,y]=geo.naXY(s.lat,s.lon);if(x<0||x>1000||y<0||y>560)continue;const c=document.createElementNS(NS,'circle');c.setAttribute('cx',x.toFixed(1));c.setAttribute('cy',y.toFixed(1));c.setAttribute('r','8');c.setAttribute('class',s.company==='Caterpillar'?'v19-cat':'v19-deere');const tt=document.createElementNS(NS,'title');tt.textContent=`${s.company} — ${s.site} | ${s.place} | ${s.detail}`;c.appendChild(tt);c.addEventListener('mouseenter',e=>show(e,s));c.addEventListener('mousemove',move);c.addEventListener('mouseleave',hide);c.addEventListener('click',()=>window.open(s.src,'_blank','noopener'));layer.appendChild(c)}svg.appendChild(layer)}
function stableMap(svg,type){const world=type==='world',href=world?'world-map.svg?v=20260815.25':'north-america-map.svg?v=20260815.25',w=1000,h=world?500:560;svg.querySelectorAll('.v19-basemap').forEach(x=>x.remove());const img=document.createElementNS(NS,'image');img.setAttribute('class','v19-basemap');img.setAttribute('x','0');img.setAttribute('y','0');img.setAttribute('width',String(w));img.setAttribute('height',String(h));img.setAttribute('href',href);img.setAttributeNS('http://www.w3.org/1999/xlink','href',href);img.setAttribute('preserveAspectRatio','none');svg.insertBefore(img,svg.firstChild);svg.querySelectorAll('.v14-country-layer,.v13-land').forEach(x=>x.style.display='none')}
function ensureMaps(){app.querySelectorAll('svg.v13-world').forEach(s=>stableMap(s,'world'));app.querySelectorAll('svg.v13-na').forEach(s=>{stableMap(s,'na');addCustomerPoints(s)})}
function val(id,fallback){return document.getElementById(id)?.value||localStorage.getItem(fallback)||''}
function ensureCompareBar(){if(!title.textContent.includes('Imports & Trade'))return;let bar=document.getElementById('v19CompareTop');if(bar)return;const oldS=document.getElementById('v10Start')?.value,start=oldS||localStorage.getItem('fiCostCompareStartDate')||'2026-01-01',oldE=document.getElementById('v10End')?.value,end=oldE||localStorage.getItem('fiCostCompareEndDate')||new Date().toISOString().slice(0,10),rule=document.getElementById('v10ObsRule')?.value||localStorage.getItem('fiCostObsRule')||'NEAREST';bar=document.createElement('section');bar.id='v19CompareTop';bar.className='v19-compare-top';bar.innerHTML=`<div class="v19-compare-copy"><strong>Landed-Cost Comparison Window</strong><span>Select any start and end date. Start = 100. The prior-year comparison for the selected end date is calculated automatically below the bridge.</span></div><label>Start date<input id="v19Start" type="date" min="2019-01-01" max="${end}" value="${start}"></label><span class="v19-arrow">→</span><label>End date<input id="v19End" type="date" min="${start}" max="${new Date().toISOString().slice(0,10)}" value="${end}"></label><label>Source observation<select id="v19Rule"><option value="NEAREST" ${rule==='NEAREST'?'selected':''}>Closest available</option><option value="PRIOR" ${rule==='PRIOR'?'selected':''}>On or before date</option></select></label>`;app.prepend(bar);function sync(which,value){if(which==='start'){localStorage.setItem('fiCostCompareStartDate',value);const x=document.getElementById('v10Start');if(x){x.value=value;x.dispatchEvent(new Event('change',{bubbles:true}))}}if(which==='end'){localStorage.setItem('fiCostCompareEndDate',value);const x=document.getElementById('v10End');if(x){x.value=value;x.dispatchEvent(new Event('change',{bubbles:true}))}}if(which==='rule'){localStorage.setItem('fiCostObsRule',value);const x=document.getElementById('v10ObsRule');if(x){x.value=value;x.dispatchEvent(new Event('change',{bubbles:true}))}}}
 bar.querySelector('#v19Start').addEventListener('change',e=>{bar.querySelector('#v19End').min=e.target.value;sync('start',e.target.value)});bar.querySelector('#v19End').addEventListener('change',e=>{bar.querySelector('#v19Start').max=e.target.value;sync('end',e.target.value)});bar.querySelector('#v19Rule').addEventListener('change',e=>sync('rule',e.target.value))}
function enhance(){ensureCompareBar();ensureMaps()}
let timer;function schedule(){clearTimeout(timer);timer=setTimeout(enhance,90)}new MutationObserver(schedule).observe(app,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});new MutationObserver(schedule).observe(title,{childList:true,subtree:true,characterData:true});app.addEventListener('click',e=>{if(e.target.closest('.v13-cap-controls button'))setTimeout(schedule,120)},true);schedule();
})();