(()=>{
const app=document.getElementById('app'),IO=window.FI_IMPORT_ORIGINS||{};if(!app)return;
let geoPromise=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').toLowerCase().replace(/\([^)]*\)/g,'').replace(/^federal republic of /,'').replace(/\s+/g,' ').trim();
function loadGeo(){if(!geoPromise)geoPromise=fetch('ne-countries.geojson?v=20260815.20',{cache:'force-cache'}).then(r=>{if(!r.ok)throw new Error('Country geometry '+r.status);return r.json()});return geoPromise}
function worldXY(lat,lon){return [(lon+180)/360*1000,(90-lat)/180*500]}
const NA={minLon:-140,maxLon:-50,minLat:14,maxLat:72};
function naXY(lat,lon){return [(lon-NA.minLon)/(NA.maxLon-NA.minLon)*1000,(NA.maxLat-lat)/(NA.maxLat-NA.minLat)*560]}
function ringPath(ring,proj,width){let d='',px=null,count=0;for(const c of ring||[]){const [x,y]=proj(c[1],c[0]);if(!Number.isFinite(x)||!Number.isFinite(y))continue;const jump=px!=null&&Math.abs(x-px)>width*.52;d+=(count===0||jump?'M':'L')+x.toFixed(1)+','+y.toFixed(1);px=x;count++}return count>2?d+'Z':''}
function geomPath(g,proj,width){if(!g)return'';const polys=g.type==='Polygon'?[g.coordinates]:g.type==='MultiPolygon'?g.coordinates:[];return polys.map(poly=>poly.map(r=>ringPath(r,proj,width)).join('')).join('')}
function featName(f){return f?.properties?.NAME_LONG||f?.properties?.ADMIN||f?.properties?.NAME||''}
function topOrigins(){return new Set((IO.countries||[]).slice(0,12).map(r=>norm(r.name)))}
function originMatch(name,set){const n=norm(name);if(set.has(n))return true;for(const x of set){if((n.includes('korea')&&x.includes('korea'))||(n==='germany'&&x.includes('germany'))||(n.includes('taiwan')&&x.includes('taiwan')))return true}return false}
function makeWorldGroup(geo){const origins=topOrigins(),g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('class','v14-country-layer world');for(const f of geo.features||[]){const d=geomPath(f.geometry,worldXY,1000);if(!d)continue;const p=document.createElementNS('http://www.w3.org/2000/svg','path'),name=featName(f);p.setAttribute('d',d);p.setAttribute('class','v14-country'+(originMatch(name,origins)?' origin-country':''));p.setAttribute('fill-rule','evenodd');const t=document.createElementNS('http://www.w3.org/2000/svg','title');t.textContent=name;p.appendChild(t);g.appendChild(p)}return g}
function bboxHitsNA(f){const b=f.bbox;if(!Array.isArray(b)||b.length<4)return true;return !(b[2]<NA.minLon||b[0]>NA.maxLon||b[3]<NA.minLat||b[1]>NA.maxLat)}
function makeNAGroup(geo){const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('class','v14-country-layer na');for(const f of geo.features||[]){if(!bboxHitsNA(f))continue;const d=geomPath(f.geometry,naXY,1000);if(!d)continue;const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',d);p.setAttribute('class','v14-country na-country');p.setAttribute('fill-rule','evenodd');const t=document.createElementNS('http://www.w3.org/2000/svg','title');t.textContent=featName(f);p.appendChild(t);g.appendChild(p)}return g}
function repositionCapacity(svg){svg.querySelectorAll('.v13-cap-point circle').forEach(c=>{const ox=+c.getAttribute('cx'),oy=+c.getAttribute('cy');if(!Number.isFinite(ox)||!Number.isFinite(oy)||c.dataset.v14moved)return;const lon=-130+(ox/1000)*70,lat=60-(oy/560)*45,[nx,ny]=naXY(lat,lon);c.setAttribute('cx',nx.toFixed(1));c.setAttribute('cy',ny.toFixed(1));c.dataset.v14moved='1'});svg.querySelectorAll('.v13-country-label').forEach(x=>x.remove());[['CANADA',57,-103],['UNITED STATES',39,-99],['MEXICO',23,-102]].forEach(([txt,lat,lon])=>{const [x,y]=naXY(lat,lon),t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('class','v14-na-label');t.setAttribute('x',x);t.setAttribute('y',y);t.textContent=txt;svg.appendChild(t)})}
async function upgradeWorld(svg){if(svg.dataset.v14done)return;svg.dataset.v14done='loading';try{const geo=await loadGeo();svg.querySelectorAll('.v13-land,.v14-country-layer').forEach(x=>x.remove());const g=makeWorldGroup(geo),anchor=svg.querySelector('.v13-region,.v13-route,.v13-origin,.v13-dest');svg.insertBefore(g,anchor||svg.firstChild);svg.dataset.v14done='1'}catch(e){svg.dataset.v14done='error';console.error(e)}}
async function upgradeNA(svg){if(svg.dataset.v14done)return;svg.dataset.v14done='loading';try{const geo=await loadGeo();svg.querySelectorAll('.v13-land,.v14-country-layer').forEach(x=>x.remove());const g=makeNAGroup(geo),anchor=svg.querySelector('.v13-country-label,.v13-cap-point');svg.insertBefore(g,anchor||svg.firstChild);repositionCapacity(svg);svg.dataset.v14done='1'}catch(e){svg.dataset.v14done='error';console.error(e)}}
function enhance(){app.querySelectorAll('svg.v13-world').forEach(upgradeWorld);app.querySelectorAll('svg.v13-na').forEach(upgradeNA)}
let timer;function schedule(){clearTimeout(timer);timer=setTimeout(enhance,60)}new MutationObserver(schedule).observe(app,{childList:true,subtree:true});schedule();
})();