(()=>{
const app=document.getElementById('app'),title=document.getElementById('viewTitle');
const TD=window.FI_TREND_DATA||{series:{}},D=window.FI_DATA||{};
if(!app||!title)return;
const toDate=s=>new Date(s+'T00:00:00Z');
const monthEnd=m=>{const [y,mo]=m.split('-').map(Number);return new Date(Date.UTC(y,mo,0));};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function meta(id){return TD.series?.[id]||null}
function obsAt(id,end){const s=meta(id);if(!s?.data?.length)return null;let best=null;for(const p of s.data){const d=toDate(p[0]);if(d<=end)best=p;else break}return best}
function janObs(id,y){const s=meta(id);if(!s?.data?.length)return null;const js=new Date(Date.UTC(+y,0,1)),je=new Date(Date.UTC(+y,0,31));let prior=null,first=null;for(const p of s.data){const d=toDate(p[0]);if(d<js)prior=p;else if(d<=je&&!first)first=p;else if(d>je)break}return first||prior}
function idx(id,month){const y=month.slice(0,4),b=janObs(id,y),c=obsAt(id,monthEnd(month));if(!b||!c||!b[1])return null;return {id,base:b,cur:c,index:c[1]/b[1]*100,meta:meta(id)}}
function fmtRaw(id,v){if(v==null||!Number.isFinite(+v))return '—';const u=meta(id)?.units||'';const n=+v;if(u.includes('USD per 40ft'))return '$'+Math.round(n).toLocaleString()+'/40ft';if(u.includes('USD per metric ton'))return '$'+Math.round(n).toLocaleString()+'/t';if(u.includes('cents per cubic'))return n.toFixed(3)+'¢/m³';if(u.includes('CAD per USD'))return n.toFixed(4)+' CAD/USD';if(u.includes('TWD per USD'))return n.toFixed(3)+' TWD/USD';if(u.includes('USD/MMBtu'))return '$'+n.toFixed(3)+'/MMBtu';if(u.includes('USD/gallon'))return '$'+n.toFixed(3)+'/gal';return n.toLocaleString(undefined,{maximumFractionDigits:4})}
function sourceLink(id,label){const m=meta(id);return m?.url?`<a class="v8-source" href="${esc(m.url)}" target="_blank" rel="noopener">${esc(label||m.source||id)} ↗</a>`:`<span>${esc(label||m?.source||id||'—')}</span>`}
function current(){const month=document.getElementById('v6Month')?.value||'2026-08';const route=document.getElementById('v6Route')?.value||'IMPORT_TWD';const currency=document.getElementById('v6Fx')?.value||(route==='IMPORT_TWD'?'TWD':route==='IMPORT_USD'?'USD':'NONE');const material=document.getElementById('v6Material')?.value||'WPU101';const freight=document.getElementById('v6Freight')?.value||(route==='MFG_CA'?'TRUCK':'COMPOSITE');const enabled={};document.querySelectorAll('[data-factor]').forEach(x=>enabled[x.dataset.factor]=x.checked);return {month,route,currency,material,freight,enabled}}
function tariffRate(date){const t=date.getTime(),d25=Date.parse('2025-03-12T00:00:00Z'),d50=Date.parse('2025-06-04T00:00:00Z');return t<d25?0:t<d50?25:50}
function drewry(month){const y=month.slice(0,4),w=meta('DREWRY_WCI'),p=meta('PCU4831114831115');if(!w?.data?.length||!p?.data?.length)return null;const yr=w.data.filter(x=>x[0].startsWith(y));if(!yr.length)return null;const first=yr[0],cur=obsAt('DREWRY_WCI',monthEnd(month));if(!cur||toDate(cur[0])<toDate(first[0]))return null;const pBase=janObs('PCU4831114831115',y),pBridge=obsAt('PCU4831114831115',toDate(first[0]));if(!pBase||!pBridge)return null;const ppiBridge=pBridge[1]/pBase[1]*100,wciOwn=cur[1]/first[1]*100;return {first,cur,pBase,pBridge,ppiBridge,wciOwn,chained:ppiBridge*wciOwn/100}}
function rawRow(driver,id,obj,status='FACT',formula='Selected ÷ January × 100'){
 const m=meta(id),b=obj?.base,c=obj?.cur,ix=obj?.index;
 return `<tr><td><strong>${esc(driver)}</strong><small>${esc(id)}</small></td><td><span class="v8-evidence ${status.toLowerCase()}">${status}</span></td><td>${b?esc(b[0]):'—'}<small>${b?esc(fmtRaw(id,b[1])):'—'}</small></td><td>${c?esc(c[0]):'—'}<small>${c?esc(fmtRaw(id,c[1])):'—'}</small></td><td>${Number.isFinite(ix)?ix.toFixed(2):'—'}</td><td class="v8-formula-cell">${esc(formula)}</td><td><strong>${esc(m?.source||'—')}</strong><small>${esc(m?.frequency||'')} · ${esc(m?.units||'')}</small>${sourceLink(id,'Open source data')}</td></tr>`
}
function derivedRow(driver,index,formula,inputs,status='DERIVED'){
 return `<tr class="v8-derived-row"><td><strong>${esc(driver)}</strong><small>calculated</small></td><td><span class="v8-evidence ${status.toLowerCase()}">${status}</span></td><td colspan="2">Inputs: ${inputs}</td><td>${Number.isFinite(index)?index.toFixed(2):'—'}</td><td class="v8-formula-cell">${formula}</td><td><span>Calculated in dashboard from source-backed inputs.</span></td></tr>`
}
function buildAudit(){
 const c=current(),y=c.month.slice(0,4),end=monthEnd(c.month);let rows=[];
 const mat=idx(c.material,c.month);rows.push(rawRow('Material benchmark',c.material,mat,c.enabled.material===false?'HELD':'FACT',c.enabled.material===false?'Held at January baseline':'Selected ÷ January × 100'));
 if(c.currency==='USD'){
   const fx=idx('DEXCAUS',c.month);rows.push(rawRow('FX — USD/CAD','DEXCAUS',fx,c.enabled.fx===false?'HELD':'FACT',c.enabled.fx===false?'Held at January baseline':'Selected CAD/USD ÷ January CAD/USD × 100'));
 } else if(c.currency==='TWD'){
   const cad=idx('DEXCAUS',c.month),twd=idx('DEXTAUS',c.month);rows.push(rawRow('FX input — USD/CAD','DEXCAUS',cad,c.enabled.fx===false?'HELD':'FACT'));rows.push(rawRow('FX input — USD/TWD','DEXTAUS',twd,c.enabled.fx===false?'HELD':'FACT'));
   if(cad&&twd){const bCross=cad.base[1]/twd.base[1],sCross=cad.cur[1]/twd.cur[1],cross=sCross/bCross*100;rows.push(derivedRow('FX — CAD/TWD cross',c.enabled.fx===false?100:cross,`(${cad.cur[1].toFixed(4)} ÷ ${twd.cur[1].toFixed(4)}) ÷ (${cad.base[1].toFixed(4)} ÷ ${twd.base[1].toFixed(4)}) × 100`,`USD/CAD + USD/TWD`,c.enabled.fx===false?'HELD':'DERIVED'))}
 }
 const janTar=tariffRate(monthEnd(y+'-01')),selTar=tariffRate(end),tariffSource=D.sources?.US_TARIFF;
 rows.push(`<tr><td><strong>Tariff rate</strong><small>effective-date rule</small></td><td><span class="v8-evidence ${c.enabled.tariff===false?'held':'fact'}">${c.enabled.tariff===false?'HELD':'FACT'}</span></td><td>${y}-01<small>${janTar}%</small></td><td>${esc(c.month)}<small>${selTar}%</small></td><td>${c.enabled.tariff===false?janTar:selTar}%</td><td class="v8-formula-cell">Dated step-function; product/HTS applicability remains classification-specific.</td><td><strong>${esc(tariffSource?.publisher||'U.S. trade policy source')}</strong><small>${esc(tariffSource?.title||'Section 232 tariff rules')}</small>${tariffSource?.url?`<a class="v8-source" href="${esc(tariffSource.url)}" target="_blank" rel="noopener">Open source ↗</a>`:''}</td></tr>`);
 const truck=idx('WPU3012',c.month);rows.push(rawRow('Mainland trucking','WPU3012',truck,c.enabled.truck===false||c.freight==='OCEAN'||c.freight==='NONE'?'HELD':'FACT',c.enabled.truck===false||c.freight==='OCEAN'||c.freight==='NONE'?'Held at January baseline':'Selected ÷ January × 100'));
 const sea=idx('PCU4831114831115',c.month);rows.push(rawRow('Ocean freight — BLS PPI','PCU4831114831115',sea,c.enabled.ocean===false||c.freight==='TRUCK'||c.freight==='NONE'?'HELD':'FACT'));
 const dw=drewry(c.month);if(dw){
   const wObj={base:dw.first,cur:dw.cur,index:dw.wciOwn};rows.push(rawRow('Ocean freight — Drewry WCI','DREWRY_WCI',wObj,c.enabled.ocean===false||c.freight==='TRUCK'||c.freight==='NONE'?'HELD':'FACT','Selected WCI ÷ first available WCI observation × 100'));
   rows.push(derivedRow('Ocean chain-link',c.enabled.ocean===false||c.freight==='TRUCK'||c.freight==='NONE'?100:dw.chained,`${dw.pBridge[1].toFixed(3)} ÷ ${dw.pBase[1].toFixed(3)} × 100 × (${dw.cur[1].toFixed(0)} ÷ ${dw.first[1].toFixed(0)})`,`BLS deep-sea PPI + Drewry WCI`,c.enabled.ocean===false||c.freight==='TRUCK'||c.freight==='NONE'?'HELD':'DERIVED'));
 }
 const energyId=meta('QC_NATGAS')?.data?.length?'QC_NATGAS':'DHHNGSP',energy=idx(energyId,c.month);rows.push(rawRow('Conversion energy',energyId,energy,c.enabled.energy===false?'HELD':'FACT',c.enabled.energy===false?'Held at January baseline':'Selected ÷ January × 100'));
 const oceanIndex=dw?.chained??sea?.index??100,truckIndex=truck?.index??100;let freightIndex=100,freightFormula='Held at January';
 if(c.freight==='COMPOSITE'){freightIndex=(8*oceanIndex+4*truckIndex)/12;freightFormula=`(8 × ${oceanIndex.toFixed(2)} + 4 × ${truckIndex.toFixed(2)}) ÷ 12`}else if(c.freight==='TRUCK'){freightIndex=truckIndex;freightFormula=`Truck index = ${truckIndex.toFixed(2)}`}else if(c.freight==='OCEAN'){freightIndex=oceanIndex;freightFormula=`Ocean index = ${oceanIndex.toFixed(2)}`}
 rows.push(derivedRow('Freight subtotal',freightIndex,freightFormula,'Ocean + trucking source indices','DERIVED'));
 rows.push(`<tr class="v8-assumption-row"><td><strong>Freight cost weights</strong><small>model assumption</small></td><td><span class="v8-evidence assumption">ASSUMPTION</span></td><td colspan="3">Imported default: ocean 8 / trucking 4. Manufactured Canada default: trucking only.</td><td class="v8-formula-cell">Scenario weights determine how source indices translate into landed cost.</td><td>Not source data. Editable model assumption.</td></tr>`);
 return {rows:rows.join(''),c};
}
function csvEscape(v){const s=String(v??'');return /[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
function exportAudit(){const a=buildAudit(),table=document.querySelector('.v8-audit-table');if(!table)return;const lines=[...table.querySelectorAll('tr')].map(tr=>[...tr.querySelectorAll('th,td')].map(td=>csvEscape(td.innerText.replace(/\s+/g,' ').trim())).join(','));const metaLine=`Data snapshot,${csvEscape(TD.fetchedAt||'')},Selected month,${csvEscape(a.c.month)},Route,${csvEscape(a.c.route)}`;const blob=new Blob([metaLine+'\n'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(blob),x=document.createElement('a');x.href=u;x.download=`fastener-landed-cost-audit-${a.c.month}.csv`;x.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function render(){if(!title.textContent.includes('Imports & Trade'))return;const anchor=app.querySelector('.v7-tie-panel')||app.querySelector('.v6-trade-layer');if(!anchor)return;app.querySelector('.v8-audit-panel')?.remove();const a=buildAudit(),sec=document.createElement('section');sec.className='v8-audit-panel';sec.innerHTML=`<div class="v8-head"><div><h2>Landed Cost — Source Data Audit Trail</h2><p>Every model output is traceable from the derived index back to the exact source observation used.</p></div><button id="v8Export">Export audit CSV</button></div><div class="v8-snapshot"><span>Data build</span><strong>${esc(TD.fetchedAt?new Date(TD.fetchedAt).toLocaleString():'Build timestamp unavailable')}</strong><span>Selected period</span><strong>${esc(a.c.month)}</strong><span>Audit rule</span><strong>FACT → DERIVED → ASSUMPTION separated</strong></div><div class="v8-table-wrap"><table class="v8-audit-table"><thead><tr><th>Driver / source ID</th><th>Evidence</th><th>January source observation</th><th>Selected source observation</th><th>Index used</th><th>Calculation / treatment</th><th>Provider & source data</th></tr></thead><tbody>${a.rows}</tbody></table></div><div class="v8-note"><strong>Audit standard:</strong> a FACT row must point to an external source series and exact observation date/value. A DERIVED row must show its formula and input series. An ASSUMPTION row must be clearly identified as a model choice and must never be presented as sourced market data. If a factor is disabled, the audit marks it HELD and keeps it at the January baseline.</div>`;anchor.insertAdjacentElement('afterend',sec);sec.querySelector('#v8Export')?.addEventListener('click',exportAudit)}
let timer;function schedule(){clearTimeout(timer);timer=setTimeout(render,40)}
new MutationObserver(schedule).observe(title,{childList:true,subtree:true,characterData:true});
new MutationObserver(schedule).observe(app,{childList:true,subtree:true});
app.addEventListener('change',e=>{if(e.target?.id?.startsWith('v6')||e.target?.matches?.('[data-factor]'))schedule()});
app.addEventListener('click',e=>{if(e.target?.matches?.('[data-solo],#v6All,#v6None'))setTimeout(schedule,20)});
schedule();
})();