from pathlib import Path

FILES=[Path('index.html'),Path('journal-analytics.js')]

repls=[
('const req=["Division","Journal Number","Journal Code","Posting Desc","Posting Date","Balance"]', 'const req=["Division","Account","Journal Number","Journal Code","Posting Desc","Posting Date","Balance"]'),
('if(!j){j={p,d:div,c:code,n:jn,dt:dt.toISOString().slice(0,10),debit:0,credit:0,x:"",q:0};journals.set(key,j)}if(bal>0)j.debit+=bal;else j.credit+=bal;if(desc.length>j.x.length)j.x=desc.slice(0,160);if(isCorrection(desc)){j.q=1;j.x=desc.slice(0,160)}', 'if(!j){j={p,d:div,c:code,n:jn,dt:dt.toISOString().slice(0,10),debit:0,credit:0,gross:0,acct:{},x:"",q:0};journals.set(key,j)}if(bal>0)j.debit+=bal;else j.credit+=bal;j.gross+=Math.abs(bal);const acct=String(z[ix.Account]||"Unassigned").trim()||"Unassigned";j.acct[acct]=(j.acct[acct]||0)+bal;if(desc.length>j.x.length)j.x=desc.slice(0,160);if(isCorrection(desc)){j.q=1;j.x=desc.slice(0,160)}'),
('manual.forEach(j=>{j.m=Math.max(j.debit,-j.credit);j.g=category(j.x);j.s=signature(j.x);j.w=MANUAL_CODES[j.c]});', 'manual.forEach(j=>{j.m=Math.max(j.debit,-j.credit);j.ga=j.gross;j.g=category(j.x);j.s=signature(j.x);j.w=MANUAL_CODES[j.c]});\nfunction netCorrectionAmount(rows,includeDivision){const m={};rows.forEach(j=>Object.entries(j.acct||{}).forEach(([acct,v])=>{const k=(includeDivision?j.d+"¦":"")+acct;m[k]=(m[k]||0)+Number(v||0)}));return Object.values(m).reduce((a,v)=>a+Math.abs(v),0)}'),
('const mm=gm.reduce((a,j)=>a+j.m,0),cm=gc.reduce((a,j)=>a+j.m,0);summary.push({period:p,totalJournals:gp.length,manualJournals:gm.length,effectiveManualJournals:gm.reduce((a,j)=>a+j.w,0),manualRate:gp.length?gm.reduce((a,j)=>a+j.w,0)/gp.length:null,manualMagnitude:mm,correctionJournals:gc.length,correctionRate:gm.length?gc.length/gm.length:null,correctionMagnitude:cm,correctionMagnitudeRate:mm?cm/mm:null,recurringManualJournals:gm.filter(j=>j.r).length,recurringManualRate:gm.length?gm.filter(j=>j.r).length/gm.length:null});', 'const mm=gm.reduce((a,j)=>a+j.m,0),manualGross=gm.reduce((a,j)=>a+j.ga,0),grossErr=gc.reduce((a,j)=>a+j.ga,0),netErr=netCorrectionAmount(gc,true);summary.push({period:p,totalJournals:gp.length,manualJournals:gm.length,effectiveManualJournals:gm.reduce((a,j)=>a+j.w,0),manualRate:gp.length?gm.reduce((a,j)=>a+j.w,0)/gp.length:null,manualMagnitude:mm,correctionJournals:gc.length,correctionRate:gm.length?gc.length/gm.length:null,correctionMagnitude:grossErr,correctionGrossAmount:grossErr,correctionNetAmount:netErr,correctionMagnitudeRate:manualGross?grossErr/manualGross:null,recurringManualJournals:gm.filter(j=>j.r).length,recurringManualRate:gm.length?gm.filter(j=>j.r).length/gm.length:null});'),
('const gd=gp.filter(j=>j.d===div),gdm=gm.filter(j=>j.d===div),gdc=gdm.filter(j=>j.q),dmm=gdm.reduce((a,j)=>a+j.m,0),dcm=gdc.reduce((a,j)=>a+j.m,0);divisionSummary.push({period:p,division:div,totalJournals:gd.length,manualJournals:gdm.length,effectiveManualJournals:gdm.reduce((a,j)=>a+j.w,0),manualRate:gd.length?gdm.reduce((a,j)=>a+j.w,0)/gd.length:null,manualMagnitude:dmm,correctionJournals:gdc.length,correctionRate:gdm.length?gdc.length/gdm.length:null,correctionMagnitude:dcm,correctionMagnitudeRate:dmm?dcm/dmm:null})', 'const gd=gp.filter(j=>j.d===div),gdm=gm.filter(j=>j.d===div),gdc=gdm.filter(j=>j.q),dmm=gdm.reduce((a,j)=>a+j.m,0),dManualGross=gdm.reduce((a,j)=>a+j.ga,0),dGrossErr=gdc.reduce((a,j)=>a+j.ga,0),dNetErr=netCorrectionAmount(gdc,false);divisionSummary.push({period:p,division:div,totalJournals:gd.length,manualJournals:gdm.length,effectiveManualJournals:gdm.reduce((a,j)=>a+j.w,0),manualRate:gd.length?gdm.reduce((a,j)=>a+j.w,0)/gd.length:null,manualMagnitude:dmm,correctionJournals:gdc.length,correctionRate:gdm.length?gdc.length/gdm.length:null,correctionMagnitude:dGrossErr,correctionGrossAmount:dGrossErr,correctionNetAmount:dNetErr,correctionMagnitudeRate:dManualGross?dGrossErr/dManualGross:null})'),
('methodologyVersion:1', 'methodologyVersion:2'),
('details:manual.map(j=>({p:j.p,d:j.d,n:j.n,c:j.c,dt:j.dt,x:j.x,m:j.m,q:j.q,g:j.g,r:j.r,w:j.w}))', 'details:manual.map(j=>({p:j.p,d:j.d,n:j.n,c:j.c,dt:j.dt,x:j.x,m:j.m,ga:j.ga,q:j.q,g:j.g,r:j.r,w:j.w}))'),
('Calculated automatically at journal level. A correction is identified from Posting Desc using correction / corr. / corriger / correct / rectification variants. Dollar magnitude = greater of total debits or absolute total credits for the journal.', 'Calculated automatically from the journal CSV. <b>Net correction $</b> nets correction movements by GL account within each division, so errors that offset each other are reflected. <b>Gross / pure error $</b> sums the absolute value of every Balance line in correction journals, so offsets never hide the total error activity.'),
('grid-template-columns:repeat(4,minmax(160px,1fr));margin-top:13px"><div class="card"><div class="kpi-label">Correction JEs</div><div class="kpi-value" id="qCount">—</div><div class="kpi-meta">Unique manual journals</div></div><div class="card"><div class="kpi-label">Correction rate</div><div class="kpi-value" id="qRate">—</div><div class="kpi-meta">Corrections ÷ manual journals</div></div><div class="card"><div class="kpi-label">Correction $ exposure</div><div class="kpi-value" id="qValue">—</div><div class="kpi-meta">Economic journal magnitude</div></div><div class="card"><div class="kpi-label">Correction $ / Manual $</div><div class="kpi-value" id="qDollarRate">—</div><div class="kpi-meta">Magnitude-based quality ratio</div></div>', 'grid-template-columns:repeat(5,minmax(160px,1fr));margin-top:13px"><div class="card"><div class="kpi-label">Correction JEs</div><div class="kpi-value" id="qCount">—</div><div class="kpi-meta">Unique manual journals</div></div><div class="card"><div class="kpi-label">Correction rate</div><div class="kpi-value" id="qRate">—</div><div class="kpi-meta">Corrections ÷ manual journals</div></div><div class="card"><div class="kpi-label">Net correction $</div><div class="kpi-value" id="qNetValue">—</div><div class="kpi-meta">Offset by GL account / division</div></div><div class="card"><div class="kpi-label">Gross / pure error $</div><div class="kpi-value" id="qGrossValue">—</div><div class="kpi-meta">Σ absolute Balance lines</div></div><div class="card"><div class="kpi-label">Gross error $ / Manual activity</div><div class="kpi-value" id="qDollarRate">—</div><div class="kpi-meta">Absolute correction lines ÷ absolute manual lines</div></div>'),
('<th>Correction $</th><th>Correction $ %</th>', '<th>Net correction $</th><th>Gross / pure error $</th><th>Gross error %</th>'),
('<th>Category</th><th>Count</th><th>Magnitude</th>', '<th>Category</th><th>Count</th><th>Gross / pure error $</th>'),
('<th>Category</th><th>Magnitude</th></tr></thead><tbody id="correctionBody">', '<th>Category</th><th>Economic JE magnitude</th><th>Gross / pure error $</th></tr></thead><tbody id="correctionBody">'),
('$id("qValue").textContent=s?money(s.correctionMagnitude):"—";', '$id("qNetValue").textContent=s?money(s.correctionNetAmount??s.correctionMagnitude):"—";$id("qGrossValue").textContent=s?money(s.correctionGrossAmount??s.correctionMagnitude):"—";'),
('<td>${money(x.correctionMagnitude)}</td><td>${pct(x.correctionMagnitudeRate)}</td></tr>', '<td>${money(x.correctionNetAmount??x.correctionMagnitude)}</td><td>${money(x.correctionGrossAmount??x.correctionMagnitude)}</td><td>${pct(x.correctionMagnitudeRate)}</td></tr>'),
('cats[x.g]??={n:0,m:0};cats[x.g].n++;cats[x.g].m+=Number(x.m||0)', 'cats[x.g]??={n:0,m:0};cats[x.g].n++;cats[x.g].m+=Number(x.ga??x.m??0)'),
('details.sort((a,b)=>b.m-a.m).map(x=>`<tr><td>${esc(x.dt)}</td><td>${esc(x.d)}</td><td>${esc(x.n)}</td><td>${esc(x.c)}</td><td>${esc(x.x)}</td><td>${esc(x.g)}</td><td>${money(x.m)}</td></tr>`)', 'details.sort((a,b)=>(b.ga??b.m)-(a.ga??a.m)).map(x=>`<tr><td>${esc(x.dt)}</td><td>${esc(x.d)}</td><td>${esc(x.n)}</td><td>${esc(x.c)}</td><td>${esc(x.x)}</td><td>${esc(x.g)}</td><td>${money(x.m)}</td><td>${money(x.ga??x.m)}</td></tr>`)')
]

for p in FILES:
    if not p.exists():
        continue
    s=p.read_text(encoding='utf-8')
    for old,new in repls:
        if old in s:
            s=s.replace(old,new)
    p.write_text(s,encoding='utf-8')
