import { neon } from '@neondatabase/serverless';

const enc=new TextEncoder();
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...headers}});
const workspace=env=>env.WORKSPACE_ID||'alex';
const db=env=>neon(env.DATABASE_URL);
const QUADS=['do','schedule','delegate','later'],TASK_STATUSES=['open','waiting','done','cancelled'],PRIORITIES=['low','normal','high'],CONTEXTS=['work','personal'];
const contextOf=v=>CONTEXTS.includes(String(v||'').toLowerCase())?String(v).toLowerCase():'work';
function cookieValue(request,name){const raw=request.headers.get('cookie')||'';for(const part of raw.split(';')){const [k,...v]=part.trim().split('=');if(k===name)return decodeURIComponent(v.join('='));}return '';}
function b64url(bytes){return btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
async function sign(secret,value){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64url(await crypto.subtle.sign('HMAC',key,enc.encode(value)));}
async function isAuthed(request,env){if(!env.SESSION_SECRET)return false;const got=cookieValue(request,'mywork_session');if(!got)return false;return got===await sign(env.SESSION_SECRET,`my-work:${workspace(env)}`);}
const sessionCookie=value=>`mywork_session=${encodeURIComponent(value)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=2592000`;
const clearCookie=()=> 'mywork_session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0';
function normalizePeople(value){if(!value)return[];const arr=Array.isArray(value)?value:String(value).split(',');return[...new Set(arr.map(x=>String(x).trim()).filter(Boolean))].slice(0,20);}
function normalizeOwner(value){const v=String(value||'').trim();return!v||v.toLowerCase()==='alex'||v.toLowerCase()==='me'?null:v;}
function localDateKey(value=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Montreal',year:'numeric',month:'2-digit',day:'2-digit'}).format(value);}
const isMine=t=>!t?.owner_name||String(t.owner_name).toLowerCase()==='alex';
const isDelegated=t=>!isMine(t)&&!['done','cancelled'].includes(t.status);
function mergePeople(base,waiting,owner){const extra=[];if(waiting)extra.push(waiting);if(owner)extra.push(owner);return normalizePeople([...(base||[]),...extra]);}
function snapshotTask(t){if(!t)return null;return{id:t.id,context:t.context,project_id:t.project_id??null,title:t.title,details:t.details??null,status:t.status,priority:t.priority,due_at:t.due_at??null,waiting_on:t.waiting_on??null,owner_name:t.owner_name??null,follow_up_at:t.follow_up_at??null,eisenhower_quadrant:t.eisenhower_quadrant??null,with_people:normalizePeople(t.with_people),completed_at:t.completed_at??null};}
function snapshotProject(p){if(!p)return null;return{id:p.id,context:p.context,name:p.name,description:p.description??null,status:p.status,with_people:normalizePeople(p.with_people)};}
async function activity(sql,env,ctx,entityType,entityId,action,summary,metadata={}){const rows=await sql`INSERT INTO activity_log (workspace_id,context,entity_type,entity_id,action,summary,metadata) VALUES (${workspace(env)},${ctx},${entityType},${String(entityId||'')},${action},${summary},${JSON.stringify(metadata)}::jsonb) RETURNING id`;return rows[0]?.id;}
async function findProject(sql,env,ctx,name){if(!name)return null;const rows=await sql`SELECT * FROM projects WHERE workspace_id=${workspace(env)} AND context=${ctx} AND lower(name)=lower(${name.trim()}) LIMIT 1`;return rows[0]||null;}
async function projectById(sql,env,ctx,id){const rows=await sql`SELECT * FROM projects WHERE workspace_id=${workspace(env)} AND context=${ctx} AND id=${id}::uuid LIMIT 1`;return rows[0]||null;}
async function getOrCreateProject(sql,env,ctx,name,description=null,withPeople=[]){if(!name)return null;const people=normalizePeople(withPeople);const rows=await sql`INSERT INTO projects (workspace_id,context,name,description,with_people) VALUES (${workspace(env)},${ctx},${name.trim()},${description},${people}) ON CONFLICT (workspace_id,context,name) DO UPDATE SET description=COALESCE(EXCLUDED.description,projects.description),with_people=CASE WHEN cardinality(EXCLUDED.with_people)>0 THEN EXCLUDED.with_people ELSE projects.with_people END,updated_at=now() RETURNING *`;return rows[0];}
async function taskById(sql,env,ctx,id){const rows=await sql`SELECT t.*,p.name AS project_name FROM tasks t LEFT JOIN projects p ON p.id=t.project_id WHERE t.workspace_id=${workspace(env)} AND t.context=${ctx} AND t.id=${id}::uuid LIMIT 1`;return rows[0]||null;}
async function restoreTask(sql,env,ctx,before){await sql`UPDATE tasks SET project_id=${before.project_id},title=${before.title},details=${before.details},status=${before.status},priority=${before.priority},due_at=${before.due_at},waiting_on=${before.waiting_on},owner_name=${before.owner_name},follow_up_at=${before.follow_up_at},eisenhower_quadrant=${before.eisenhower_quadrant},with_people=${normalizePeople(before.with_people)},completed_at=${before.completed_at},updated_at=now() WHERE workspace_id=${workspace(env)} AND context=${ctx} AND id=${before.id}::uuid`;}
async function undoLast(sql,env,ctx){const rows=await sql`SELECT a.* FROM activity_log a WHERE a.workspace_id=${workspace(env)} AND a.context=${ctx} AND COALESCE((a.metadata->>'reversible')::boolean,false)=true AND NOT EXISTS (SELECT 1 FROM activity_log u WHERE u.workspace_id=a.workspace_id AND u.context=a.context AND u.action='undo' AND u.metadata->>'undo_of'=a.id::text) ORDER BY a.id DESC LIMIT 1`;const a=rows[0];if(!a)return{ok:false,message:'Nothing recent to undo.'};const m=a.metadata||{};if(m.operation==='task_create')await sql`DELETE FROM tasks WHERE workspace_id=${workspace(env)} AND context=${ctx} AND id=${m.entity_id}::uuid`;else if(['task_update','task_complete','task_move'].includes(m.operation)&&m.before)await restoreTask(sql,env,ctx,m.before);else if(m.operation==='note_create')await sql`DELETE FROM notes WHERE workspace_id=${workspace(env)} AND context=${ctx} AND id=${m.entity_id}::uuid`;else if(m.operation==='memory_create')await sql`DELETE FROM memory_entries WHERE workspace_id=${workspace(env)} AND context=${ctx} AND id=${m.entity_id}::uuid`;else if(m.operation==='project_create')await sql`DELETE FROM projects WHERE workspace_id=${workspace(env)} AND context=${ctx} AND id=${m.entity_id}::uuid AND NOT EXISTS (SELECT 1 FROM tasks WHERE project_id=${m.entity_id}::uuid)`;else if(m.operation==='project_update'&&m.before){const b=m.before;await sql`UPDATE projects SET name=${b.name},description=${b.description},status=${b.status},with_people=${normalizePeople(b.with_people)},updated_at=now() WHERE workspace_id=${workspace(env)} AND context=${ctx} AND id=${b.id}::uuid`;}else return{ok:false,message:'That change cannot be undone automatically.'};await activity(sql,env,ctx,a.entity_type,a.entity_id,'undo',`Undid: ${a.summary}`,{undo_of:String(a.id)});return{ok:true,message:`Undid: ${a.summary}`};}

const tools=[
{type:'function',name:'list_projects',description:'List tracked projects in the active Work or Personal context.',strict:true,parameters:{type:'object',properties:{search:{type:['string','null']},person:{type:['string','null']}},required:['search','person'],additionalProperties:false}},
{type:'function',name:'create_project',description:'Create or update a project in the active context when the user clearly wants it tracked.',strict:true,parameters:{type:'object',properties:{name:{type:'string'},description:{type:['string','null']},with_people:{type:'array',items:{type:'string'}}},required:['name','description','with_people'],additionalProperties:false}},
{type:'function',name:'list_tasks',description:'Find tasks in the active context by words, project, person, status, owner or Eisenhower quadrant.',strict:true,parameters:{type:'object',properties:{search:{type:['string','null']},project_name:{type:['string','null']},person:{type:['string','null']},owner_name:{type:['string','null']},status:{type:'string',enum:['open','waiting','done','cancelled','all']},eisenhower_quadrant:{type:['string','null'],enum:['do','schedule','delegate','later',null]}},required:['search','project_name','person','owner_name','status','eisenhower_quadrant'],additionalProperties:false}},
{type:'function',name:'create_task',description:'Create a concrete action in the active context. Do not create tasks from mere brainstorming.',strict:true,parameters:{type:'object',properties:{title:{type:'string'},details:{type:['string','null']},project_name:{type:['string','null']},due_at:{type:['string','null']},priority:{type:'string',enum:['low','normal','high']},status:{type:'string',enum:['open','waiting']},waiting_on:{type:['string','null']},owner_name:{type:['string','null']},follow_up_at:{type:['string','null']},eisenhower_quadrant:{type:['string','null'],enum:['do','schedule','delegate','later',null]},with_people:{type:'array',items:{type:'string'}}},required:['title','details','project_name','due_at','priority','status','waiting_on','owner_name','follow_up_at','eisenhower_quadrant','with_people'],additionalProperties:false}},
{type:'function',name:'update_task',description:'Update one exact task in the active context after its ID has been resolved.',strict:true,parameters:{type:'object',properties:{id:{type:'string'},title:{type:['string','null']},details:{type:['string','null']},project_name:{type:['string','null']},due_at:{type:['string','null']},priority:{type:['string','null'],enum:['low','normal','high',null]},status:{type:['string','null'],enum:['open','waiting','done','cancelled',null]},waiting_on:{type:['string','null']},owner_name:{type:['string','null']},follow_up_at:{type:['string','null']},eisenhower_quadrant:{type:['string','null'],enum:['do','schedule','delegate','later',null]},with_people:{type:['array','null'],items:{type:'string'}}},required:['id','title','details','project_name','due_at','priority','status','waiting_on','owner_name','follow_up_at','eisenhower_quadrant','with_people'],additionalProperties:false}},
{type:'function',name:'complete_task',description:'Mark one exact task complete in the active context.',strict:true,parameters:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false}},
{type:'function',name:'add_note',description:'Save a durable note, decision, meeting note or assumption in the active context.',strict:true,parameters:{type:'object',properties:{body:{type:'string'},kind:{type:'string',enum:['note','decision','meeting_note','assumption']},title:{type:['string','null']},project_name:{type:['string','null']}},required:['body','kind','title','project_name'],additionalProperties:false}},
{type:'function',name:'remember_context',description:'Save stable context in the active Work or Personal context for future retrieval.',strict:true,parameters:{type:'object',properties:{body:{type:'string'},memory_type:{type:'string',enum:['context','decision','history','reference']},title:{type:['string','null']},project_name:{type:['string','null']},tags:{type:'array',items:{type:'string'}}},required:['body','memory_type','title','project_name','tags'],additionalProperties:false}},
{type:'function',name:'search_memory',description:'Search prior memory, notes, decisions and chat history inside the active context.',strict:true,parameters:{type:'object',properties:{query:{type:'string'},project_name:{type:['string','null']}},required:['query','project_name'],additionalProperties:false}},
{type:'function',name:'get_workspace_summary',description:'Get counts and important open work inside the active context.',strict:true,parameters:{type:'object',properties:{scope:{type:'string',enum:['all','today','upcoming','overdue','waiting','delegated','followup','inbox']},person:{type:['string','null']}},required:['scope','person'],additionalProperties:false}},
{type:'function',name:'list_people',description:'List people connected to tasks and projects in the active context.',strict:true,parameters:{type:'object',properties:{search:{type:['string','null']}},required:['search'],additionalProperties:false}},
{type:'function',name:'undo_last_change',description:'Undo the most recent reversible change in the active context.',strict:true,parameters:{type:'object',properties:{},required:[],additionalProperties:false}}
];

async function runTool(name,args,sql,env,ctx){const ws=workspace(env);
if(name==='list_projects'){let rows=await sql`SELECT id,name,description,status,with_people,updated_at FROM projects WHERE workspace_id=${ws} AND context=${ctx} ORDER BY updated_at DESC`;if(args.search){const q=args.search.toLowerCase();rows=rows.filter(x=>x.name.toLowerCase().includes(q)||(x.description||'').toLowerCase().includes(q));}if(args.person){const p=args.person.toLowerCase();rows=rows.filter(x=>normalizePeople(x.with_people).some(n=>n.toLowerCase().includes(p)));}return{projects:rows.slice(0,50)};}
if(name==='create_project'){const existed=await findProject(sql,env,ctx,args.name),before=snapshotProject(existed),p=await getOrCreateProject(sql,env,ctx,args.name,args.description,args.with_people);await activity(sql,env,ctx,'project',p.id,existed?'update':'create',`${existed?'Updated':'Created'} project: ${p.name}`,{reversible:true,operation:existed?'project_update':'project_create',entity_id:p.id,before});return{project:p};}
if(name==='list_tasks'){let rows=await sql`SELECT t.*,p.name AS project_name FROM tasks t LEFT JOIN projects p ON p.id=t.project_id WHERE t.workspace_id=${ws} AND t.context=${ctx} ORDER BY t.due_at NULLS LAST,t.updated_at DESC LIMIT 180`;if(args.status!=='all')rows=rows.filter(x=>x.status===args.status);if(args.project_name)rows=rows.filter(x=>(x.project_name||'').toLowerCase().includes(args.project_name.toLowerCase()));if(args.person){const p=args.person.toLowerCase();rows=rows.filter(x=>normalizePeople(x.with_people).some(n=>n.toLowerCase().includes(p))||(x.waiting_on||'').toLowerCase().includes(p)||(x.owner_name||'').toLowerCase().includes(p));}if(args.owner_name){const o=args.owner_name.toLowerCase();rows=rows.filter(x=>(x.owner_name||'Alex').toLowerCase().includes(o));}if(args.eisenhower_quadrant)rows=rows.filter(x=>x.eisenhower_quadrant===args.eisenhower_quadrant);if(args.search){const q=args.search.toLowerCase();rows=rows.filter(x=>[x.title,x.details,x.waiting_on,x.owner_name,x.project_name,normalizePeople(x.with_people).join(' ')].join(' ').toLowerCase().includes(q));}return{tasks:rows.slice(0,70)};}
if(name==='create_task'){const p=args.project_name?await getOrCreateProject(sql,env,ctx,args.project_name):null,owner=normalizeOwner(args.owner_name),people=mergePeople(args.with_people,args.waiting_on,owner),q=QUADS.includes(args.eisenhower_quadrant)?args.eisenhower_quadrant:null;const rows=await sql`INSERT INTO tasks (workspace_id,context,project_id,title,details,status,priority,due_at,waiting_on,owner_name,follow_up_at,eisenhower_quadrant,with_people,source) VALUES (${ws},${ctx},${p?.id||null},${args.title.trim()},${args.details},${args.status},${args.priority},${args.due_at},${args.waiting_on},${owner},${args.follow_up_at},${q},${people},'ai_chat') RETURNING *`;const t=rows[0];await activity(sql,env,ctx,'task',t.id,'create',`Created task: ${t.title}`,{reversible:true,operation:'task_create',entity_id:t.id});return{task:await taskById(sql,env,ctx,t.id)};}
if(name==='update_task'){const old=await taskById(sql,env,ctx,args.id);if(!old)return{error:'Task not found'};const before=snapshotTask(old);let projectId=old.project_id;if(args.project_name!==null)projectId=args.project_name?(await getOrCreateProject(sql,env,ctx,args.project_name)).id:null;const title=args.title??old.title,details=args.details??old.details,due=args.due_at??old.due_at,priority=args.priority??old.priority,status=args.status??old.status,waiting=args.waiting_on??old.waiting_on,owner=args.owner_name===null?old.owner_name:normalizeOwner(args.owner_name),follow=args.follow_up_at===null?old.follow_up_at:args.follow_up_at,q=args.eisenhower_quadrant===null?old.eisenhower_quadrant:(QUADS.includes(args.eisenhower_quadrant)?args.eisenhower_quadrant:null),basePeople=args.with_people===null?normalizePeople(old.with_people):normalizePeople(args.with_people),people=mergePeople(basePeople,waiting,owner);await sql`UPDATE tasks SET project_id=${projectId},title=${title},details=${details},due_at=${due},priority=${priority},status=${status},waiting_on=${waiting},owner_name=${owner},follow_up_at=${follow},eisenhower_quadrant=${q},with_people=${people},updated_at=now(),completed_at=CASE WHEN ${status}='done' THEN COALESCE(completed_at,now()) ELSE CASE WHEN ${status}<>'done' THEN NULL ELSE completed_at END END WHERE workspace_id=${ws} AND context=${ctx} AND id=${args.id}::uuid`;await activity(sql,env,ctx,'task',args.id,'update',`Updated task: ${title}`,{reversible:true,operation:'task_update',entity_id:args.id,before});return{task:await taskById(sql,env,ctx,args.id)};}
if(name==='complete_task'){const old=await taskById(sql,env,ctx,args.id);if(!old)return{error:'Task not found'};const before=snapshotTask(old);await sql`UPDATE tasks SET status='done',completed_at=COALESCE(completed_at,now()),waiting_on=NULL,follow_up_at=NULL,updated_at=now() WHERE workspace_id=${ws} AND context=${ctx} AND id=${args.id}::uuid`;await activity(sql,env,ctx,'task',args.id,'complete',`Completed task: ${old.title}`,{reversible:true,operation:'task_complete',entity_id:args.id,before});return{task:await taskById(sql,env,ctx,args.id)};}
if(name==='add_note'){const p=args.project_name?await getOrCreateProject(sql,env,ctx,args.project_name):null,rows=await sql`INSERT INTO notes (workspace_id,context,project_id,kind,title,body,source) VALUES (${ws},${ctx},${p?.id||null},${args.kind},${args.title},${args.body},'ai_chat') RETURNING *`;await activity(sql,env,ctx,'note',rows[0].id,'create',`${args.kind}: ${args.title||args.body.slice(0,80)}`,{reversible:true,operation:'note_create',entity_id:rows[0].id});return{note:rows[0]};}
if(name==='remember_context'){const p=args.project_name?await getOrCreateProject(sql,env,ctx,args.project_name):null,rows=await sql`INSERT INTO memory_entries (workspace_id,context,project_id,memory_type,title,body,tags,source_type,source_ref,occurred_at) VALUES (${ws},${ctx},${p?.id||null},${args.memory_type},${args.title},${args.body},${JSON.stringify(args.tags)}::jsonb,'ai_chat','my-work',now()) RETURNING *`;await activity(sql,env,ctx,'memory',rows[0].id,'remember',`Remembered: ${args.title||args.body.slice(0,80)}`,{reversible:true,operation:'memory_create',entity_id:rows[0].id});return{memory:rows[0]};}
if(name==='search_memory'){const project=args.project_name?await findProject(sql,env,ctx,args.project_name):null;let mem=[];try{mem=await sql`SELECT m.*,p.name AS project_name FROM memory_entries m LEFT JOIN projects p ON p.id=m.project_id WHERE m.workspace_id=${ws} AND m.context=${ctx} AND (${project?.id||null}::uuid IS NULL OR m.project_id=${project?.id||null}::uuid) AND to_tsvector('simple',coalesce(m.title,'')||' '||m.body) @@ plainto_tsquery('simple',${args.query}) ORDER BY COALESCE(m.occurred_at,m.created_at) DESC LIMIT 12`;}catch{mem=await sql`SELECT m.*,p.name AS project_name FROM memory_entries m LEFT JOIN projects p ON p.id=m.project_id WHERE m.workspace_id=${ws} AND m.context=${ctx} ORDER BY COALESCE(m.occurred_at,m.created_at) DESC LIMIT 12`;}const notes=await sql`SELECT n.*,p.name AS project_name FROM notes n LEFT JOIN projects p ON p.id=n.project_id WHERE n.workspace_id=${ws} AND n.context=${ctx} AND (n.body ILIKE ${'%'+args.query+'%'} OR COALESCE(n.title,'') ILIKE ${'%'+args.query+'%'}) ORDER BY n.created_at DESC LIMIT 12`,chats=await sql`SELECT role,content,created_at FROM chat_messages WHERE workspace_id=${ws} AND context=${ctx} AND content ILIKE ${'%'+args.query.slice(0,120)+'%'} ORDER BY created_at DESC LIMIT 8`;return{memory:mem,notes,chats};}
if(name==='get_workspace_summary'){let rows=await sql`SELECT t.*,p.name AS project_name FROM tasks t LEFT JOIN projects p ON p.id=t.project_id WHERE t.workspace_id=${ws} AND t.context=${ctx} AND t.status NOT IN ('done','cancelled') ORDER BY t.due_at NULLS LAST,t.updated_at DESC LIMIT 180`;const today=localDateKey();if(args.person){const p=args.person.toLowerCase();rows=rows.filter(x=>normalizePeople(x.with_people).some(n=>n.toLowerCase().includes(p))||(x.waiting_on||'').toLowerCase().includes(p)||(x.owner_name||'').toLowerCase().includes(p));}const isToday=x=>x.due_at&&localDateKey(new Date(x.due_at))===today,overdue=x=>x.due_at&&localDateKey(new Date(x.due_at))<today,followDue=x=>x.follow_up_at&&localDateKey(new Date(x.follow_up_at))<=today;let selected=rows;if(args.scope==='today')selected=rows.filter(isToday);if(args.scope==='overdue')selected=rows.filter(overdue);if(args.scope==='waiting')selected=rows.filter(x=>x.status==='waiting');if(args.scope==='delegated')selected=rows.filter(isDelegated);if(args.scope==='followup')selected=rows.filter(followDue);if(args.scope==='upcoming')selected=rows.filter(x=>x.due_at&&localDateKey(new Date(x.due_at))>today);if(args.scope==='inbox')selected=rows.filter(x=>!x.eisenhower_quadrant);const projectCount=(await sql`SELECT count(*)::int AS n FROM projects WHERE workspace_id=${ws} AND context=${ctx} AND status='active'`)[0].n;return{context:ctx,today:rows.filter(isToday).length,overdue:rows.filter(overdue).length,waiting:rows.filter(x=>x.status==='waiting').length,delegated:rows.filter(isDelegated).length,followup:rows.filter(followDue).length,projects:projectCount,inbox:rows.filter(x=>!x.eisenhower_quadrant).length,tasks:selected.slice(0,50)};}
if(name==='list_people'){const tasks=await sql`SELECT with_people,waiting_on,owner_name,status FROM tasks WHERE workspace_id=${ws} AND context=${ctx} AND status NOT IN ('done','cancelled')`,projects=await sql`SELECT with_people FROM projects WHERE workspace_id=${ws} AND context=${ctx} AND status='active'`,map=new Map();const get=n=>{const k=String(n||'').trim();if(!k)return null;const o=map.get(k)||{name:k,shared:0,waiting:0,delegated:0,projects:0};map.set(k,o);return o};for(const t of tasks){for(const p of normalizePeople(t.with_people)){const o=get(p);if(o)o.shared++;}if(t.waiting_on){const o=get(t.waiting_on);if(o)o.waiting++;}if(t.owner_name){const o=get(t.owner_name);if(o)o.delegated++;}}for(const p of projects)for(const n of normalizePeople(p.with_people)){const o=get(n);if(o)o.projects++;}let out=[...map.values()].sort((a,b)=>(b.shared+b.waiting+b.delegated+b.projects)-(a.shared+a.waiting+a.delegated+a.projects));if(args.search)out=out.filter(x=>x.name.toLowerCase().includes(args.search.toLowerCase()));return{people:out.slice(0,50)};}
if(name==='undo_last_change')return undoLast(sql,env,ctx);return{error:`Unknown tool ${name}`};}

function extractText(response){const parts=[];for(const item of response.output||[])if(item.type==='message')for(const c of item.content||[])if(c.type==='output_text'&&c.text)parts.push(c.text);return parts.join('\n').trim();}
function systemInstructions(env,ctx){const now=new Date(),label=ctx==='personal'?'Personal':'Work';return`You are My Work, Alex's conversational chief-of-staff. The active context is ${label}. Today is ${now.toISOString()} and timezone is America/Montreal.
- Treat the active context as a hard boundary. Never create, update, search, summarize or mix records from the other context unless the user explicitly switches contexts in the app.
- In Work, organize professional tasks, projects, people, decisions and context. In Personal, organize family, home, health, travel, personal finance and life administration.
- Database tools are the source of truth. Never claim a save/change unless the tool succeeded.
- Concrete actions become tasks; brainstorming does not unless committed.
- Record explicit agreements/conclusions as decisions; save stable background selectively.
- Resolve conversational references with list_tasks/list_projects when needed.
- Owner = who must do the work; With = people involved; Waiting on = current blocker; Follow-up = when Alex should check back. Null owner means Alex.
- If someone else owns a task, set owner_name. If “with X”, add X to with_people. If waiting on X, set waiting status and waiting_on, and add a follow-up when stated.
- Eisenhower: urgent+important=do; important+not urgent=schedule; urgent+less important/delegated=delegate; neither/later= later. Do not invent a quadrant unless asked or obvious.
- Multiple actions in one message can produce multiple calls.
- For focus, prioritize Alex-owned work; delegated/waiting items surface as follow-ups.
- Search memory when prior rationale or decisions are referenced.
- Use undo_last_change for explicit undo requests.
- Keep replies concise and operational.`;}
async function callOpenAI(env,input,ctx){const res=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:env.OPENAI_MODEL||'gpt-5.6',instructions:systemInstructions(env,ctx),input,tools,tool_choice:'auto',store:false,safety_identifier:`my-work-${workspace(env)}-${ctx}`})});const txt=await res.text();let data;try{data=txt?JSON.parse(txt):{}}catch{throw new Error(`OpenAI returned an invalid response (${res.status}).`)}if(!res.ok)throw new Error(data?.error?.message||`OpenAI request failed (${res.status})`);return data;}
async function chat(request,env,ctx){if(!env.OPENAI_API_KEY||!env.DATABASE_URL)return json({error:'Server is missing OPENAI_API_KEY or DATABASE_URL.'},500);const body=await request.json(),message=String(body.message||'').trim();if(!message)return json({error:'Message is required.'},400);const sql=db(env),ws=workspace(env),recent=await sql`SELECT role,content FROM chat_messages WHERE workspace_id=${ws} AND context=${ctx} ORDER BY created_at DESC LIMIT 20`;await sql`INSERT INTO chat_messages (workspace_id,context,role,content) VALUES (${ws},${ctx},'user',${message})`;let input=[...recent.reverse().map(m=>({role:m.role,content:m.content})),{role:'user',content:message}],response,toolEvents=[];for(let round=0;round<8;round++){response=await callOpenAI(env,input,ctx);const calls=(response.output||[]).filter(x=>x.type==='function_call');if(!calls.length)break;input.push(...response.output);for(const call of calls){let args={};try{args=JSON.parse(call.arguments||'{}')}catch{}let result;try{result=await runTool(call.name,args,sql,env,ctx)}catch(e){result={error:e.message||String(e)}}toolEvents.push({name:call.name,args,result});input.push({type:'function_call_output',call_id:call.call_id,output:JSON.stringify(result)});}}const reply=extractText(response)||'Done.';await sql`INSERT INTO chat_messages (workspace_id,context,role,content) VALUES (${ws},${ctx},'assistant',${reply})`;return json({reply,tool_events:toolEvents,context:ctx});}
function buildPeople(tasks,projects){const map=new Map(),get=n=>{const k=String(n||'').trim();if(!k)return null;const o=map.get(k)||{name:k,shared:0,waiting:0,delegated:0,projects:0};map.set(k,o);return o};for(const t of tasks.filter(x=>!['done','cancelled'].includes(x.status))){for(const n of normalizePeople(t.with_people)){const o=get(n);if(o)o.shared++;}if(t.waiting_on){const o=get(t.waiting_on);if(o)o.waiting++;}if(t.owner_name){const o=get(t.owner_name);if(o)o.delegated++;}}for(const p of projects.filter(x=>x.status==='active'))for(const n of normalizePeople(p.with_people)){const o=get(n);if(o)o.projects++;}return[...map.values()].sort((a,b)=>(b.shared+b.waiting+b.delegated+b.projects)-(a.shared+a.waiting+a.delegated+a.projects));}
async function state(env,ctx){const sql=db(env),ws=workspace(env),tasks=await sql`SELECT t.*,p.name AS project_name FROM tasks t LEFT JOIN projects p ON p.id=t.project_id WHERE t.workspace_id=${ws} AND t.context=${ctx} ORDER BY CASE WHEN t.status IN ('open','waiting') THEN 0 ELSE 1 END,t.due_at NULLS LAST,t.updated_at DESC LIMIT 300`,projects=await sql`SELECT p.*,count(t.id) FILTER (WHERE t.status IN ('open','waiting'))::int AS open_tasks FROM projects p LEFT JOIN tasks t ON t.project_id=p.id WHERE p.workspace_id=${ws} AND p.context=${ctx} GROUP BY p.id ORDER BY p.updated_at DESC`,notes=await sql`SELECT n.*,p.name AS project_name FROM notes n LEFT JOIN projects p ON p.id=n.project_id WHERE n.workspace_id=${ws} AND n.context=${ctx} ORDER BY n.created_at DESC LIMIT 50`,messages=await sql`SELECT role,content,created_at FROM chat_messages WHERE workspace_id=${ws} AND context=${ctx} ORDER BY created_at DESC LIMIT 50`,activityRows=await sql`SELECT id,entity_type,entity_id,action,summary,metadata,created_at FROM activity_log WHERE workspace_id=${ws} AND context=${ctx} ORDER BY id DESC LIMIT 100`;const today=localDateKey(),open=tasks.filter(x=>!['done','cancelled'].includes(x.status)),isToday=x=>x.due_at&&localDateKey(new Date(x.due_at))===today,overdue=x=>x.due_at&&localDateKey(new Date(x.due_at))<today,followDue=x=>x.follow_up_at&&localDateKey(new Date(x.follow_up_at))<=today,lastUndoable=activityRows.find(a=>a.metadata?.reversible&&!activityRows.some(u=>u.action==='undo'&&String(u.metadata?.undo_of)===String(a.id)));return{context:ctx,tasks,projects,notes,messages:messages.reverse(),activity:activityRows,people:buildPeople(tasks,projects),last_undoable:lastUndoable||null,metrics:{today:open.filter(x=>isMine(x)&&isToday(x)).length,overdue:open.filter(x=>isMine(x)&&overdue(x)).length,waiting:open.filter(x=>x.status==='waiting').length,delegated:open.filter(isDelegated).length,followup:open.filter(followDue).length,projects:projects.filter(x=>x.status==='active').length,open:open.length,mywork:open.filter(isMine).length,inbox:open.filter(x=>!x.eisenhower_quadrant).length}};}
async function patchTask(request,env,ctx,id){const sql=db(env),old=await taskById(sql,env,ctx,id);if(!old)return json({error:'Task not found'},404);const b=await request.json(),before=snapshotTask(old);let projectId=old.project_id;if(Object.prototype.hasOwnProperty.call(b,'project_name'))projectId=b.project_name?(await getOrCreateProject(sql,env,ctx,String(b.project_name))).id:null;const title=Object.prototype.hasOwnProperty.call(b,'title')?String(b.title||'').trim():old.title;if(!title)return json({error:'Title is required.'},400);const details=Object.prototype.hasOwnProperty.call(b,'details')?(b.details||null):old.details,status=Object.prototype.hasOwnProperty.call(b,'status')&&TASK_STATUSES.includes(b.status)?b.status:old.status,priority=Object.prototype.hasOwnProperty.call(b,'priority')&&PRIORITIES.includes(b.priority)?b.priority:old.priority,due=Object.prototype.hasOwnProperty.call(b,'due_at')?(b.due_at||null):old.due_at,waiting=Object.prototype.hasOwnProperty.call(b,'waiting_on')?(b.waiting_on||null):old.waiting_on,owner=Object.prototype.hasOwnProperty.call(b,'owner_name')?normalizeOwner(b.owner_name):old.owner_name,follow=Object.prototype.hasOwnProperty.call(b,'follow_up_at')?(b.follow_up_at||null):old.follow_up_at,q=Object.prototype.hasOwnProperty.call(b,'eisenhower_quadrant')?(QUADS.includes(b.eisenhower_quadrant)?b.eisenhower_quadrant:null):old.eisenhower_quadrant,basePeople=Object.prototype.hasOwnProperty.call(b,'with_people')?normalizePeople(b.with_people):normalizePeople(old.with_people),people=mergePeople(basePeople,waiting,owner);await sql`UPDATE tasks SET project_id=${projectId},title=${title},details=${details},status=${status},priority=${priority},due_at=${due},waiting_on=${waiting},owner_name=${owner},follow_up_at=${follow},eisenhower_quadrant=${q},with_people=${people},completed_at=CASE WHEN ${status}='done' THEN COALESCE(completed_at,now()) ELSE NULL END,updated_at=now() WHERE workspace_id=${workspace(env)} AND context=${ctx} AND id=${id}::uuid`;await activity(sql,env,ctx,'task',id,'update_manual',`Updated task: ${title}`,{reversible:true,operation:'task_update',entity_id:id,before});return json({ok:true,task:await taskById(sql,env,ctx,id)});}
async function patchProject(request,env,ctx,id){const sql=db(env),old=await projectById(sql,env,ctx,id);if(!old)return json({error:'Project not found'},404);const b=await request.json(),before=snapshotProject(old),name=Object.prototype.hasOwnProperty.call(b,'name')?String(b.name||'').trim():old.name;if(!name)return json({error:'Project name is required.'},400);const description=Object.prototype.hasOwnProperty.call(b,'description')?(b.description||null):old.description,status=Object.prototype.hasOwnProperty.call(b,'status')&&['active','on_hold','done','archived'].includes(b.status)?b.status:old.status,people=Object.prototype.hasOwnProperty.call(b,'with_people')?normalizePeople(b.with_people):normalizePeople(old.with_people);await sql`UPDATE projects SET name=${name},description=${description},status=${status},with_people=${people},updated_at=now() WHERE workspace_id=${workspace(env)} AND context=${ctx} AND id=${id}::uuid`;await activity(sql,env,ctx,'project',id,'update_manual',`Updated project: ${name}`,{reversible:true,operation:'project_update',entity_id:id,before});return json({ok:true,project:await projectById(sql,env,ctx,id)});}
async function searchWorkspace(env,q,ctx){const sql=db(env),ws=workspace(env),needle=`%${q}%`,[tasks,projects,notes,memory,chats]=await Promise.all([sql`SELECT id,title,details,status,priority,due_at,follow_up_at,owner_name,waiting_on,with_people,eisenhower_quadrant FROM tasks WHERE workspace_id=${ws} AND context=${ctx} AND (title ILIKE ${needle} OR COALESCE(details,'') ILIKE ${needle} OR COALESCE(waiting_on,'') ILIKE ${needle} OR COALESCE(owner_name,'') ILIKE ${needle} OR array_to_string(with_people,' ') ILIKE ${needle}) ORDER BY updated_at DESC LIMIT 20`,sql`SELECT id,name,description,status,with_people FROM projects WHERE workspace_id=${ws} AND context=${ctx} AND (name ILIKE ${needle} OR COALESCE(description,'') ILIKE ${needle} OR array_to_string(with_people,' ') ILIKE ${needle}) ORDER BY updated_at DESC LIMIT 12`,sql`SELECT id,title,body,kind,created_at FROM notes WHERE workspace_id=${ws} AND context=${ctx} AND (COALESCE(title,'') ILIKE ${needle} OR body ILIKE ${needle}) ORDER BY created_at DESC LIMIT 12`,sql`SELECT id,title,body,memory_type,created_at FROM memory_entries WHERE workspace_id=${ws} AND context=${ctx} AND (COALESCE(title,'') ILIKE ${needle} OR body ILIKE ${needle}) ORDER BY created_at DESC LIMIT 12`,sql`SELECT role,content,created_at FROM chat_messages WHERE workspace_id=${ws} AND context=${ctx} AND content ILIKE ${needle} ORDER BY created_at DESC LIMIT 10`]);return{context:ctx,tasks,projects,notes,memory,chats};}

export default{async fetch(request,env){const url=new URL(request.url),ctx=contextOf(url.searchParams.get('context'));try{if(url.pathname==='/api/login'&&request.method==='POST'){const{password}=await request.json();if(!env.APP_PASSWORD||!env.SESSION_SECRET)return json({error:'Login is not configured.'},500);if(String(password)!==String(env.APP_PASSWORD))return json({error:'Incorrect password.'},401);return json({ok:true},200,{'set-cookie':sessionCookie(await sign(env.SESSION_SECRET,`my-work:${workspace(env)}`))});}if(url.pathname==='/api/logout'&&request.method==='POST')return json({ok:true},200,{'set-cookie':clearCookie()});if(url.pathname==='/login.html')return env.ASSETS.fetch(request);const authed=await isAuthed(request,env);if(url.pathname.startsWith('/api/')&&!authed)return json({error:'Unauthorized'},401);if(url.pathname==='/api/chat'&&request.method==='POST')return chat(request,env,ctx);if(url.pathname==='/api/state'&&request.method==='GET')return json(await state(env,ctx));if(url.pathname==='/api/undo'&&request.method==='POST')return json(await undoLast(db(env),env,ctx));if(url.pathname==='/api/search'&&request.method==='GET'){const q=String(url.searchParams.get('q')||'').trim();return json(q?await searchWorkspace(env,q,ctx):{context:ctx,tasks:[],projects:[],notes:[],memory:[],chats:[]});}const taskMatch=url.pathname.match(/^\/api\/tasks\/([0-9a-f-]+)$/i);if(taskMatch&&request.method==='PATCH')return patchTask(request,env,ctx,taskMatch[1]);const completeMatch=url.pathname.match(/^\/api\/tasks\/([0-9a-f-]+)\/complete$/i);if(completeMatch&&request.method==='POST'){const sql=db(env),old=await taskById(sql,env,ctx,completeMatch[1]);if(!old)return json({error:'Task not found'},404);const before=snapshotTask(old);await sql`UPDATE tasks SET status='done',completed_at=COALESCE(completed_at,now()),waiting_on=NULL,follow_up_at=NULL,updated_at=now() WHERE workspace_id=${workspace(env)} AND context=${ctx} AND id=${completeMatch[1]}::uuid`;await activity(sql,env,ctx,'task',completeMatch[1],'complete_manual',`Completed task: ${old.title}`,{reversible:true,operation:'task_complete',entity_id:completeMatch[1],before});return json({ok:true,task:await taskById(sql,env,ctx,completeMatch[1])});}const projectMatch=url.pathname.match(/^\/api\/projects\/([0-9a-f-]+)$/i);if(projectMatch&&request.method==='PATCH')return patchProject(request,env,ctx,projectMatch[1]);if(url.pathname.startsWith('/api/'))return json({error:'API route not found.'},404);if(!authed){const loginUrl=new URL('/login.html',url);return env.ASSETS.fetch(new Request(loginUrl,request));}return env.ASSETS.fetch(request);}catch(e){console.error(e);return json({error:e?.message||String(e)},500);}}};